{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.4.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.13.jar",
          "url": "projektor-settings-plugin-3.4.13.jar",
          "size": 46778,
          "sha512": "3ce1c5cc40af8895f85ac17f9b57a19d6db7ddfc4f893737140628a2078fd65bc2654d608b9ef4e0844209bac784ef5b11138e310bbadcc60c910998db6b2025",
          "sha256": "c61d76693d0c456cf0cbb6df7d507511f8ce43c3bb43adaab7c309e2928652f4",
          "sha1": "c4d0e48a11d211d899579037a737b42e3b88594d",
          "md5": "c4ed4c8598e847fd4d46832fd7d0d5a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.13.jar",
          "url": "projektor-settings-plugin-3.4.13.jar",
          "size": 46778,
          "sha512": "3ce1c5cc40af8895f85ac17f9b57a19d6db7ddfc4f893737140628a2078fd65bc2654d608b9ef4e0844209bac784ef5b11138e310bbadcc60c910998db6b2025",
          "sha256": "c61d76693d0c456cf0cbb6df7d507511f8ce43c3bb43adaab7c309e2928652f4",
          "sha1": "c4d0e48a11d211d899579037a737b42e3b88594d",
          "md5": "c4ed4c8598e847fd4d46832fd7d0d5a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.13-sources.jar",
          "url": "projektor-settings-plugin-3.4.13-sources.jar",
          "size": 11643,
          "sha512": "664513d397f8730d59d8665239837eddf10a1d1bcf510cf597d22c44722d99587aa0498819ef668b769aaab2cb892d27fc9587021f1b2264abfb11d42b83ae2b",
          "sha256": "ddebeeee71eeab1125d304ca2a10b5b5a2585732eb3c0a56101212ec2ff72452",
          "sha1": "7896ae573f5fd768931de4605d9491f367387b7a",
          "md5": "414108fb73d84fbbee22d76916256ff6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.13-javadoc.jar",
          "url": "projektor-settings-plugin-3.4.13-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
