{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.4.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.15.jar",
          "url": "projektor-settings-plugin-3.4.15.jar",
          "size": 49942,
          "sha512": "0e3eb2ef0d03e31ef5deddff234486d2f2d6dc96d40c062d23fb0ee8f826662c469270ae6bdc772627f86fcfec88263b151da9d44c61b74c32d0ab35028ee627",
          "sha256": "fd479fad2dfc94d65032c4e59a13e9676105c09e2578ec3b0485f0c3aac90f4d",
          "sha1": "9bd11f0d3feb4202d34bb3fa650e057a7ee4a555",
          "md5": "f2b4bed489181f09e5f6a0f8863abe92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.15.jar",
          "url": "projektor-settings-plugin-3.4.15.jar",
          "size": 49942,
          "sha512": "0e3eb2ef0d03e31ef5deddff234486d2f2d6dc96d40c062d23fb0ee8f826662c469270ae6bdc772627f86fcfec88263b151da9d44c61b74c32d0ab35028ee627",
          "sha256": "fd479fad2dfc94d65032c4e59a13e9676105c09e2578ec3b0485f0c3aac90f4d",
          "sha1": "9bd11f0d3feb4202d34bb3fa650e057a7ee4a555",
          "md5": "f2b4bed489181f09e5f6a0f8863abe92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.15-sources.jar",
          "url": "projektor-settings-plugin-3.4.15-sources.jar",
          "size": 10689,
          "sha512": "5b0891c9598cb9c8a1c13ab5d5ec3671800699514e6ce8074a4ad4ef7c1d1cbb79dc9e3cf9dba7998e1544f6ceca25602626e0a771b7f3af3cc4420bf38c7677",
          "sha256": "dce557da5e6c598fcfa82c7f96b6d1bd4327f3e6f23cdd7a22daaa00a7f06b98",
          "sha1": "95b93cbf3ecc9fcfd24b46d20d1be61e0258c333",
          "md5": "83b3f75427ce82cf623b98c591aa1976"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.15-javadoc.jar",
          "url": "projektor-settings-plugin-3.4.15-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
