{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.8.jar",
          "url": "projektor-settings-plugin-3.5.8.jar",
          "size": 49976,
          "sha512": "036deb0cc79793a51f1b6a5092319d5eb555a0956ac642934f87be5a9e6bc91c8a7889dc293a9e8fbd8b68592692d410559421587f37b6c7e6e93fb7a4ed0035",
          "sha256": "0632d1bfd0d5b1d736d5b06917c2a87dcc89659d5da8224606b0a8a69de5dac1",
          "sha1": "d08964f93129524b5429f2e5ffd016b049cbaa37",
          "md5": "ef3bba1964516249ba3a65489ab0487b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.8.jar",
          "url": "projektor-settings-plugin-3.5.8.jar",
          "size": 49976,
          "sha512": "036deb0cc79793a51f1b6a5092319d5eb555a0956ac642934f87be5a9e6bc91c8a7889dc293a9e8fbd8b68592692d410559421587f37b6c7e6e93fb7a4ed0035",
          "sha256": "0632d1bfd0d5b1d736d5b06917c2a87dcc89659d5da8224606b0a8a69de5dac1",
          "sha1": "d08964f93129524b5429f2e5ffd016b049cbaa37",
          "md5": "ef3bba1964516249ba3a65489ab0487b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.8-sources.jar",
          "url": "projektor-settings-plugin-3.5.8-sources.jar",
          "size": 10687,
          "sha512": "e525b75853c0da655b8d94a3f9b68786f216d781f8a0b020e977fea40a6a97287c71a5531cc76be57734f1c3c702acf75e19f2c1f965b59dc2ff73c61408c961",
          "sha256": "cc97f931623cb9f33319d4eeecfd9a7ae6de124af4c93260cd13ca948a2d1906",
          "sha1": "64988bfb1757298d7af4192bb23e4878fb3f0c11",
          "md5": "3958729dd2d9fa9b980c5db25625d3d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.8-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.8-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
