{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.5.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.5.15.jar",
          "url": "projektor-common-3.5.15.jar",
          "size": 37181,
          "sha512": "09708ce354fb9de506d64ffe4e04f2575fe0a371159e911fc8d0c955a7abcbfd2d8e9d9d4af97bd5fd58ebe8d1f82807f691b47f2696c82db9fc38194e940128",
          "sha256": "3352b94e32b829cdde7f3c0ab08739b4e46e2a081b1f0d3395fc0673c0e0066d",
          "sha1": "f996b45d38f1178320b9d807018e36feb3b9fb33",
          "md5": "0f549d1016d3ee8b77c949871ecf7a99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.5.15.jar",
          "url": "projektor-common-3.5.15.jar",
          "size": 37181,
          "sha512": "09708ce354fb9de506d64ffe4e04f2575fe0a371159e911fc8d0c955a7abcbfd2d8e9d9d4af97bd5fd58ebe8d1f82807f691b47f2696c82db9fc38194e940128",
          "sha256": "3352b94e32b829cdde7f3c0ab08739b4e46e2a081b1f0d3395fc0673c0e0066d",
          "sha1": "f996b45d38f1178320b9d807018e36feb3b9fb33",
          "md5": "0f549d1016d3ee8b77c949871ecf7a99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.5.15-sources.jar",
          "url": "projektor-common-3.5.15-sources.jar",
          "size": 9897,
          "sha512": "38ad730853b75ce9ae80ec0db12d35a2ca51bb2344957ec809b05e306dd2a1034c3fb2726c517b884af6fa3e935eae0b02f4e30ec3eb51295062add84e066a18",
          "sha256": "e9fae3a5524559e70cd29e507b73291dd85fcecd68dc100b1ebe2d2ba641e956",
          "sha1": "3e47323c8ea9a9009babb0f300414a3544102fb9",
          "md5": "934424c8ad8e83ef0086d4402a41a3ec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.5.15-javadoc.jar",
          "url": "projektor-common-3.5.15-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
