{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.7.2.jar",
          "url": "projektor-project-plugin-4.7.2.jar",
          "size": 995437,
          "sha512": "a978e763d90fcc6c6af43ab0761877aa89d9f4a8cdf31e0004bb7f5672fd6cc458e27935941d389a119a6f2d1cb1f37c9738e1781bfac1e829330946b59b7ee6",
          "sha256": "005f24c7e1f163ce84efa40e3ae04e4747dfa5bb5e50c0aa7d7d71f027104df7",
          "sha1": "b605ba3ccf784ef58f090b189615bda6ee198e74",
          "md5": "38630df4019871e9d3f08d426a91ec9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.parchmentmc.librarian.forgegradle",
          "module": "org.parchmentmc.librarian.forgegradle.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "fabric-loom",
          "module": "fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "com.modrinth.minotaur.gradle.plugin",
          "version": {
            "requires": "2.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.7.2.jar",
          "url": "projektor-project-plugin-4.7.2.jar",
          "size": 995437,
          "sha512": "a978e763d90fcc6c6af43ab0761877aa89d9f4a8cdf31e0004bb7f5672fd6cc458e27935941d389a119a6f2d1cb1f37c9738e1781bfac1e829330946b59b7ee6",
          "sha256": "005f24c7e1f163ce84efa40e3ae04e4747dfa5bb5e50c0aa7d7d71f027104df7",
          "sha1": "b605ba3ccf784ef58f090b189615bda6ee198e74",
          "md5": "38630df4019871e9d3f08d426a91ec9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.7.2-sources.jar",
          "url": "projektor-project-plugin-4.7.2-sources.jar",
          "size": 93284,
          "sha512": "215936cfec5609ade6f44e60cdb76aafe04df55015881963fd63b75e7ef2426fd1ccc394fdc60179221f8d46739652b41ab8912650f0170f29e080bb2a2ba05e",
          "sha256": "ecdf24130c775b066bca55013795ca0011c5aa7e8f74f7697f7e64efef0c4400",
          "sha1": "d671ad820ed6ec77d55db9bd261d1c5f02f09709",
          "md5": "461958027d2fd2d9023999a3f101f5aa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.7.2-javadoc.jar",
          "url": "projektor-project-plugin-4.7.2-javadoc.jar",
          "size": 261,
          "sha512": "a5cf920812331563fc3819cf0e07080787641bb7416040fe04fd7993f1f064d3b3449b6329a0ed418c4c48130bb4ebe231b2984b8954796538ad86db67203a0d",
          "sha256": "0ee917eb7bf33a787f3948fa31fbdf157509977b79a93f0ffe3685208cb2cf66",
          "sha1": "6ef41949cc6fdb646714fc0e1a107a84309f6ea4",
          "md5": "8ff29c056a86c41b230544ba425bea58"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.7.2.jar",
          "url": "projektor-project-plugin-4.7.2.jar",
          "size": 995437,
          "sha512": "a978e763d90fcc6c6af43ab0761877aa89d9f4a8cdf31e0004bb7f5672fd6cc458e27935941d389a119a6f2d1cb1f37c9738e1781bfac1e829330946b59b7ee6",
          "sha256": "005f24c7e1f163ce84efa40e3ae04e4747dfa5bb5e50c0aa7d7d71f027104df7",
          "sha1": "b605ba3ccf784ef58f090b189615bda6ee198e74",
          "md5": "38630df4019871e9d3f08d426a91ec9d"
        }
      ]
    }
  ]
}
