{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor",
    "version": "8.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-8.0.5.jar",
          "url": "projektor-8.0.5.jar",
          "size": 306274,
          "sha512": "400d5be1d436b60fbacef75682608a5a94f70de0cfa7de5b10dd4f813adec5b7c4e0dad14197cd716b3558b8b964044f0cb5bcbe711d8c40986c201000f6d6be",
          "sha256": "02d44ee9b541e6d34feeb8ebcb992467e6c5f3e38e9ebab4a4f40d2cdc9abf6d",
          "sha1": "20f04241f2b47b5f92d9a366f52cf00716370181",
          "md5": "c44ee9211b320a1814af8eed10e5ee00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-8.0.5.jar",
          "url": "projektor-8.0.5.jar",
          "size": 306274,
          "sha512": "400d5be1d436b60fbacef75682608a5a94f70de0cfa7de5b10dd4f813adec5b7c4e0dad14197cd716b3558b8b964044f0cb5bcbe711d8c40986c201000f6d6be",
          "sha256": "02d44ee9b541e6d34feeb8ebcb992467e6c5f3e38e9ebab4a4f40d2cdc9abf6d",
          "sha1": "20f04241f2b47b5f92d9a366f52cf00716370181",
          "md5": "c44ee9211b320a1814af8eed10e5ee00"
        }
      ]
    }
  ]
}
