{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.2.jar",
          "url": "projektor-settings-plugin-4.2.2.jar",
          "size": 271414,
          "sha512": "29569e94fe93272aae16258dad437cf66c19b8fee3eb987951da9c6b2bcdb10a36117c751db9e32e2fd7d4abfbc55b61b7210f94cf374987d081dd14db6382f7",
          "sha256": "6c4588d682c4052a6aa552b98bf932e21deedd710fd0145ff538ae55c6535c3b",
          "sha1": "c5e7f557a7bbc8bfc7ddfb8dc390c152b97cc0ee",
          "md5": "4e8538e825739f434d9b7d565dd7143b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.2.jar",
          "url": "projektor-settings-plugin-4.2.2.jar",
          "size": 271414,
          "sha512": "29569e94fe93272aae16258dad437cf66c19b8fee3eb987951da9c6b2bcdb10a36117c751db9e32e2fd7d4abfbc55b61b7210f94cf374987d081dd14db6382f7",
          "sha256": "6c4588d682c4052a6aa552b98bf932e21deedd710fd0145ff538ae55c6535c3b",
          "sha1": "c5e7f557a7bbc8bfc7ddfb8dc390c152b97cc0ee",
          "md5": "4e8538e825739f434d9b7d565dd7143b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.2-sources.jar",
          "url": "projektor-settings-plugin-4.2.2-sources.jar",
          "size": 11080,
          "sha512": "f6b5a79364facf9923f63f3a136baf73875a718f8842861f8c8554a23567895da8b4ce7c323bfed672d62e4b42a917809db9e9b03b9f3e28b1502e88ae4fc4ab",
          "sha256": "d5f69e47a1f06b74c941755157171c384783b60ee6f5b3f0cdb0b68f9dfccc36",
          "sha1": "4078f4a3504910d38b5f5447012630f3d9bdc4c6",
          "md5": "e5220574d0a8da8c3ba748ba99c4d47c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.2-javadoc.jar",
          "url": "projektor-settings-plugin-4.2.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.2.jar",
          "url": "projektor-settings-plugin-4.2.2.jar",
          "size": 271414,
          "sha512": "29569e94fe93272aae16258dad437cf66c19b8fee3eb987951da9c6b2bcdb10a36117c751db9e32e2fd7d4abfbc55b61b7210f94cf374987d081dd14db6382f7",
          "sha256": "6c4588d682c4052a6aa552b98bf932e21deedd710fd0145ff538ae55c6535c3b",
          "sha1": "c5e7f557a7bbc8bfc7ddfb8dc390c152b97cc0ee",
          "md5": "4e8538e825739f434d9b7d565dd7143b"
        }
      ]
    }
  ]
}
