{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "3.2.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.2.28.jar",
          "url": "projektor-project-plugin-3.2.28.jar",
          "size": 367443,
          "sha512": "0788e790db3b97dca190c3e51cacf6e19e8869c131217b641426a5a8770e4afe5eb0cb5c0ea383a10b05dc0b8547bd9f0d620c998a4f7f38cda869f7012356c1",
          "sha256": "22677bb2512facd1a111ef062ac39f8d1f24ed1ca9f083c3f7b82bac6fc1bd78",
          "sha1": "21bff012a5c63b3358d1514aa8945283936d2d05",
          "md5": "8a81a51aa9a36a6e437d8572c11d1538"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-3.2.28.jar",
          "url": "projektor-project-plugin-3.2.28.jar",
          "size": 367443,
          "sha512": "0788e790db3b97dca190c3e51cacf6e19e8869c131217b641426a5a8770e4afe5eb0cb5c0ea383a10b05dc0b8547bd9f0d620c998a4f7f38cda869f7012356c1",
          "sha256": "22677bb2512facd1a111ef062ac39f8d1f24ed1ca9f083c3f7b82bac6fc1bd78",
          "sha1": "21bff012a5c63b3358d1514aa8945283936d2d05",
          "md5": "8a81a51aa9a36a6e437d8572c11d1538"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.2.28-sources.jar",
          "url": "projektor-project-plugin-3.2.28-sources.jar",
          "size": 56143,
          "sha512": "5f0a4df8c9b275dce01bf4fca1ae8b6c9c592c457039b62b7b364f16845c3834006790d8a150039c7e2d1d26e89f09c2c55c7cc1d04c15121f0ad84ca72ead83",
          "sha256": "af07983e4a622ee4cd3e10b08ca86be5b5a0fe541fc1882ea0ae0db11b0ef1c9",
          "sha1": "8c06c40daeb44cceb1d0fa20373539e53a255d58",
          "md5": "347b39639996662f50564a3957e8cdfc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.2.28-javadoc.jar",
          "url": "projektor-project-plugin-3.2.28-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
