{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-6.0.3.jar",
          "url": "project-plugin-6.0.3.jar",
          "size": 300868,
          "sha512": "e4e73081c29b37935e0aa337a252b4f61abb1117471392e763642ae19a0e15b09b7ca673376564e20746fd8425a7c2e7e7013de4503cc6b41684475eb1142a4d",
          "sha256": "d8ae57ac24e17a0887108739adb250ee9cce85f5d97bca50cbe8d00a9835bfa4",
          "sha1": "60b58a1e32d924d1f76ce8e6b9bae5c775e90fa8",
          "md5": "379df8840c2fc2f1f80f5d2946ed6011"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.9"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-6.0.3.jar",
          "url": "project-plugin-6.0.3.jar",
          "size": 300868,
          "sha512": "e4e73081c29b37935e0aa337a252b4f61abb1117471392e763642ae19a0e15b09b7ca673376564e20746fd8425a7c2e7e7013de4503cc6b41684475eb1142a4d",
          "sha256": "d8ae57ac24e17a0887108739adb250ee9cce85f5d97bca50cbe8d00a9835bfa4",
          "sha1": "60b58a1e32d924d1f76ce8e6b9bae5c775e90fa8",
          "md5": "379df8840c2fc2f1f80f5d2946ed6011"
        }
      ]
    }
  ]
}
