{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "5.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-5.0.5.jar",
          "url": "project-plugin-5.0.5.jar",
          "size": 299124,
          "sha512": "f388c9ba0ed37d9972288d5ed5bbae4c852c1a6a4d2a95ab2973a5a8e4781621c98f0d04d52805a1502cefd5dffbcd24f813ace7666ed29ef6a1b03ecf52d5b0",
          "sha256": "128dd9037fb41a42f28d798a7f633fd889a47445a031a3c28cf4b8716197cc89",
          "sha1": "c83a718da40329656bce34bc8238b78bcb7a49ea",
          "md5": "6049bc381242d8244e06302cfd5312e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.7"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-5.0.5.jar",
          "url": "project-plugin-5.0.5.jar",
          "size": 299124,
          "sha512": "f388c9ba0ed37d9972288d5ed5bbae4c852c1a6a4d2a95ab2973a5a8e4781621c98f0d04d52805a1502cefd5dffbcd24f813ace7666ed29ef6a1b03ecf52d5b0",
          "sha256": "128dd9037fb41a42f28d798a7f633fd889a47445a031a3c28cf4b8716197cc89",
          "sha1": "c83a718da40329656bce34bc8238b78bcb7a49ea",
          "md5": "6049bc381242d8244e06302cfd5312e8"
        }
      ]
    }
  ]
}
