{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.6.4.jar",
          "url": "projektor-common-3.6.4.jar",
          "size": 56041,
          "sha512": "0534a0298d62f243199aadd2efcf1778ab144f1b0e3160e981a4f4c6fbbc0d53da777f3de5a5cc4ff36874796ef38053f818411b6cf6bb2a2425e67f3258d101",
          "sha256": "79e1182c85bb784b69d5c6c3ec7c391b8970031876bf58a63000b1b3b27081fe",
          "sha1": "dbc662e73591c46b3f58978bb512d789b8062d14",
          "md5": "1e920c4d3e47f4e24ff59547b437ff07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.6.4.jar",
          "url": "projektor-common-3.6.4.jar",
          "size": 56041,
          "sha512": "0534a0298d62f243199aadd2efcf1778ab144f1b0e3160e981a4f4c6fbbc0d53da777f3de5a5cc4ff36874796ef38053f818411b6cf6bb2a2425e67f3258d101",
          "sha256": "79e1182c85bb784b69d5c6c3ec7c391b8970031876bf58a63000b1b3b27081fe",
          "sha1": "dbc662e73591c46b3f58978bb512d789b8062d14",
          "md5": "1e920c4d3e47f4e24ff59547b437ff07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.4-sources.jar",
          "url": "projektor-common-3.6.4-sources.jar",
          "size": 13851,
          "sha512": "5a6bd455a2ddefab8c1863b27c1711173a89336f411a8a717d749860e8ec27ce2a7105e81efac7e499616d7c9a1d0038281c2b3a05d350c93ce14a9d733d9514",
          "sha256": "ed191db86f624a73bfd547eec1993db4ee3acce92e010e43c27b2a2385c8523e",
          "sha1": "fe5e71fe377e974c24ed07f84fd0c7ea3b44bccc",
          "md5": "4b4a2c1f541a57b46fe26d1124431e15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.4-javadoc.jar",
          "url": "projektor-common-3.6.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
