{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.0.jar",
          "url": "projektor-project-plugin-4.6.0.jar",
          "size": 776641,
          "sha512": "5cd264c2193ff7c2879d4add73248ba853e106e125a82a7e5ea52726dfb7f03193422055d603e58fe43be35cc1f8c4ddda8308325f2bc5d2ad9c94e26fc4a0b8",
          "sha256": "babc5980e41ba3814bc9d37f9f49b37fac3ca599becae02087543dbddd716629",
          "sha1": "69c13594fcadd9611058c37d2fff45f84459865f",
          "md5": "c194c1937478087b1533daec4b18b422"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.15"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.6.12"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta2"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta2"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "com.modrinth.minotaur.gradle.plugin",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "fabric-loom",
          "module": "fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.13.3"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "7.0.0-beta.45"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.6.0.jar",
          "url": "projektor-project-plugin-4.6.0.jar",
          "size": 776641,
          "sha512": "5cd264c2193ff7c2879d4add73248ba853e106e125a82a7e5ea52726dfb7f03193422055d603e58fe43be35cc1f8c4ddda8308325f2bc5d2ad9c94e26fc4a0b8",
          "sha256": "babc5980e41ba3814bc9d37f9f49b37fac3ca599becae02087543dbddd716629",
          "sha1": "69c13594fcadd9611058c37d2fff45f84459865f",
          "md5": "c194c1937478087b1533daec4b18b422"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.0-sources.jar",
          "url": "projektor-project-plugin-4.6.0-sources.jar",
          "size": 82912,
          "sha512": "eb66e47aa9ac705f8ab155a321e09bb84d4c78add97328232645064519d124222682bf68d42a0ae911464deaa2c8d7b1e402b5cbb7149ec8e9252f55fab8f086",
          "sha256": "6b96a4d14e6c755569e0829417febe58dd1942a9a25c392278740903855bf3a8",
          "sha1": "1954bb548989994eb8af8b099dd27ca6c05c2862",
          "md5": "2d0a3b5888dff43eebc614df188b9bbd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.0-javadoc.jar",
          "url": "projektor-project-plugin-4.6.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.0.jar",
          "url": "projektor-project-plugin-4.6.0.jar",
          "size": 776641,
          "sha512": "5cd264c2193ff7c2879d4add73248ba853e106e125a82a7e5ea52726dfb7f03193422055d603e58fe43be35cc1f8c4ddda8308325f2bc5d2ad9c94e26fc4a0b8",
          "sha256": "babc5980e41ba3814bc9d37f9f49b37fac3ca599becae02087543dbddd716629",
          "sha1": "69c13594fcadd9611058c37d2fff45f84459865f",
          "md5": "c194c1937478087b1533daec4b18b422"
        }
      ]
    }
  ]
}
