package io.github.diskria.projektor.configurations

import io.github.diskria.projektor.common.configurations.IAndroidApplicationConfiguration

open class AndroidApplicationConfiguration : IAndroidApplicationConfiguration
