{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.7.jar",
          "url": "projektor-project-plugin-4.6.7.jar",
          "size": 899404,
          "sha512": "d51b79cf90bb05f97047f568d2b8f69f0dff43cd3a3693a1199f7f7120598e4e744f65f6fe404bfdb1b29fa5fe8e451cf1a232445ad3c181df22dcf4eafa5e72",
          "sha256": "fc0b6080a9a90adedae5017686f7fb888fabc3d0b727ca01ea7d33f2ff85f526",
          "sha1": "9e03ecb2ab708c2489d540c849b95ff174e6efee",
          "md5": "d89b639e7d1a8166d633fc900c4d8995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "com.modrinth.minotaur.gradle.plugin",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "fabric-loom",
          "module": "fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.6.7.jar",
          "url": "projektor-project-plugin-4.6.7.jar",
          "size": 899404,
          "sha512": "d51b79cf90bb05f97047f568d2b8f69f0dff43cd3a3693a1199f7f7120598e4e744f65f6fe404bfdb1b29fa5fe8e451cf1a232445ad3c181df22dcf4eafa5e72",
          "sha256": "fc0b6080a9a90adedae5017686f7fb888fabc3d0b727ca01ea7d33f2ff85f526",
          "sha1": "9e03ecb2ab708c2489d540c849b95ff174e6efee",
          "md5": "d89b639e7d1a8166d633fc900c4d8995"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.7-sources.jar",
          "url": "projektor-project-plugin-4.6.7-sources.jar",
          "size": 83389,
          "sha512": "c78832659aab681bbdad41dce796ae3f461d0840e0143997d12195a3f8c6aa314452cb4facdfe88c83cbb99b45183ad374bf8d0a26f6bc0186b1c78983639c44",
          "sha256": "d00b69de1f9d2f3bf7be70fcc83b4dd0f56f1dab35d008f858c20d1e38784e38",
          "sha1": "e0eb639f686e2da3ccfa5b831e720cc8ebe8f471",
          "md5": "a21f5702a368b77583ff6a9d1b0559e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.7-javadoc.jar",
          "url": "projektor-project-plugin-4.6.7-javadoc.jar",
          "size": 261,
          "sha512": "8b46769d1b45676258a93364ff90ebe703cca1ab919ef3a99534b8384e2b598ab92a09029a10c49f37a29e94b44a89c21680e33261e25c3641c2c9224fc3edfc",
          "sha256": "b1f7e86a073b012f5ceea561ac5a317267a358e824375ddd1fa8cf522caf9301",
          "sha1": "31c71756996f784d9c8a2575b741d7fa8c37d336",
          "md5": "5c7ac60d4b1641b80b6a1f477d47ce0f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.7.jar",
          "url": "projektor-project-plugin-4.6.7.jar",
          "size": 899404,
          "sha512": "d51b79cf90bb05f97047f568d2b8f69f0dff43cd3a3693a1199f7f7120598e4e744f65f6fe404bfdb1b29fa5fe8e451cf1a232445ad3c181df22dcf4eafa5e72",
          "sha256": "fc0b6080a9a90adedae5017686f7fb888fabc3d0b727ca01ea7d33f2ff85f526",
          "sha1": "9e03ecb2ab708c2489d540c849b95ff174e6efee",
          "md5": "d89b639e7d1a8166d633fc900c4d8995"
        }
      ]
    }
  ]
}
