{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.0.jar",
          "url": "projektor-settings-plugin-4.7.0.jar",
          "size": 362917,
          "sha512": "069d4b09a0b6e8670995bf5ec4774fa821e98c53cd0d1c6d70d8e12d37ecc13a93cc5064370b8a0f11b6cfb19bd447fda105e44d2668557676f9873541e1572b",
          "sha256": "eb6d5b37f4bda75da7458f26519f5a739242c05434492fe14b2e11085865c88d",
          "sha1": "432146ad2079b0735ed75b0787a30d82339b8dd7",
          "md5": "60a9e4f96904292e478e624b91ed637e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.0.jar",
          "url": "projektor-settings-plugin-4.7.0.jar",
          "size": 362917,
          "sha512": "069d4b09a0b6e8670995bf5ec4774fa821e98c53cd0d1c6d70d8e12d37ecc13a93cc5064370b8a0f11b6cfb19bd447fda105e44d2668557676f9873541e1572b",
          "sha256": "eb6d5b37f4bda75da7458f26519f5a739242c05434492fe14b2e11085865c88d",
          "sha1": "432146ad2079b0735ed75b0787a30d82339b8dd7",
          "md5": "60a9e4f96904292e478e624b91ed637e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.0-sources.jar",
          "url": "projektor-settings-plugin-4.7.0-sources.jar",
          "size": 12837,
          "sha512": "7da75dd1cb4d8469cf2f047f893754419b6c6b386f77efd17327824e7ef4a6f48e25299633490667e84fc3993a53b77588f0ea7eaa376c279000146481a38c32",
          "sha256": "7251437c29b9150a70d54cfbb82c67881080357f6cee317a194aaa090c7fd730",
          "sha1": "45b6ce923385255d4302d6d9d8d0fb3f72b5bd42",
          "md5": "c4892c09f686932833c83310d73d9ed5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.0-javadoc.jar",
          "url": "projektor-settings-plugin-4.7.0-javadoc.jar",
          "size": 261,
          "sha512": "a68b1fa417356398499d39de1a9526a3009184e0ff39d1f67b12d56a1fb7d42a706dfc8590024f17c045b276383737d11ac8b21f5a615ea04986309842be488f",
          "sha256": "7252e7ac632dc7a953d22f003aa2254aefcbb4da5adb2d2f19fbd412031fa18d",
          "sha1": "cf1edaf636938e2b232c45ba83926524f0a483f5",
          "md5": "2b66c9e440b4a28cdcce49b26217e79e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.0.jar",
          "url": "projektor-settings-plugin-4.7.0.jar",
          "size": 362917,
          "sha512": "069d4b09a0b6e8670995bf5ec4774fa821e98c53cd0d1c6d70d8e12d37ecc13a93cc5064370b8a0f11b6cfb19bd447fda105e44d2668557676f9873541e1572b",
          "sha256": "eb6d5b37f4bda75da7458f26519f5a739242c05434492fe14b2e11085865c88d",
          "sha1": "432146ad2079b0735ed75b0787a30d82339b8dd7",
          "md5": "60a9e4f96904292e478e624b91ed637e"
        }
      ]
    }
  ]
}
