{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.4.jar",
          "url": "projektor-settings-plugin-3.6.4.jar",
          "size": 53203,
          "sha512": "1c3e9acc1bae0a35157494e116b9ea154c9010382d6ce1f65a6730278a7ed1aff7abddfc1837b08c1cacc5c9b5f3b3ba29aaf2c0cc7a8d0f5f42967598d8af8c",
          "sha256": "b0ee980450ca071de9fa074717f16c229cc4f55eb7565e09a5a4c4ea05f49e17",
          "sha1": "ff6a1641aad8a5c892bdef964de3f7906b86236a",
          "md5": "b9165332eceda1dc3e630de62bed6c8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.4.jar",
          "url": "projektor-settings-plugin-3.6.4.jar",
          "size": 53203,
          "sha512": "1c3e9acc1bae0a35157494e116b9ea154c9010382d6ce1f65a6730278a7ed1aff7abddfc1837b08c1cacc5c9b5f3b3ba29aaf2c0cc7a8d0f5f42967598d8af8c",
          "sha256": "b0ee980450ca071de9fa074717f16c229cc4f55eb7565e09a5a4c4ea05f49e17",
          "sha1": "ff6a1641aad8a5c892bdef964de3f7906b86236a",
          "md5": "b9165332eceda1dc3e630de62bed6c8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.4-sources.jar",
          "url": "projektor-settings-plugin-3.6.4-sources.jar",
          "size": 11245,
          "sha512": "cd81ddda16fa217373e676fb5fe7baed13de31490e16b63778c0746213a516f121a00652b480b409b451a668342a2cf954a07c98ec6b11caa3f50290de3812eb",
          "sha256": "eb58f98b8c70d2ad869d3ccf611478b526b421f3d46477b01c52f9a0a411f499",
          "sha1": "814788aba290fe9c0d521e838718ccc960e7f917",
          "md5": "25222609e235889ce968459f3c3753d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.4-javadoc.jar",
          "url": "projektor-settings-plugin-3.6.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
