{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.2.jar",
          "url": "projektor-settings-plugin-3.5.2.jar",
          "size": 49975,
          "sha512": "772e954b6274ef351ff5b7acb60780cd1679fd4b2e10bd66f870f76c7cc40f50a935d2335eb3836148f2958adaceb88817dc5fd3bbc1859b207319557784a015",
          "sha256": "d1b78ff815dee0bd93b69ea1aa9420ad931e39fc9a1f0cd208c21c06cdc6d3f6",
          "sha1": "03a6add3343e4fcd35a96d35a4a9008ad4b5cdf5",
          "md5": "9cc39a368d25031381a1b35d4b2801a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.2.jar",
          "url": "projektor-settings-plugin-3.5.2.jar",
          "size": 49975,
          "sha512": "772e954b6274ef351ff5b7acb60780cd1679fd4b2e10bd66f870f76c7cc40f50a935d2335eb3836148f2958adaceb88817dc5fd3bbc1859b207319557784a015",
          "sha256": "d1b78ff815dee0bd93b69ea1aa9420ad931e39fc9a1f0cd208c21c06cdc6d3f6",
          "sha1": "03a6add3343e4fcd35a96d35a4a9008ad4b5cdf5",
          "md5": "9cc39a368d25031381a1b35d4b2801a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.2-sources.jar",
          "url": "projektor-settings-plugin-3.5.2-sources.jar",
          "size": 10687,
          "sha512": "6394b1b50aa7d010ad03c574246eb40b0b71291a2cb664cc01a45d63d8773ab4b723c360afebc5b23eb160eb1aeebbfd7be8e623380658de085c3a10ce9ab7c2",
          "sha256": "3f62d5d4c9688d263b8df82df110fbe11cf9581566ac832d14db2050d1937e8d",
          "sha1": "f6da91dc1da632b7a310ea3a6157e8e304e9bdc5",
          "md5": "ed17d7909d35bdbebe040eac5927e979"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.2-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
