{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-5.0.0.jar",
          "url": "project-plugin-5.0.0.jar",
          "size": 293503,
          "sha512": "6db50beb9028507af2e24373f42d1b5a14ba03d67300cbd584ad13cb2b4f34123015827b4c56c4725835db996cc5d7c04ad021d851e5aee6b9986958f2d3eab6",
          "sha256": "1b7879b1622d3a30357aded1720abf0f5637ffb0d3d8f48ae4da7f2e3304cd0a",
          "sha1": "c7fe786ef2643f675fd164843673855944debac8",
          "md5": "43e7bfc5449eef6c765ec4d75261ccba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.7"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-5.0.0.jar",
          "url": "project-plugin-5.0.0.jar",
          "size": 293503,
          "sha512": "6db50beb9028507af2e24373f42d1b5a14ba03d67300cbd584ad13cb2b4f34123015827b4c56c4725835db996cc5d7c04ad021d851e5aee6b9986958f2d3eab6",
          "sha256": "1b7879b1622d3a30357aded1720abf0f5637ffb0d3d8f48ae4da7f2e3304cd0a",
          "sha1": "c7fe786ef2643f675fd164843673855944debac8",
          "md5": "43e7bfc5449eef6c765ec4d75261ccba"
        }
      ]
    }
  ]
}
