{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "5.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-5.0.6.jar",
          "url": "project-plugin-5.0.6.jar",
          "size": 301742,
          "sha512": "91890f6240ff5f648898865d785ee17c4e4d5b5989f0326ff287526b82fe051195d7fb13f815ec97d55b84c51604c60c0c56e71d46edc7725d0089e493a2efb5",
          "sha256": "3b284a6bad06ee02b0b54e2b7b03bf7e2c0b19a573462ec10a0d5ea54e65fe55",
          "sha1": "3c16d98c2fb3c40d8d4089c2d3d22280d4333619",
          "md5": "1b40eb786184382763e995a0f1d0c12e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.9"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-5.0.6.jar",
          "url": "project-plugin-5.0.6.jar",
          "size": 301742,
          "sha512": "91890f6240ff5f648898865d785ee17c4e4d5b5989f0326ff287526b82fe051195d7fb13f815ec97d55b84c51604c60c0c56e71d46edc7725d0089e493a2efb5",
          "sha256": "3b284a6bad06ee02b0b54e2b7b03bf7e2c0b19a573462ec10a0d5ea54e65fe55",
          "sha1": "3c16d98c2fb3c40d8d4089c2d3d22280d4333619",
          "md5": "1b40eb786184382763e995a0f1d0c12e"
        }
      ]
    }
  ]
}
