{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.9.jar",
          "url": "projektor-settings-plugin-3.4.9.jar",
          "size": 44426,
          "sha512": "61bb10aaee4151b448b3ec44540964319dae9abdd2d2de980447e6ffbdf7d7381f836631405beaa28778ad573f2af574cf734cac44aaaf0c6a91e71aa3c9d6bf",
          "sha256": "cc31fa66310cf0dc0458cbc17904a3a514c7ee428f59613d08a0a78cee8b3e47",
          "sha1": "5c8fcd77a20901254524439e6ef7dc3f54b682a6",
          "md5": "d90845e2acaf7528399d2c8c81128145"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.9.jar",
          "url": "projektor-settings-plugin-3.4.9.jar",
          "size": 44426,
          "sha512": "61bb10aaee4151b448b3ec44540964319dae9abdd2d2de980447e6ffbdf7d7381f836631405beaa28778ad573f2af574cf734cac44aaaf0c6a91e71aa3c9d6bf",
          "sha256": "cc31fa66310cf0dc0458cbc17904a3a514c7ee428f59613d08a0a78cee8b3e47",
          "sha1": "5c8fcd77a20901254524439e6ef7dc3f54b682a6",
          "md5": "d90845e2acaf7528399d2c8c81128145"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.9-sources.jar",
          "url": "projektor-settings-plugin-3.4.9-sources.jar",
          "size": 9104,
          "sha512": "590ff17f4022ceb5246923ee6a1468efeddf0347204c584193c7003bba88eca942ee2d1bd89c9a568222959a47a8a7a6a739304a84494b4ec14fa0997d45f192",
          "sha256": "da421a2e58930e8ff0860471ca9c841989c615f1a5c85d6748ef895ca1e50e0c",
          "sha1": "313e816506eea1635d3a4ffe12d35be4b27b11b4",
          "md5": "5e987ea0c94be7b1f1fa657d57dd90e5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.9-javadoc.jar",
          "url": "projektor-settings-plugin-3.4.9-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
