{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.12.jar",
          "url": "projektor-settings-plugin-3.6.12.jar",
          "size": 53882,
          "sha512": "912cfe908b89e5ee07a766d90bc3c1e3d28db13e2cef86308033172c5afe3693ef87fe3b988da945c0d9a9e619d44649c5e89d94d3824caeaca33973ae3bf542",
          "sha256": "36fdfd7b9cc7fbf8423b2ec7b31f55c479568948fe17555525c9d0ded6fc7b46",
          "sha1": "e61f064cba20ede18ce4eabc4dda969a940b2068",
          "md5": "72a70097762dc94f7cf2e07d0c67b728"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.6.12"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.12.jar",
          "url": "projektor-settings-plugin-3.6.12.jar",
          "size": 53882,
          "sha512": "912cfe908b89e5ee07a766d90bc3c1e3d28db13e2cef86308033172c5afe3693ef87fe3b988da945c0d9a9e619d44649c5e89d94d3824caeaca33973ae3bf542",
          "sha256": "36fdfd7b9cc7fbf8423b2ec7b31f55c479568948fe17555525c9d0ded6fc7b46",
          "sha1": "e61f064cba20ede18ce4eabc4dda969a940b2068",
          "md5": "72a70097762dc94f7cf2e07d0c67b728"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.12-sources.jar",
          "url": "projektor-settings-plugin-3.6.12-sources.jar",
          "size": 10898,
          "sha512": "8d74584ed97af46b1c4cc1d7a4f80d86576e8d5fda4f78f92f36e987c6f15f9129b41b6d2ea373195b1882fdb768b75ddee460821db2894848b59644c78c599d",
          "sha256": "a90803ad175ea2a03c6c0257da952d400511dc27282ea43da998ef23de438fbb",
          "sha1": "1b2b7fa5cd0b729d6820c3dd4f716eb4d2e28091",
          "md5": "88f34af2dbcf873256ec18c134f1740f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.12-javadoc.jar",
          "url": "projektor-settings-plugin-3.6.12-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
