{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.4.6.jar",
          "url": "projektor-common-3.4.6.jar",
          "size": 22186,
          "sha512": "a1977cf8536f674c6eda3469584e598584de406951313c8efee96a04b350ae246e44579d1fefcb11e03387d572c323cab1f1ed7786a752d5d7f0db07ead24aa6",
          "sha256": "e754c8c25e46937a3a6a4e55d651398889c256c9bf007390a14eabf0791d3d74",
          "sha1": "87f274397936dc425a15aeaf3e18334ce2b91797",
          "md5": "d717a2779404d60bde69fc3caf36392b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.4.6.jar",
          "url": "projektor-common-3.4.6.jar",
          "size": 22186,
          "sha512": "a1977cf8536f674c6eda3469584e598584de406951313c8efee96a04b350ae246e44579d1fefcb11e03387d572c323cab1f1ed7786a752d5d7f0db07ead24aa6",
          "sha256": "e754c8c25e46937a3a6a4e55d651398889c256c9bf007390a14eabf0791d3d74",
          "sha1": "87f274397936dc425a15aeaf3e18334ce2b91797",
          "md5": "d717a2779404d60bde69fc3caf36392b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.6-sources.jar",
          "url": "projektor-common-3.4.6-sources.jar",
          "size": 5720,
          "sha512": "9e42482e967a479ae1784244e0653d314a988c025788c2018d4e6d0512a791869e39d514466d065892bc82ae259c5b48a494f29288ed3332c2197b2be006a3d5",
          "sha256": "3fa5e965b4ab5848445292398b3eec550e9991948efa32b95186c0a5a971b9ad",
          "sha1": "14df211d4dd0eebdaa2df342cdeace5468e1ab49",
          "md5": "4e3828575657510579d185523c786b11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.6-javadoc.jar",
          "url": "projektor-common-3.4.6-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
