{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.4.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.10.jar",
          "url": "projektor-settings-plugin-3.4.10.jar",
          "size": 43091,
          "sha512": "34307fbf19166b2b276ea26bfbaf1676342a384cec2088b4973bc1e3ae98a78e115302d028ff8880548998e78e9818c98862dd50dd54a4cd3989cb1e9fe7cebc",
          "sha256": "7fe004bef56fc7ae7d9605bd598afb03583956e8db2c2ab52c185e7c125f16ab",
          "sha1": "c5ea20708905055a8323ba24d408824e8167e4de",
          "md5": "70d3ad3a94a8b5616725c8ec45d5dec2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.10.jar",
          "url": "projektor-settings-plugin-3.4.10.jar",
          "size": 43091,
          "sha512": "34307fbf19166b2b276ea26bfbaf1676342a384cec2088b4973bc1e3ae98a78e115302d028ff8880548998e78e9818c98862dd50dd54a4cd3989cb1e9fe7cebc",
          "sha256": "7fe004bef56fc7ae7d9605bd598afb03583956e8db2c2ab52c185e7c125f16ab",
          "sha1": "c5ea20708905055a8323ba24d408824e8167e4de",
          "md5": "70d3ad3a94a8b5616725c8ec45d5dec2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.10-sources.jar",
          "url": "projektor-settings-plugin-3.4.10-sources.jar",
          "size": 8864,
          "sha512": "2f90f60c46ac7641a41ecb0d2c94d7682838ceaf395ab2d506e5dee2c61a72e3b7645d9fce569090c1475e30402a9f4b3b68bcedd50585c1ed8ee0fe5dfd8fb1",
          "sha256": "6b93182c0ff39b1c20686144691ba338f7f3826bf4fb96ff7317b8deba43ed55",
          "sha1": "babb48403230df1ec15709248bd2fe9b19ab1600",
          "md5": "df64688b86ec4d9abe3c99236870da33"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.10-javadoc.jar",
          "url": "projektor-settings-plugin-3.4.10-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
