{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.5.8.jar",
          "url": "projektor-common-3.5.8.jar",
          "size": 34129,
          "sha512": "42c39c0e25d0012363694604fbdb6fc124017a542e44488b761a8ec33eada4333c62d7c8a95f570fb14a5f1e325be93bb20a952384ce8549820585cc7a95da28",
          "sha256": "188cba4436a94ea12d23d69b423ea26b6427f7b6f197aa0dfedd39ef119f20da",
          "sha1": "7f3240f8c533f18bbe4be864d3516b0d16591a8b",
          "md5": "baa1c04aea3882f0ee9c7a92b54ef917"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.5.8.jar",
          "url": "projektor-common-3.5.8.jar",
          "size": 34129,
          "sha512": "42c39c0e25d0012363694604fbdb6fc124017a542e44488b761a8ec33eada4333c62d7c8a95f570fb14a5f1e325be93bb20a952384ce8549820585cc7a95da28",
          "sha256": "188cba4436a94ea12d23d69b423ea26b6427f7b6f197aa0dfedd39ef119f20da",
          "sha1": "7f3240f8c533f18bbe4be864d3516b0d16591a8b",
          "md5": "baa1c04aea3882f0ee9c7a92b54ef917"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.5.8-sources.jar",
          "url": "projektor-common-3.5.8-sources.jar",
          "size": 9411,
          "sha512": "03a19908b6a83112d6f335c08025964383d9cf46a8ce71a3eaa09e7664d681fdcf3680f97a4483531661ddb5d721fddadc6193d6f31bbe86221b6a97554e8265",
          "sha256": "cdbe0c3af2d37cbbb47f9335d369718828214533187789f98a59955fb7c3c910",
          "sha1": "72d8e8590913f932975a89031b566681217d7673",
          "md5": "19f9f1b5abc941a8b1e7e260c520abed"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.5.8-javadoc.jar",
          "url": "projektor-common-3.5.8-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
