{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.test",
    "module": "gradle-plugin-moduleA",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-plugin-moduleA-0.1.0.jar",
          "url": "gradle-plugin-moduleA-0.1.0.jar",
          "size": 3893,
          "sha512": "d0dda9b4d3cc23ece0f020b989c459ab29a4bb8d90dbf5452678da66784d69a1608577e7f3a2a61c9af8c0a6ed30683bb98f680dd92e639b2756c083f6298351",
          "sha256": "8048c594236eaea45592eb5b244cefa9961b6abc5496f892f8e09a3bd1051916",
          "sha1": "de60316ca0a6d3269763560d13bc9b464861f877",
          "md5": "3b0d41fba2f0ed15eef790ea7ef748a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-moduleA-0.1.0.jar",
          "url": "gradle-plugin-moduleA-0.1.0.jar",
          "size": 3893,
          "sha512": "d0dda9b4d3cc23ece0f020b989c459ab29a4bb8d90dbf5452678da66784d69a1608577e7f3a2a61c9af8c0a6ed30683bb98f680dd92e639b2756c083f6298351",
          "sha256": "8048c594236eaea45592eb5b244cefa9961b6abc5496f892f8e09a3bd1051916",
          "sha1": "de60316ca0a6d3269763560d13bc9b464861f877",
          "md5": "3b0d41fba2f0ed15eef790ea7ef748a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-plugin-moduleA-0.1.0-sources.jar",
          "url": "gradle-plugin-moduleA-0.1.0-sources.jar",
          "size": 1461,
          "sha512": "4fa777e86467745176f21b604fa8aa0ad2392badd8e255306a6a1d373c39e16e904f59b9dc9e4e128b6d3468032146b00b2a9209a3eaeb52b0d563ce2af996ca",
          "sha256": "59f08904bf962b488395e553400766f6dfd7384242b81fb000178a5a8ce3097b",
          "sha1": "c5238dd2bd449fd11650fc9b8e6e9266bd88a414",
          "md5": "008bdfcf5b232627eece633da59873e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-plugin-moduleA-0.1.0-javadoc.jar",
          "url": "gradle-plugin-moduleA-0.1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-plugin-moduleA-0.1.0.jar",
          "url": "gradle-plugin-moduleA-0.1.0.jar",
          "size": 3893,
          "sha512": "d0dda9b4d3cc23ece0f020b989c459ab29a4bb8d90dbf5452678da66784d69a1608577e7f3a2a61c9af8c0a6ed30683bb98f680dd92e639b2756c083f6298351",
          "sha256": "8048c594236eaea45592eb5b244cefa9961b6abc5496f892f8e09a3bd1051916",
          "sha1": "de60316ca0a6d3269763560d13bc9b464861f877",
          "md5": "3b0d41fba2f0ed15eef790ea7ef748a1"
        }
      ]
    }
  ]
}
