{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.4.9.jar",
          "url": "projektor-common-3.4.9.jar",
          "size": 29345,
          "sha512": "bfae4da9413a34609ea44ec711b60cf30a5f7c5628b1f3491fd83a6d40abd245fbc671e71c7fb75379f1c52af990e2648c281ac6038bdf7608e76f32256f4775",
          "sha256": "98dbf50f8c0b5c0c7f58beb6262dc03575842dc00478b20ec16bf2ab8a07fbef",
          "sha1": "73f42459483b9b5ffebddfbac9bed2b0a75ae643",
          "md5": "64dc504d6d17772c990807d0a739db08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.4.9.jar",
          "url": "projektor-common-3.4.9.jar",
          "size": 29345,
          "sha512": "bfae4da9413a34609ea44ec711b60cf30a5f7c5628b1f3491fd83a6d40abd245fbc671e71c7fb75379f1c52af990e2648c281ac6038bdf7608e76f32256f4775",
          "sha256": "98dbf50f8c0b5c0c7f58beb6262dc03575842dc00478b20ec16bf2ab8a07fbef",
          "sha1": "73f42459483b9b5ffebddfbac9bed2b0a75ae643",
          "md5": "64dc504d6d17772c990807d0a739db08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.9-sources.jar",
          "url": "projektor-common-3.4.9-sources.jar",
          "size": 7568,
          "sha512": "07817ccd5c5ac4312479b18100e47e5c886285d86926ccc2dd7148b39d734535169a6dc82451993c1930f3119a5248aee6d648aa7d95cb69b3123770291c81ab",
          "sha256": "24a86a7bbe357b4bbbc2ec578007c0cba72683938a1135db479ddde174905d85",
          "sha1": "26b3938a447f38bb8029b04dad4ddce9c7829b7a",
          "md5": "de8dbf9455e64fc32ac276b200196bbd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.9-javadoc.jar",
          "url": "projektor-common-3.4.9-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
