{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.11.jar",
          "url": "projektor-settings-plugin-3.4.11.jar",
          "size": 42525,
          "sha512": "c704fda77bc7ff834cdb17b5548af334a09e519026207638bef76df8baa8fd08d71fd222cb2b0b669899dc65766d764c788e54dc904d0be71f29c8b2a60da45d",
          "sha256": "e0c47ecf62a3aec9821ade5701e0d82aa806210eadc566851399fbe3a2e50611",
          "sha1": "08c55d85f1f987e37008ff925cd0cf3c81a50a1d",
          "md5": "65ccfa0c03dc2a30f75fff9c0102b1d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.11.jar",
          "url": "projektor-settings-plugin-3.4.11.jar",
          "size": 42525,
          "sha512": "c704fda77bc7ff834cdb17b5548af334a09e519026207638bef76df8baa8fd08d71fd222cb2b0b669899dc65766d764c788e54dc904d0be71f29c8b2a60da45d",
          "sha256": "e0c47ecf62a3aec9821ade5701e0d82aa806210eadc566851399fbe3a2e50611",
          "sha1": "08c55d85f1f987e37008ff925cd0cf3c81a50a1d",
          "md5": "65ccfa0c03dc2a30f75fff9c0102b1d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.11-sources.jar",
          "url": "projektor-settings-plugin-3.4.11-sources.jar",
          "size": 8716,
          "sha512": "60eef08533419304e98113c577f14d03f6711d756f40e086df8d12302e342df09667c938f27a68093afcc9e4686b3960592b928a3cd48abc06e238a642fe8393",
          "sha256": "e79e93be15fb618a1e43c48ba050d88dd540f87cc295b00c5a630e5c9a762a08",
          "sha1": "96b284159f7b6801a360370ace4c6737ba1897fc",
          "md5": "50b7e9c22266deb81cd42e716e7bfe12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.11-javadoc.jar",
          "url": "projektor-settings-plugin-3.4.11-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
