{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "settings-plugin",
    "version": "3.5.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "settings-plugin-3.5.13.jar",
          "url": "settings-plugin-3.5.13.jar",
          "size": 49271,
          "sha512": "3542b7186ecf4bbef54fb478a4bf13c095730ffedf59679aa00f6861af602ad78a53208ff2c1a60fae727597e681965c01d3f83f3f89dcb17a1467e5cd4c3455",
          "sha256": "c54ffbcb68e8d31015fa9b10e6934044034fcc04c5762b959473e431fd2b651b",
          "sha1": "36c7e2b1647476ee4cf78bfd957ae3d1dd7d6d2a",
          "md5": "3a7cc9c8d00956c5f4930eca313251d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "settings-plugin-3.5.13.jar",
          "url": "settings-plugin-3.5.13.jar",
          "size": 49271,
          "sha512": "3542b7186ecf4bbef54fb478a4bf13c095730ffedf59679aa00f6861af602ad78a53208ff2c1a60fae727597e681965c01d3f83f3f89dcb17a1467e5cd4c3455",
          "sha256": "c54ffbcb68e8d31015fa9b10e6934044034fcc04c5762b959473e431fd2b651b",
          "sha1": "36c7e2b1647476ee4cf78bfd957ae3d1dd7d6d2a",
          "md5": "3a7cc9c8d00956c5f4930eca313251d8"
        }
      ]
    }
  ]
}
