{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "settings-plugin",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "settings-plugin-1.3.3.jar",
          "url": "settings-plugin-1.3.3.jar",
          "size": 22247,
          "sha512": "8c4467f6830f6e07c0fb771f2e2d304f05b4c02f0958b1fc0c11fc65b93a447281b48b495f782a05e7ea16533cc858743e4533a097a87c7970d2afad229b97e8",
          "sha256": "1ea106ab56c5f3165374a71ccd2edc6ff9c3bd9c00697fcbbff6ab4f4cdf0ca8",
          "sha1": "8ac09b231f0ff3f3befbd83aa82ed41c8ce2e30b",
          "md5": "dce5cd26b36d2fd7f0e74b101ac3322b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "settings-plugin-1.3.3.jar",
          "url": "settings-plugin-1.3.3.jar",
          "size": 22247,
          "sha512": "8c4467f6830f6e07c0fb771f2e2d304f05b4c02f0958b1fc0c11fc65b93a447281b48b495f782a05e7ea16533cc858743e4533a097a87c7970d2afad229b97e8",
          "sha256": "1ea106ab56c5f3165374a71ccd2edc6ff9c3bd9c00697fcbbff6ab4f4cdf0ca8",
          "sha1": "8ac09b231f0ff3f3befbd83aa82ed41c8ce2e30b",
          "md5": "dce5cd26b36d2fd7f0e74b101ac3322b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "settings-plugin-1.3.3-sources.jar",
          "url": "settings-plugin-1.3.3-sources.jar",
          "size": 4166,
          "sha512": "8d0788943aab4a3f5e36bc46fc076f0df982fed0e413486d482a356fab5277808a9f2f47f11eec1ab17f6d90bf706db4db71e2f6847c4dea339538a100a5fca4",
          "sha256": "33a6e77772dee3804bf7d99112701c5a90745296d15dbf8fa7f67ff8fd4ad8c7",
          "sha1": "f6b4c31f14f182dfcd768a4ea0f906346965d631",
          "md5": "39827bfba0ca4ffbc0100763166686e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "settings-plugin-1.3.3-javadoc.jar",
          "url": "settings-plugin-1.3.3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
