{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.6.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.10.jar",
          "url": "projektor-project-plugin-4.6.10.jar",
          "size": 1018519,
          "sha512": "e2a73c5e58b79ec89494f3e8a0e3eaaf0d9bad4893241cb03038b6fe56b1b76023647cea1de4662dcbcac26e7dedd3e4f955dd6a1337d0ae201aa9cc1ffc90d4",
          "sha256": "c3d5fb457294f53534963ba5dd77ce92e8258b04ed1f821ad6b463ecf996a2d4",
          "sha1": "838f51808ddb6e3071f63088cb928bb6e65cbd4f",
          "md5": "89887cc72fe6fadf270b40498d3a846d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "com.modrinth.minotaur.gradle.plugin",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.parchmentmc.librarian.forgegradle",
          "module": "org.parchmentmc.librarian.forgegradle.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "fabric-loom",
          "module": "fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.6.10.jar",
          "url": "projektor-project-plugin-4.6.10.jar",
          "size": 1018519,
          "sha512": "e2a73c5e58b79ec89494f3e8a0e3eaaf0d9bad4893241cb03038b6fe56b1b76023647cea1de4662dcbcac26e7dedd3e4f955dd6a1337d0ae201aa9cc1ffc90d4",
          "sha256": "c3d5fb457294f53534963ba5dd77ce92e8258b04ed1f821ad6b463ecf996a2d4",
          "sha1": "838f51808ddb6e3071f63088cb928bb6e65cbd4f",
          "md5": "89887cc72fe6fadf270b40498d3a846d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.10-sources.jar",
          "url": "projektor-project-plugin-4.6.10-sources.jar",
          "size": 92353,
          "sha512": "def0223056989ca2aa2f3c1f0fc5ab9a86ecef5a84d2062348b489edfc9a94ab3dc4fad3898a4926279f3dd855f01e975c1be91856d4c81d5e011f3e2488f02a",
          "sha256": "e664e690309cc878c7991d3f50da20b360c895b2d2868e94c7e3115e04a16362",
          "sha1": "b3f747116c64d48318b747ff478b07e1087d1ce6",
          "md5": "d629adc25ab11b591ef3785401da138a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.10-javadoc.jar",
          "url": "projektor-project-plugin-4.6.10-javadoc.jar",
          "size": 261,
          "sha512": "3d9db37631673d69cd372dac8019fd1d67fe840f536cfa217f3d3962fdca0c22b2fd5677cb0d4699a215d170fc6f64e2795a2d556488382a8af359946c82c72e",
          "sha256": "a000a8056f88061229dbed874f667302cb631be8b7bcaf8b06869a9c063ecf7b",
          "sha1": "3c7f80b4d5f3db1c2c1dc019b25fa8c329e74e13",
          "md5": "e8e810361d48060d93c8cc0631043d00"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.10.jar",
          "url": "projektor-project-plugin-4.6.10.jar",
          "size": 1018519,
          "sha512": "e2a73c5e58b79ec89494f3e8a0e3eaaf0d9bad4893241cb03038b6fe56b1b76023647cea1de4662dcbcac26e7dedd3e4f955dd6a1337d0ae201aa9cc1ffc90d4",
          "sha256": "c3d5fb457294f53534963ba5dd77ce92e8258b04ed1f821ad6b463ecf996a2d4",
          "sha1": "838f51808ddb6e3071f63088cb928bb6e65cbd4f",
          "md5": "89887cc72fe6fadf270b40498d3a846d"
        }
      ]
    }
  ]
}
