{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.6.6.jar",
          "url": "projektor-common-3.6.6.jar",
          "size": 33927,
          "sha512": "36b5f3423502d16dd3bf018be85395c708cdf64aadd2d97fe56f3ea1d39620f2f035f5e6a00ccad89e01a64e3beeb898125f0c4a415ada758d35841a03d059d7",
          "sha256": "30984aae8d7e24a34d83b5090b9ec4e99b069ba0c388d0dd6f3555dd776a7708",
          "sha1": "3f95c769c5226ccc7ed1f8c13cc1b6ae3ed29341",
          "md5": "dc5508b5c75233a0e11ba20cd4981670"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.6.6.jar",
          "url": "projektor-common-3.6.6.jar",
          "size": 33927,
          "sha512": "36b5f3423502d16dd3bf018be85395c708cdf64aadd2d97fe56f3ea1d39620f2f035f5e6a00ccad89e01a64e3beeb898125f0c4a415ada758d35841a03d059d7",
          "sha256": "30984aae8d7e24a34d83b5090b9ec4e99b069ba0c388d0dd6f3555dd776a7708",
          "sha1": "3f95c769c5226ccc7ed1f8c13cc1b6ae3ed29341",
          "md5": "dc5508b5c75233a0e11ba20cd4981670"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.6-sources.jar",
          "url": "projektor-common-3.6.6-sources.jar",
          "size": 9313,
          "sha512": "cc1b1b6265cdb8a93fd80826e4909e5bd5a4f9c95def95f8314d040bec0836dba95383bbb07cc017f1d69e376553fdd2b7ed18c206a482dadd77586b908857e7",
          "sha256": "d891366dd90b9bdc1001f89d0abad0518f7ca1dcfa485a46dab9cf3b80f24586",
          "sha1": "92765217d25387d8c472d0ec18f2c1daf33d9a1b",
          "md5": "f4845d49e5e5a181b7b87618eeebeb83"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.6-javadoc.jar",
          "url": "projektor-common-3.6.6-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
