{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.8.jar",
          "url": "projektor-settings-plugin-4.6.8.jar",
          "size": 364069,
          "sha512": "016fecd110a59d7c141996e21c6541c2173781ed615df89e91ef6d3829bc661ecadf4158324ae96bdeb51860b2807e9486f1d29708c26643b4c26ee725e074d5",
          "sha256": "042b87216d3dd8730aaf406b15a5ebf9662aeebeed998084ffc4715d127f4d45",
          "sha1": "e52be7d288fcde6532fa3834dec63cd4f7b225dd",
          "md5": "80e734d7286e27c76594c539b131b26a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.8.jar",
          "url": "projektor-settings-plugin-4.6.8.jar",
          "size": 364069,
          "sha512": "016fecd110a59d7c141996e21c6541c2173781ed615df89e91ef6d3829bc661ecadf4158324ae96bdeb51860b2807e9486f1d29708c26643b4c26ee725e074d5",
          "sha256": "042b87216d3dd8730aaf406b15a5ebf9662aeebeed998084ffc4715d127f4d45",
          "sha1": "e52be7d288fcde6532fa3834dec63cd4f7b225dd",
          "md5": "80e734d7286e27c76594c539b131b26a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.8-sources.jar",
          "url": "projektor-settings-plugin-4.6.8-sources.jar",
          "size": 11982,
          "sha512": "a6d79cfa9cbbc2c4b04983c0e3591520f0885295a8b7544df60a815116c10520561250de9197da6da8a3991301a26b888f16faf7c170eee6ddc88e134f46baec",
          "sha256": "7a60979af73673b449f1c5bcb89848bf53af189765885736ab22667324c087a4",
          "sha1": "451d28d25739973315f89e8e8f5c30de7411264e",
          "md5": "c9d4ae420e8a2683084e8970265cb190"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.8-javadoc.jar",
          "url": "projektor-settings-plugin-4.6.8-javadoc.jar",
          "size": 261,
          "sha512": "c35a3bbca9a058d6410463d46f50edda1296b9b82c37921f332356038205bf9f62d44e909747ad1f75e11bcb185f670cb15fb38d90f9361b9b3c9bff5ac7f122",
          "sha256": "91d86b2ca2c90e24f0904ef9bd3fa00e84c64da665e75e269040fa35568d0593",
          "sha1": "0b0aa4a64c1ace77536dc071c4a562a34dfd9a15",
          "md5": "dbc258b22134dc9a191fe6e32dfdb017"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.8.jar",
          "url": "projektor-settings-plugin-4.6.8.jar",
          "size": 364069,
          "sha512": "016fecd110a59d7c141996e21c6541c2173781ed615df89e91ef6d3829bc661ecadf4158324ae96bdeb51860b2807e9486f1d29708c26643b4c26ee725e074d5",
          "sha256": "042b87216d3dd8730aaf406b15a5ebf9662aeebeed998084ffc4715d127f4d45",
          "sha1": "e52be7d288fcde6532fa3834dec63cd4f7b225dd",
          "md5": "80e734d7286e27c76594c539b131b26a"
        }
      ]
    }
  ]
}
