{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.3.0.jar",
          "url": "projektor-settings-plugin-4.3.0.jar",
          "size": 272490,
          "sha512": "feac75e62d696a2ecd09f234d66a4a874ce8643c02727b15a662f37f1fde9b931517b8499a86088a8840b3acff518c38e2460c2f424660d4abfb74b178c57f42",
          "sha256": "3ba6a1a3c33fe0c4b5c73623b2d3e4440eff16d834537cf3bf878b4b8ee8c32c",
          "sha1": "3ad6b239316105e07bcaaeee584ceab6172ea859",
          "md5": "e6c75be2d1e4d49cd93e8a615c53a63f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.3.0.jar",
          "url": "projektor-settings-plugin-4.3.0.jar",
          "size": 272490,
          "sha512": "feac75e62d696a2ecd09f234d66a4a874ce8643c02727b15a662f37f1fde9b931517b8499a86088a8840b3acff518c38e2460c2f424660d4abfb74b178c57f42",
          "sha256": "3ba6a1a3c33fe0c4b5c73623b2d3e4440eff16d834537cf3bf878b4b8ee8c32c",
          "sha1": "3ad6b239316105e07bcaaeee584ceab6172ea859",
          "md5": "e6c75be2d1e4d49cd93e8a615c53a63f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.3.0-sources.jar",
          "url": "projektor-settings-plugin-4.3.0-sources.jar",
          "size": 11151,
          "sha512": "de065719e63246cf349367d32984d43268560680f8b33efd66d39253ccef78f64d2d8c64307f93bba9c17089750ccdb8fbea69e820f782806690e90d77321883",
          "sha256": "6dbddad9836d909dc1306ce60abe27f07d0514195c3d15f6ce8a78b6d2bb3aa5",
          "sha1": "00fc8327ee8c76b14bc01b8d99655e06ee08f23a",
          "md5": "2f8fc46c3547c431e7008f54bb7545b2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.3.0-javadoc.jar",
          "url": "projektor-settings-plugin-4.3.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.3.0.jar",
          "url": "projektor-settings-plugin-4.3.0.jar",
          "size": 272490,
          "sha512": "feac75e62d696a2ecd09f234d66a4a874ce8643c02727b15a662f37f1fde9b931517b8499a86088a8840b3acff518c38e2460c2f424660d4abfb74b178c57f42",
          "sha256": "3ba6a1a3c33fe0c4b5c73623b2d3e4440eff16d834537cf3bf878b4b8ee8c32c",
          "sha1": "3ad6b239316105e07bcaaeee584ceab6172ea859",
          "md5": "e6c75be2d1e4d49cd93e8a615c53a63f"
        }
      ]
    }
  ]
}
