{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.7.jar",
          "url": "projektor-settings-plugin-4.6.7.jar",
          "size": 337446,
          "sha512": "c3c23bf893c1eef751ee8b6d4199c21d122beffbc44e3a1216e7a6d171e6f84bf3820ffca8684c35dbf30b1f808068f3e2b43eda0706b8710f59e0aed901bb2f",
          "sha256": "ba30324730fa72373f1fc42b584937e85034efe013592500faff0c90ff44ca6f",
          "sha1": "f09c6c5216d6055d3d82ef30e97ce139802f08f5",
          "md5": "e3dc6f2c9bd4fad0a128e4d1d3c1d209"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.7.jar",
          "url": "projektor-settings-plugin-4.6.7.jar",
          "size": 337446,
          "sha512": "c3c23bf893c1eef751ee8b6d4199c21d122beffbc44e3a1216e7a6d171e6f84bf3820ffca8684c35dbf30b1f808068f3e2b43eda0706b8710f59e0aed901bb2f",
          "sha256": "ba30324730fa72373f1fc42b584937e85034efe013592500faff0c90ff44ca6f",
          "sha1": "f09c6c5216d6055d3d82ef30e97ce139802f08f5",
          "md5": "e3dc6f2c9bd4fad0a128e4d1d3c1d209"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.7-sources.jar",
          "url": "projektor-settings-plugin-4.6.7-sources.jar",
          "size": 11982,
          "sha512": "e1db5586ab69813355bf611bea4498100d8025b04ff98d2274f5e6bd4c8627202476bbc513af02873b2dcc5aa1e93831669fc5dc16e5d36f0b289beaed6276aa",
          "sha256": "005b393146404ee33d3b31b145715f28c75684f3980e7d19464d3c45e58cf60b",
          "sha1": "901efa950b6223d7ecf258698cc0f795988d7a98",
          "md5": "d335e9b293c297be8ef7b3e5983e1d92"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.7-javadoc.jar",
          "url": "projektor-settings-plugin-4.6.7-javadoc.jar",
          "size": 261,
          "sha512": "72c1b9c51ed806f2a759600ca2ab79b5bdead909d7dcc679cbecf78142478d48ba69d35d8da098f6300a9530d24e77153cc996e376a3840fb995996ac3cf2696",
          "sha256": "13fb5d27017c557ed5b095d54b2edb8171787189dc02cc04fa3671649d32574d",
          "sha1": "1b624a338ec25511cf7cb8f9b31f4f42b10ca9e7",
          "md5": "519f393591b82cd9b2d407eef3fcbb3a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.7.jar",
          "url": "projektor-settings-plugin-4.6.7.jar",
          "size": 337446,
          "sha512": "c3c23bf893c1eef751ee8b6d4199c21d122beffbc44e3a1216e7a6d171e6f84bf3820ffca8684c35dbf30b1f808068f3e2b43eda0706b8710f59e0aed901bb2f",
          "sha256": "ba30324730fa72373f1fc42b584937e85034efe013592500faff0c90ff44ca6f",
          "sha1": "f09c6c5216d6055d3d82ef30e97ce139802f08f5",
          "md5": "e3dc6f2c9bd4fad0a128e4d1d3c1d209"
        }
      ]
    }
  ]
}
