{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.5.jar",
          "url": "projektor-settings-plugin-3.6.5.jar",
          "size": 50928,
          "sha512": "8b61c90efabbcca0890b585a95ac302163bd47c6cbd8dbbddfe631a99803c4a30d96beedb6b7228bfbe297359a0c449a7cd88f76a4be58587541771910d7c332",
          "sha256": "eed6961b2b628add9ae993be37177546dc59ea4ff20ddc7a6c925327d16f7242",
          "sha1": "21a9b188d49321ff5ccd8a182d41fb21ac3fd752",
          "md5": "349c1d0c149da0ab934a4148a7d21a0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.5.jar",
          "url": "projektor-settings-plugin-3.6.5.jar",
          "size": 50928,
          "sha512": "8b61c90efabbcca0890b585a95ac302163bd47c6cbd8dbbddfe631a99803c4a30d96beedb6b7228bfbe297359a0c449a7cd88f76a4be58587541771910d7c332",
          "sha256": "eed6961b2b628add9ae993be37177546dc59ea4ff20ddc7a6c925327d16f7242",
          "sha1": "21a9b188d49321ff5ccd8a182d41fb21ac3fd752",
          "md5": "349c1d0c149da0ab934a4148a7d21a0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.5-sources.jar",
          "url": "projektor-settings-plugin-3.6.5-sources.jar",
          "size": 10853,
          "sha512": "1af01483b82a1bfbbb944b2492f9d8a05800fd7c2f40c46ca6009b37e1c5a334e828b0327ddc20bc67da6e2d77969e0c27622d99176f68eefeb14b0f82729834",
          "sha256": "1dfd79ca030e65c73c89b618ce616c91d7b6abf7c02728078bae3c27d11d9f38",
          "sha1": "2ed0da58dc54a0a3157cf6f86319e1ab47312254",
          "md5": "25ed29e96b286a907bc6fe02b413836b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.5-javadoc.jar",
          "url": "projektor-settings-plugin-3.6.5-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
