{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "settings-plugin",
    "version": "7.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "settings-plugin-7.0.0.jar",
          "url": "settings-plugin-7.0.0.jar",
          "size": 100175,
          "sha512": "2937c8672312eb0f46f5026f819f0b7c3e18db19236e27ae95e12436e6f651cd2d35c10a22f78a354c7942a04dd1bb6867cc60fc1944c555d1e3b3923ae6c747",
          "sha256": "7a31fe631db0762389d4c7805efe0caa57e03fe7aaa9de1ac5638bc96ad7e528",
          "sha1": "da2f06beaddae29c8b3dcdba1fce0f434b1f5d78",
          "md5": "84856f8970286a2d9df63635b0fe2535"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.4.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "settings-plugin-7.0.0.jar",
          "url": "settings-plugin-7.0.0.jar",
          "size": 100175,
          "sha512": "2937c8672312eb0f46f5026f819f0b7c3e18db19236e27ae95e12436e6f651cd2d35c10a22f78a354c7942a04dd1bb6867cc60fc1944c555d1e3b3923ae6c747",
          "sha256": "7a31fe631db0762389d4c7805efe0caa57e03fe7aaa9de1ac5638bc96ad7e528",
          "sha1": "da2f06beaddae29c8b3dcdba1fce0f434b1f5d78",
          "md5": "84856f8970286a2d9df63635b0fe2535"
        }
      ]
    }
  ]
}
