{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.1.jar",
          "url": "projektor-settings-plugin-3.6.1.jar",
          "size": 52919,
          "sha512": "a7205588c2d347f4c4ca5be254759ca2590554186690c5e8d9cf4243fde48a381b40afe8e428b40df5b12a2377051dc53156aec4517723e2c7dd7dae52d7239a",
          "sha256": "6ac16c1f8cfeac1d684ae53b5c4a98b3e652b7f248288bb944edc846d3f6d825",
          "sha1": "e9856bb0e2f686ed8ffc81f6c36caf034f39624c",
          "md5": "fbfd46d10e23b0598bb46a558c3d570b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.1.jar",
          "url": "projektor-settings-plugin-3.6.1.jar",
          "size": 52919,
          "sha512": "a7205588c2d347f4c4ca5be254759ca2590554186690c5e8d9cf4243fde48a381b40afe8e428b40df5b12a2377051dc53156aec4517723e2c7dd7dae52d7239a",
          "sha256": "6ac16c1f8cfeac1d684ae53b5c4a98b3e652b7f248288bb944edc846d3f6d825",
          "sha1": "e9856bb0e2f686ed8ffc81f6c36caf034f39624c",
          "md5": "fbfd46d10e23b0598bb46a558c3d570b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.1-sources.jar",
          "url": "projektor-settings-plugin-3.6.1-sources.jar",
          "size": 11207,
          "sha512": "292d3aa9473dc0be0fd8685e7bb5d308c6ac107a5ac5c8f21cc92cecc5e8a5505946f803c1df5022e396ad7c6521a78dbf8999cf816917cc8ae02dafa25b0c96",
          "sha256": "d5857fcd51accebbd9b6bd2101012998a42ef62ab629bb0f43b64a840c15910b",
          "sha1": "09019f6fd84cf875084fdbd8f8c233f6b7411464",
          "md5": "6f22cd01484d2e999074aa369cfeca65"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.1-javadoc.jar",
          "url": "projektor-settings-plugin-3.6.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
