{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "5.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-5.0.2.jar",
          "url": "project-plugin-5.0.2.jar",
          "size": 293392,
          "sha512": "a264840686bac3dd2241995ad86a19f42a8750129861a96f46f9cc55372ccafaf93ae26cc0df4df776f69f3adde79b46ae866b60eb74c8cf52327c35a2961978",
          "sha256": "dab838b1db330769766e300f40802b5bc37e70b77dce9f00093a97777e6672ee",
          "sha1": "c9ac6e2b5f1af45a9588bd333e98c326fa48fc9c",
          "md5": "7d1a6857b68e3a0430f6cab6e579c221"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.7"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-5.0.2.jar",
          "url": "project-plugin-5.0.2.jar",
          "size": 293392,
          "sha512": "a264840686bac3dd2241995ad86a19f42a8750129861a96f46f9cc55372ccafaf93ae26cc0df4df776f69f3adde79b46ae866b60eb74c8cf52327c35a2961978",
          "sha256": "dab838b1db330769766e300f40802b5bc37e70b77dce9f00093a97777e6672ee",
          "sha1": "c9ac6e2b5f1af45a9588bd333e98c326fa48fc9c",
          "md5": "7d1a6857b68e3a0430f6cab6e579c221"
        }
      ]
    }
  ]
}
