{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gradle",
    "module": "github-pages-moduleA",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "github-pages-moduleA-0.1.0.jar",
          "url": "github-pages-moduleA-0.1.0.jar",
          "size": 2156,
          "sha512": "2f1098ce72d96119f6aac8e372065751bd552e0db855fe63e3e2007b7dc7af1bbf6cd0badaf49da24767452f50f60201121ed4ce63869e27cd3e17fc7da05051",
          "sha256": "0fe695189f736f0f84cda12a7b80742875fbb92399c498babeb124f9bf73229b",
          "sha1": "3b22654bf734ad34d11acf9cea30e690646e6c2e",
          "md5": "56e19c535b64ce4d2cf01992c4721c84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "github-pages-moduleA-0.1.0.jar",
          "url": "github-pages-moduleA-0.1.0.jar",
          "size": 2156,
          "sha512": "2f1098ce72d96119f6aac8e372065751bd552e0db855fe63e3e2007b7dc7af1bbf6cd0badaf49da24767452f50f60201121ed4ce63869e27cd3e17fc7da05051",
          "sha256": "0fe695189f736f0f84cda12a7b80742875fbb92399c498babeb124f9bf73229b",
          "sha1": "3b22654bf734ad34d11acf9cea30e690646e6c2e",
          "md5": "56e19c535b64ce4d2cf01992c4721c84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "github-pages-moduleA-0.1.0-sources.jar",
          "url": "github-pages-moduleA-0.1.0-sources.jar",
          "size": 1137,
          "sha512": "8da3ce526b81cf3b184e08720076ddd5a5392b4cff94b1dcc9603ea4f793430edb2aafa5211c972c15f3d377e346a1c53d6e304f57efa20d50d6ae4755fd544e",
          "sha256": "0ea8be8e0173835566f035acd62e36734ee93a1bcd6eebc4f74cf26b665f1233",
          "sha1": "d8496da41c3b4c9715ed219346cc3cb844643cf2",
          "md5": "d1fcd49256516a47658d88692b85d699"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "github-pages-moduleA-0.1.0-javadoc.jar",
          "url": "github-pages-moduleA-0.1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
