{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.1.jar",
          "url": "projektor-project-plugin-4.2.1.jar",
          "size": 640417,
          "sha512": "d14bef82fd2cf4d0d829b9e957ceca32c14bf7bbbd50bd945ba1f2c1ff5f18526dc1e4605020dc4fde0d658076545e011424acee99332849974412b6bb371641",
          "sha256": "62eb42cfa22de54bb6de4bf4cdadf7941403aa95d718687eef7603ede666ea13",
          "sha1": "7816f49d9e46920baf855e8a6d528e87e5d4a69c",
          "md5": "f4a1f5cf48492dd622a3a5e5f1320686"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.2.1.jar",
          "url": "projektor-project-plugin-4.2.1.jar",
          "size": 640417,
          "sha512": "d14bef82fd2cf4d0d829b9e957ceca32c14bf7bbbd50bd945ba1f2c1ff5f18526dc1e4605020dc4fde0d658076545e011424acee99332849974412b6bb371641",
          "sha256": "62eb42cfa22de54bb6de4bf4cdadf7941403aa95d718687eef7603ede666ea13",
          "sha1": "7816f49d9e46920baf855e8a6d528e87e5d4a69c",
          "md5": "f4a1f5cf48492dd622a3a5e5f1320686"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.1-sources.jar",
          "url": "projektor-project-plugin-4.2.1-sources.jar",
          "size": 69669,
          "sha512": "8bac5489202a386860f22818c9ebb5e9073f52ac05a2eec9babeb7c4e92c43124fc87b65e974e942c4fb63e3431c30abbd921a0e9bfd4107e01f95ad0c6a57cb",
          "sha256": "d96d59cd4c02394e9bb0e0a60bb97e9452f61046d30ee8895e0ed33f701701e0",
          "sha1": "67b3bc4a4df1223bbf1ec428cebb5a8bb72b5f4e",
          "md5": "df5316094622404d448bf1254d608c88"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.1-javadoc.jar",
          "url": "projektor-project-plugin-4.2.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.1.jar",
          "url": "projektor-project-plugin-4.2.1.jar",
          "size": 640417,
          "sha512": "d14bef82fd2cf4d0d829b9e957ceca32c14bf7bbbd50bd945ba1f2c1ff5f18526dc1e4605020dc4fde0d658076545e011424acee99332849974412b6bb371641",
          "sha256": "62eb42cfa22de54bb6de4bf4cdadf7941403aa95d718687eef7603ede666ea13",
          "sha1": "7816f49d9e46920baf855e8a6d528e87e5d4a69c",
          "md5": "f4a1f5cf48492dd622a3a5e5f1320686"
        }
      ]
    }
  ]
}
