{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.0.jar",
          "url": "projektor-project-plugin-4.2.0.jar",
          "size": 640466,
          "sha512": "a4f4285646845b2be319d81871451706f557817863f1178b3f059c5ae7175f5a334594a4ede9508f17efda16ed087e673bb86ffec733d2fcda107d3aa6ad2813",
          "sha256": "81976dd0dd408d84a231d383bcd90dcb53c9786417b25d09a42b68b9bb4add0e",
          "sha1": "e4abc1abae38ef35912f5bb919ddbd4eb6096769",
          "md5": "180558490abd0ff8c093a942be82df2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.2.0.jar",
          "url": "projektor-project-plugin-4.2.0.jar",
          "size": 640466,
          "sha512": "a4f4285646845b2be319d81871451706f557817863f1178b3f059c5ae7175f5a334594a4ede9508f17efda16ed087e673bb86ffec733d2fcda107d3aa6ad2813",
          "sha256": "81976dd0dd408d84a231d383bcd90dcb53c9786417b25d09a42b68b9bb4add0e",
          "sha1": "e4abc1abae38ef35912f5bb919ddbd4eb6096769",
          "md5": "180558490abd0ff8c093a942be82df2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.0-sources.jar",
          "url": "projektor-project-plugin-4.2.0-sources.jar",
          "size": 69671,
          "sha512": "046ac66f2260f1c396a79d5e4cee7e976137826d04183328fa9adaeef46a90e3f0d5664ba14bed04c7004a9502dd867f5b617815a3340301735b5e7be44be1d6",
          "sha256": "cbc95d33aefd182935e6ebefd5043960b61d1fd8585eec2b8e61accd38f28766",
          "sha1": "a87788bfc3632efd1892f5d9a3d35de1bbbb83e6",
          "md5": "2baa60f5c452d2a9fddb873a43fccb13"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.0-javadoc.jar",
          "url": "projektor-project-plugin-4.2.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.0.jar",
          "url": "projektor-project-plugin-4.2.0.jar",
          "size": 640466,
          "sha512": "a4f4285646845b2be319d81871451706f557817863f1178b3f059c5ae7175f5a334594a4ede9508f17efda16ed087e673bb86ffec733d2fcda107d3aa6ad2813",
          "sha256": "81976dd0dd408d84a231d383bcd90dcb53c9786417b25d09a42b68b9bb4add0e",
          "sha1": "e4abc1abae38ef35912f5bb919ddbd4eb6096769",
          "md5": "180558490abd0ff8c093a942be82df2e"
        }
      ]
    }
  ]
}
