{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.4.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.12.jar",
          "url": "projektor-settings-plugin-3.4.12.jar",
          "size": 41911,
          "sha512": "b2093b2b01d00efb901e2f8a172e1c1031f912e1d99ab16c03957d40cca62f8aa40b225b7ea0db5a42f21d9f1df2427c8cda1dd113220d43f533f78391da37fe",
          "sha256": "9ef5a7b47dfe35966fa0f5ab3fac7f86196b0ff6886b6e09f92aea6419107889",
          "sha1": "6d42942231e9d9af3e6491013ff3ec71b1a5588b",
          "md5": "703d9a43390225306812807a093ee4b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.12.jar",
          "url": "projektor-settings-plugin-3.4.12.jar",
          "size": 41911,
          "sha512": "b2093b2b01d00efb901e2f8a172e1c1031f912e1d99ab16c03957d40cca62f8aa40b225b7ea0db5a42f21d9f1df2427c8cda1dd113220d43f533f78391da37fe",
          "sha256": "9ef5a7b47dfe35966fa0f5ab3fac7f86196b0ff6886b6e09f92aea6419107889",
          "sha1": "6d42942231e9d9af3e6491013ff3ec71b1a5588b",
          "md5": "703d9a43390225306812807a093ee4b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.12-sources.jar",
          "url": "projektor-settings-plugin-3.4.12-sources.jar",
          "size": 8911,
          "sha512": "71296e25f13e1c49c4e84a832ccb376be3c1d46aaeda93505317cb633ddde9a2e500ce3bfb663da7575d82ffcc904607c3be0c1098a0ee35df654e006b309546",
          "sha256": "b9c3bbfbe3bd818dd691a239aa106d16a1c8029f42ade2fb1aabb521837a5a1d",
          "sha1": "2efbf18b71611e8d8903b942ebb85511c1ae589d",
          "md5": "4dd59f18a82d9946efd04bdad686d488"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.12-javadoc.jar",
          "url": "projektor-settings-plugin-3.4.12-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
