[versions]
foojay-resolver-plugin = "1.0.0"
plugin-publish-plugin = "2.1.1"

kotlin = "2.4.0"
kotlin-serialization-json = "1.11.0"
kotlin-html = "0.12.0"
ktor = "3.5.2"

snake-yaml = "2.6"
poetesse = "0.1.0"

[libraries]
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "kotlin-serialization-json" }
kotlin-html = { group = "org.jetbrains.kotlinx", name = "kotlinx-html-jvm", version.ref = "kotlin-html" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
snake-yaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snake-yaml" }
poetesse = { group = "io.github.diskria", name = "poetesse", version.ref = "poetesse" }

foojay-resolver-plugin = { group = "org.gradle.toolchains.foojay-resolver-convention", name = "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin", version.ref = "foojay-resolver-plugin" }
kotlin-jvm-plugin = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { group = "org.jetbrains.kotlin.plugin.serialization", name = "org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
plugin-publish-plugin = { group = "com.gradle.publish", name = "plugin-publish-plugin", version.ref = "plugin-publish-plugin" }

[bundles]
ktor-client = [
    "ktor-client-core",
    "ktor-client-cio",
]
implementation-settings-plugins = [
    "foojay-resolver-plugin",
]
implementation-project-plugins = [
    "kotlin-jvm-plugin",
    "kotlin-serialization-plugin",
    "plugin-publish-plugin",
]
