{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.4.jar",
          "url": "projektor-settings-plugin-3.5.4.jar",
          "size": 49976,
          "sha512": "352123e9ac226be64bc97b91b7a04bb198310c268570194032adb95ea17b19a180f6010717d75f95d37d550c3bef77cb55017f756a874ed9b8543aebdd3b2e1b",
          "sha256": "a9770e30b4e30f9217074ea138e08eeaa98122b4538ce729a500ab2a59fa9faa",
          "sha1": "4af365fd4e4c5c6ad829dad1512f47858cd1c8e0",
          "md5": "7b4d26003989a18182e0031edfd16933"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.4.jar",
          "url": "projektor-settings-plugin-3.5.4.jar",
          "size": 49976,
          "sha512": "352123e9ac226be64bc97b91b7a04bb198310c268570194032adb95ea17b19a180f6010717d75f95d37d550c3bef77cb55017f756a874ed9b8543aebdd3b2e1b",
          "sha256": "a9770e30b4e30f9217074ea138e08eeaa98122b4538ce729a500ab2a59fa9faa",
          "sha1": "4af365fd4e4c5c6ad829dad1512f47858cd1c8e0",
          "md5": "7b4d26003989a18182e0031edfd16933"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.4-sources.jar",
          "url": "projektor-settings-plugin-3.5.4-sources.jar",
          "size": 10687,
          "sha512": "4e6183d11bb4f613d3a3d11c2ea2e3680a82a1de73e106b73e1ae441281a441fb13ef264be5ecda0037b7ec09b952a44a3e74eaecaa7a50c12be962359796cd1",
          "sha256": "5eed0540817dac9d567463d2aad9fa33a80280aa76649d3b316588027e611fd5",
          "sha1": "1dfe472e3e86939249c6bc6d94d3ec5e0a391ecb",
          "md5": "7823688722f12f6f969edee14ff09417"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.4-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
