{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.20.jar",
          "url": "projektor-settings-plugin-3.5.20.jar",
          "size": 49278,
          "sha512": "7f570f88e7b9c5f0e4d50de20981a4eecd0706c53bb6e58a7f0bf7b386d5303a885de9db2a1fa1f53967087a622c1863c7947c8dcef8958833859f92c5c907eb",
          "sha256": "d7c3cdc576f5eea32b2b32c43286b670237a2848210de861b0075ffec8467d2b",
          "sha1": "87df7a6ce644288f252dff013e121cf2ecc410db",
          "md5": "aba8bfef56abd488bbdaec4f9c43743e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.20.jar",
          "url": "projektor-settings-plugin-3.5.20.jar",
          "size": 49278,
          "sha512": "7f570f88e7b9c5f0e4d50de20981a4eecd0706c53bb6e58a7f0bf7b386d5303a885de9db2a1fa1f53967087a622c1863c7947c8dcef8958833859f92c5c907eb",
          "sha256": "d7c3cdc576f5eea32b2b32c43286b670237a2848210de861b0075ffec8467d2b",
          "sha1": "87df7a6ce644288f252dff013e121cf2ecc410db",
          "md5": "aba8bfef56abd488bbdaec4f9c43743e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.20-sources.jar",
          "url": "projektor-settings-plugin-3.5.20-sources.jar",
          "size": 10401,
          "sha512": "b6817a683b54dbaf05ddd8797717bdbbe821abd8d7931eb049dc90c1388687d77d962d2c7af3340e1dc24a5e2291d8a1775131f98bc0957eab9d2a7c2fb1ab2d",
          "sha256": "b0cdecb11026a8f72fbb547815c432fd74a0e2a93c539511a4f044d5976cbc30",
          "sha1": "ca2dc705650772cd83f2a26dce680e6c8ba12c0b",
          "md5": "e4134f00f53203d0e3c0d8ba7b738434"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.20-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.20-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
