{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.6.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.6.10.jar",
          "url": "projektor-common-3.6.10.jar",
          "size": 33942,
          "sha512": "5ee1b2b55cc423f15e6d97d3ddf697e1aae5393312a43de310bb76daccae9adc48d421735d5ca54b6527a0695f9f1684446abb6c0969f08b48c55829abb27025",
          "sha256": "f24c25061b8172957d969b642e27e99cfc3223e2c76807bc45e63ca5de52b7e7",
          "sha1": "37a692d3a0b54a531c45537c113eab0a3a14448f",
          "md5": "44d48e73b40fdb4228728c41296f7c2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.6.10.jar",
          "url": "projektor-common-3.6.10.jar",
          "size": 33942,
          "sha512": "5ee1b2b55cc423f15e6d97d3ddf697e1aae5393312a43de310bb76daccae9adc48d421735d5ca54b6527a0695f9f1684446abb6c0969f08b48c55829abb27025",
          "sha256": "f24c25061b8172957d969b642e27e99cfc3223e2c76807bc45e63ca5de52b7e7",
          "sha1": "37a692d3a0b54a531c45537c113eab0a3a14448f",
          "md5": "44d48e73b40fdb4228728c41296f7c2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.10-sources.jar",
          "url": "projektor-common-3.6.10-sources.jar",
          "size": 9316,
          "sha512": "6e3aabe35139c15b152d87cb4bdb0ee7a15f6a2598bed607b8aa78b5c565f642553dfc862d31b38b6ab6fdb7a88d02a1add1b7fa70fea8b96973f6f8990cfc07",
          "sha256": "5f9fe4df62c65246af411a29f4ab69abff6680c4992efb67c4c3b17ddf435724",
          "sha1": "c0daea9311d0b7ce2c6d3a2e934f7b7783c1c9fa",
          "md5": "5afca2937c4fcbef1832573b18eba4db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.10-javadoc.jar",
          "url": "projektor-common-3.6.10-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
