{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.23.jar",
          "url": "projektor-settings-plugin-3.5.23.jar",
          "size": 53196,
          "sha512": "f364be916269e6e71130a4cbcbd6f0a7bc9ed5c28693e87d06aefe983848e9e8bde8ded1e4f74c2ec7594d410edb4d1512addf2c3b207751420d8769ac4e5548",
          "sha256": "e2295873d610bdb49e65336b908835c124d46cfc588687cc25bb136b39cbd6e8",
          "sha1": "4fd8009ab58a373d0c8c436897cba9e629dc70fc",
          "md5": "42f7749e56469405a7afa973a264a3c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.23.jar",
          "url": "projektor-settings-plugin-3.5.23.jar",
          "size": 53196,
          "sha512": "f364be916269e6e71130a4cbcbd6f0a7bc9ed5c28693e87d06aefe983848e9e8bde8ded1e4f74c2ec7594d410edb4d1512addf2c3b207751420d8769ac4e5548",
          "sha256": "e2295873d610bdb49e65336b908835c124d46cfc588687cc25bb136b39cbd6e8",
          "sha1": "4fd8009ab58a373d0c8c436897cba9e629dc70fc",
          "md5": "42f7749e56469405a7afa973a264a3c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.23-sources.jar",
          "url": "projektor-settings-plugin-3.5.23-sources.jar",
          "size": 11283,
          "sha512": "72efd6ac9280968744d7a59f880d39787547192da21f51dc27d96455ad5931e895ac8d40108b2b149c574ecc24fe5b38c68a5272278f8179ed57ebe9f0843f1f",
          "sha256": "e0ca1cd49931e6069737994d33050e66b22b5be78d1e523b2cf721649ded36fb",
          "sha1": "e54612747a76e5b8ea3a28dc92997ec4638eef27",
          "md5": "30bdbda1b5a3eba91877eb4ef8361990"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.23-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.23-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
