{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.6.jar",
          "url": "projektor-settings-plugin-3.5.6.jar",
          "size": 49976,
          "sha512": "50133ff163c7e74d5e49caae8337594366ec192a4861baded56b692435f50f0587fa0d4e8037919a39df953c969bdbabe68eed444f8b54c8dd94d39270de6917",
          "sha256": "872e44195087f6e44942f9a481ce11384b49505f1fb149b4fd3cc6e5ee0bc129",
          "sha1": "983012f7fed34e9d19c067e8d8cb309d3b4236a9",
          "md5": "7c2778afe45817ab84a2b74869437913"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.6.jar",
          "url": "projektor-settings-plugin-3.5.6.jar",
          "size": 49976,
          "sha512": "50133ff163c7e74d5e49caae8337594366ec192a4861baded56b692435f50f0587fa0d4e8037919a39df953c969bdbabe68eed444f8b54c8dd94d39270de6917",
          "sha256": "872e44195087f6e44942f9a481ce11384b49505f1fb149b4fd3cc6e5ee0bc129",
          "sha1": "983012f7fed34e9d19c067e8d8cb309d3b4236a9",
          "md5": "7c2778afe45817ab84a2b74869437913"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.6-sources.jar",
          "url": "projektor-settings-plugin-3.5.6-sources.jar",
          "size": 10687,
          "sha512": "eaea40ef62ab0e02c168181a433daf3b799c678c19c1b7a994cff34075181f91a6a711b48d9d12258859fc96efca8c8bea3cda26b9740306b9d0adc6142af556",
          "sha256": "ab49ca72a22b0d07231b39ad191d3e4c5c618d24cb54e4ec2c85f6221947da28",
          "sha1": "fc4494040de63d85981143de818e45533b9a1cec",
          "md5": "3c7d0d5d5bae7e4ff36cba7a0a8b2412"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.6-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.6-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
