{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "6.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-6.0.4.jar",
          "url": "project-plugin-6.0.4.jar",
          "size": 301156,
          "sha512": "9e6bdcd8852effcf911985cc5692ef1d54f5b4eb1fd80880c1ba45d81599f89d6d4072e4b164442d0854fea910e9fd75ee65d97140039eda1a24d4c8a0f6ffc3",
          "sha256": "4dce4a37134a23a2cb9d894f471a986fd0e53e571997596e401eb13da6d266e1",
          "sha1": "dff1a87d2e8950959f29e9798c14d478310caa7f",
          "md5": "4a18d522e86cd2f19a519f388ad75769"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.9"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-6.0.4.jar",
          "url": "project-plugin-6.0.4.jar",
          "size": 301156,
          "sha512": "9e6bdcd8852effcf911985cc5692ef1d54f5b4eb1fd80880c1ba45d81599f89d6d4072e4b164442d0854fea910e9fd75ee65d97140039eda1a24d4c8a0f6ffc3",
          "sha256": "4dce4a37134a23a2cb9d894f471a986fd0e53e571997596e401eb13da6d266e1",
          "sha1": "dff1a87d2e8950959f29e9798c14d478310caa7f",
          "md5": "4a18d522e86cd2f19a519f388ad75769"
        }
      ]
    }
  ]
}
