{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.7.1.jar",
          "url": "projektor-project-plugin-4.7.1.jar",
          "size": 996839,
          "sha512": "0ca061bfb131639c5b8f47c0e5589b0221d116eb8a5431a0e8c7ca0c0229613a841b8ddd53452ede10fd3bffafd434cde2f656a9813f5c54a851751a6c3005bb",
          "sha256": "4aaaf111c8098ac4f698a5a1bef32957390b965b65877d915f24f4e3d5175725",
          "sha1": "0949fdbc17e40ca950267907f2482361066e1581",
          "md5": "40d2abb63ed338c3df572e5108ef19c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.parchmentmc.librarian.forgegradle",
          "module": "org.parchmentmc.librarian.forgegradle.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "fabric-loom",
          "module": "fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "com.modrinth.minotaur.gradle.plugin",
          "version": {
            "requires": "2.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.7.1.jar",
          "url": "projektor-project-plugin-4.7.1.jar",
          "size": 996839,
          "sha512": "0ca061bfb131639c5b8f47c0e5589b0221d116eb8a5431a0e8c7ca0c0229613a841b8ddd53452ede10fd3bffafd434cde2f656a9813f5c54a851751a6c3005bb",
          "sha256": "4aaaf111c8098ac4f698a5a1bef32957390b965b65877d915f24f4e3d5175725",
          "sha1": "0949fdbc17e40ca950267907f2482361066e1581",
          "md5": "40d2abb63ed338c3df572e5108ef19c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.7.1-sources.jar",
          "url": "projektor-project-plugin-4.7.1-sources.jar",
          "size": 93321,
          "sha512": "356e08b61df2bff0389dcf525d2af19fcf666585422eb497337d268ba9f76c9a04daa23fd6b5bb7e2a9aa70845156ac9f0b2c16b12749f41a395c60dfed0a284",
          "sha256": "8e53318ba8a0993be8d9c77663ecd4d5740124cf6d0046849f8148f8bbbf94e2",
          "sha1": "2d24c64c8e8431be95b0db69d369beb640986c85",
          "md5": "a5e926d07b77ddfa044bf4d7f68bc128"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.7.1-javadoc.jar",
          "url": "projektor-project-plugin-4.7.1-javadoc.jar",
          "size": 261,
          "sha512": "88afec7b6c1e79f34fce4162f3e4abe61105bcf972ae9165301b2146ab71669c6c05cc32b6ed2d0b022d01071f77a1e6733f5f1e926a32958879d036950998e3",
          "sha256": "cb125cbb841e7c033ff255dc4b5199ef445e7b00bd2cef691a56d3979c9c64c2",
          "sha1": "98b3f8a9c8fef64f89ca6bfeecaf6e59e365a212",
          "md5": "7cd9637e5318d8a63e7d314637b7ae02"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.7.1.jar",
          "url": "projektor-project-plugin-4.7.1.jar",
          "size": 996839,
          "sha512": "0ca061bfb131639c5b8f47c0e5589b0221d116eb8a5431a0e8c7ca0c0229613a841b8ddd53452ede10fd3bffafd434cde2f656a9813f5c54a851751a6c3005bb",
          "sha256": "4aaaf111c8098ac4f698a5a1bef32957390b965b65877d915f24f4e3d5175725",
          "sha1": "0949fdbc17e40ca950267907f2482361066e1581",
          "md5": "40d2abb63ed338c3df572e5108ef19c4"
        }
      ]
    }
  ]
}
