{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor",
    "version": "8.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-8.0.3.jar",
          "url": "projektor-8.0.3.jar",
          "size": 302589,
          "sha512": "d847b1b36ec24c4c5d855d361f2efee06cebf56521e8340ee65a0c26c6b102e2b8b72a31c4f11db1b1fd7b14135a5b66852d136f38cf1840c8274ee63c53b64c",
          "sha256": "366f113bdb798c426da111a712bea1145f8dc6112d8471e98da73ef0520cdd42",
          "sha1": "bf48ebd3e21630b7c8d72ea5e261e125e30d03b5",
          "md5": "ad014aed3605bd690b5e9e026527812a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-8.0.3.jar",
          "url": "projektor-8.0.3.jar",
          "size": 302589,
          "sha512": "d847b1b36ec24c4c5d855d361f2efee06cebf56521e8340ee65a0c26c6b102e2b8b72a31c4f11db1b1fd7b14135a5b66852d136f38cf1840c8274ee63c53b64c",
          "sha256": "366f113bdb798c426da111a712bea1145f8dc6112d8471e98da73ef0520cdd42",
          "sha1": "bf48ebd3e21630b7c8d72ea5e261e125e30d03b5",
          "md5": "ad014aed3605bd690b5e9e026527812a"
        }
      ]
    }
  ]
}
