{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "3.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.6.7.jar",
          "url": "projektor-project-plugin-3.6.7.jar",
          "size": 441922,
          "sha512": "78b0a89ee75ccd383582ffe8624a38f3192bdb1efa14886a2150dff025f855e17462d78397729204479481da7c366b057189f395bcbc6f4eb5b5a50ca426a59c",
          "sha256": "0ce1ee150fb9df5f816a3fb98025315cbeada17176923721427e2fdd4a337a89",
          "sha1": "098ccf9099bd6ac9e0bca4a56370aa9fc967b6e7",
          "md5": "bb27f6cf7bf1358e5fde8c44200f5a77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-3.6.7.jar",
          "url": "projektor-project-plugin-3.6.7.jar",
          "size": 441922,
          "sha512": "78b0a89ee75ccd383582ffe8624a38f3192bdb1efa14886a2150dff025f855e17462d78397729204479481da7c366b057189f395bcbc6f4eb5b5a50ca426a59c",
          "sha256": "0ce1ee150fb9df5f816a3fb98025315cbeada17176923721427e2fdd4a337a89",
          "sha1": "098ccf9099bd6ac9e0bca4a56370aa9fc967b6e7",
          "md5": "bb27f6cf7bf1358e5fde8c44200f5a77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.6.7-sources.jar",
          "url": "projektor-project-plugin-3.6.7-sources.jar",
          "size": 67719,
          "sha512": "bb5e350a60d943b0e2f561fec613122dd02e0482f95fa1e706a3e423f3ce83a769fd8f8381f49c7ae228f22cfc79d8de0390d619253ae43ac9c411028b3ea04e",
          "sha256": "2ec2e46ee1a0e17957023618d9abe0b7f05df64562fda154b58af53aa07aac4b",
          "sha1": "59f65c84aa98518bd8ba082dc65642c6eca6199e",
          "md5": "fdb9ee499aae9b5f5946909469694382"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.6.7-javadoc.jar",
          "url": "projektor-project-plugin-3.6.7-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
