{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.2.jar",
          "url": "projektor-settings-plugin-3.6.2.jar",
          "size": 52919,
          "sha512": "46e90adedd053f8d4c2200fc749b2c9ad6a514699222473ed46c4099224cb37027dee88b6ad0891aa312a0694a533da2a7088019902d1d45cefd2d70634b8549",
          "sha256": "119ee8690709302a099509e268c96451bdd600796c123a13f62cdadad4dc9e07",
          "sha1": "05dba547d46702e876d09aacdc5020924259f27c",
          "md5": "2b936afdab2360d908ae5c9e4e27eb8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.2.jar",
          "url": "projektor-settings-plugin-3.6.2.jar",
          "size": 52919,
          "sha512": "46e90adedd053f8d4c2200fc749b2c9ad6a514699222473ed46c4099224cb37027dee88b6ad0891aa312a0694a533da2a7088019902d1d45cefd2d70634b8549",
          "sha256": "119ee8690709302a099509e268c96451bdd600796c123a13f62cdadad4dc9e07",
          "sha1": "05dba547d46702e876d09aacdc5020924259f27c",
          "md5": "2b936afdab2360d908ae5c9e4e27eb8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.2-sources.jar",
          "url": "projektor-settings-plugin-3.6.2-sources.jar",
          "size": 11207,
          "sha512": "961cc5386ef0f47adc6ff0c68f9469a19c1a8f2cffbd9b35ba01fa9d33b2855be6bff2f7a208901685bc3ab373d20e18e16b3ac6e40d3b602993dcb7f08acd2f",
          "sha256": "d0eae1da4ade5fa9b41fbab268b62416e65da4c5096b76650ce0f284e6e2bb8c",
          "sha1": "8b3575545d75888f70e4ff32084066835e8d13b3",
          "md5": "65fdcf3acb945fb89494c9cb0c89d8a1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.2-javadoc.jar",
          "url": "projektor-settings-plugin-3.6.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
