{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.2.jar",
          "url": "projektor-settings-plugin-4.6.2.jar",
          "size": 310559,
          "sha512": "06f47cd93d667c4e21e54335f618df92b8f806fcd024f804ece38e7661a980e012f7d629bf00cbefa054d50516bd85d38619ae42dafd508fb493dcd5f2335037",
          "sha256": "209b37db5011ff05699c0c3d351c9935fd62a86fff8a2c1e01c3cbf21a8b7afe",
          "sha1": "60f24dacff7ea4a13f6e614c10b0b102eb4c397a",
          "md5": "d564a6da21caa905e89810651e323e8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.15"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.6.13"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.2.jar",
          "url": "projektor-settings-plugin-4.6.2.jar",
          "size": 310559,
          "sha512": "06f47cd93d667c4e21e54335f618df92b8f806fcd024f804ece38e7661a980e012f7d629bf00cbefa054d50516bd85d38619ae42dafd508fb493dcd5f2335037",
          "sha256": "209b37db5011ff05699c0c3d351c9935fd62a86fff8a2c1e01c3cbf21a8b7afe",
          "sha1": "60f24dacff7ea4a13f6e614c10b0b102eb4c397a",
          "md5": "d564a6da21caa905e89810651e323e8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.2-sources.jar",
          "url": "projektor-settings-plugin-4.6.2-sources.jar",
          "size": 11956,
          "sha512": "e8459b985e49444d398b0e2717f0623023ab14b32bf0a6281429ce268138adf99cc6059a8c8e159e5b2986ec8b8827936bbe0553c5e1b8c1b6c17960cdccfab3",
          "sha256": "8725515143e6e5982e4825af0fe78f2ee62e4f59a16dca4b05ab7a1a0a0ef986",
          "sha1": "e0e504042e888b3769dfe16c2e8a5db595efa35e",
          "md5": "4a90ae721045db4a813ff3dba013bb02"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.2-javadoc.jar",
          "url": "projektor-settings-plugin-4.6.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.2.jar",
          "url": "projektor-settings-plugin-4.6.2.jar",
          "size": 310559,
          "sha512": "06f47cd93d667c4e21e54335f618df92b8f806fcd024f804ece38e7661a980e012f7d629bf00cbefa054d50516bd85d38619ae42dafd508fb493dcd5f2335037",
          "sha256": "209b37db5011ff05699c0c3d351c9935fd62a86fff8a2c1e01c3cbf21a8b7afe",
          "sha1": "60f24dacff7ea4a13f6e614c10b0b102eb4c397a",
          "md5": "d564a6da21caa905e89810651e323e8c"
        }
      ]
    }
  ]
}
