{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.4.4.jar",
          "url": "projektor-common-3.4.4.jar",
          "size": 18573,
          "sha512": "8e7d736a5ff31efb399d65b18012ad5f7a6f72bda6271ae8992750b9c1d555d4d0d15c01cf0e23cc9c28c77f24a69d72bafec650443407309eff2f040001cacb",
          "sha256": "7f5f8380ec6e7af528ead0dc4d70cf9ba3ef291adedd4d6b3e82cd5319cd9ad0",
          "sha1": "d67c803b4570ffdacfcee1bf738ebd099731891d",
          "md5": "615746e2589d80a4aa25351cea4fd80f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.4.4.jar",
          "url": "projektor-common-3.4.4.jar",
          "size": 18573,
          "sha512": "8e7d736a5ff31efb399d65b18012ad5f7a6f72bda6271ae8992750b9c1d555d4d0d15c01cf0e23cc9c28c77f24a69d72bafec650443407309eff2f040001cacb",
          "sha256": "7f5f8380ec6e7af528ead0dc4d70cf9ba3ef291adedd4d6b3e82cd5319cd9ad0",
          "sha1": "d67c803b4570ffdacfcee1bf738ebd099731891d",
          "md5": "615746e2589d80a4aa25351cea4fd80f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.4-sources.jar",
          "url": "projektor-common-3.4.4-sources.jar",
          "size": 4989,
          "sha512": "9c12b33ceab2058725913155592fcfd502677b49c556c4329a3247945bb3a27f2bca5a07453981c6d523ac2bc34a4d416b900737b81a1a7836b4fa88c9491af8",
          "sha256": "ce0c11c461a2a604c5f8afe8cb0c0a5400c001e378c91749a1ad63794af3fb41",
          "sha1": "88955ad2b6da5712a9de1b5a4541f1302f2b832e",
          "md5": "81afa60bc0acf269852fa8e28377fd5e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.4-javadoc.jar",
          "url": "projektor-common-3.4.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
