{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.5.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.5.22.jar",
          "url": "projektor-common-3.5.22.jar",
          "size": 46300,
          "sha512": "717637e06df32d5b1cd39f4d4a9f5c8531a94255fdcc3e4e114ed4e65e33ea4e19e7db6b96eee1663522bb586803e8a302b4e899d7d56b89a848810e09a2e91e",
          "sha256": "84885c2751eff1c323593acc6a222d0949379c36142dd0a1080e50f6dc274db2",
          "sha1": "1e8b84e5255131ea4b4358722a940d7b7415be66",
          "md5": "420f64e1338ebd6eb31424fca1c2ff49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.5.22.jar",
          "url": "projektor-common-3.5.22.jar",
          "size": 46300,
          "sha512": "717637e06df32d5b1cd39f4d4a9f5c8531a94255fdcc3e4e114ed4e65e33ea4e19e7db6b96eee1663522bb586803e8a302b4e899d7d56b89a848810e09a2e91e",
          "sha256": "84885c2751eff1c323593acc6a222d0949379c36142dd0a1080e50f6dc274db2",
          "sha1": "1e8b84e5255131ea4b4358722a940d7b7415be66",
          "md5": "420f64e1338ebd6eb31424fca1c2ff49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.5.22-sources.jar",
          "url": "projektor-common-3.5.22-sources.jar",
          "size": 11665,
          "sha512": "29a75289b1ceb81dcb9ba897e0a58e7b9884982d05c5a0178b85b8407f943e16c59a7b7518a1a27a000825178759f0e8ff88d1810cfce3903fc803a82939e3cd",
          "sha256": "6238ca504fe57b5fddf87e06ca36661f90726d7ced9c766b0438c13260f828c0",
          "sha1": "c9eb8dd08dcffb445c6ec7def89c1f2caa87688e",
          "md5": "9bfc121887638c9ec304a0ae42ae7fc6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.5.22-javadoc.jar",
          "url": "projektor-common-3.5.22-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
