{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.1.jar",
          "url": "projektor-settings-plugin-4.7.1.jar",
          "size": 363425,
          "sha512": "7af25d4361c4232e2b488404e8fb2656222e2df5de67e1824c4268fc38c9c353776020a56bdf04a42951d2c99fa9bbd3088da11c01b08a5713021b93a646ae1a",
          "sha256": "fc428d46dab9dfac5c36be367f6b8a877117d1ae5c2e71c68222fe04ee7078ed",
          "sha1": "332ba71f1a0d1d6041876edb1a10f8eb87379470",
          "md5": "89c77b79f1cdd29d71633cd90b92027b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.1.jar",
          "url": "projektor-settings-plugin-4.7.1.jar",
          "size": 363425,
          "sha512": "7af25d4361c4232e2b488404e8fb2656222e2df5de67e1824c4268fc38c9c353776020a56bdf04a42951d2c99fa9bbd3088da11c01b08a5713021b93a646ae1a",
          "sha256": "fc428d46dab9dfac5c36be367f6b8a877117d1ae5c2e71c68222fe04ee7078ed",
          "sha1": "332ba71f1a0d1d6041876edb1a10f8eb87379470",
          "md5": "89c77b79f1cdd29d71633cd90b92027b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.1-sources.jar",
          "url": "projektor-settings-plugin-4.7.1-sources.jar",
          "size": 12851,
          "sha512": "d215a7a4ddf33beeb78796430800dea8e17b084835e0154f5aa914a90b9bda2059847a6f66b54fcbfe1f1c3bca6ead0acaf7baaee7da408e747be78df92a13c7",
          "sha256": "a9ecb02ca013d63f29b34cf8597ad0a5d16d0dad09fd93513e1d86adaa4af318",
          "sha1": "4af54855496477f5fc76064f4d1ba5153b219213",
          "md5": "c5a5bc5c5ce6243401ce76e85aa3298b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.1-javadoc.jar",
          "url": "projektor-settings-plugin-4.7.1-javadoc.jar",
          "size": 261,
          "sha512": "fec0852d004d860bb18072faa769d47cb4a0eec573b65f9f3290917f9ddd04a57e6494d2bc2b7b92947485b2979f3e52c0bdb395e855a9c0fd536779aaac61cc",
          "sha256": "b8eaa590001f20ab6ae1445725cb50edb1e646a7ac952a1af7b76f97975c6861",
          "sha1": "e9ccd6f820fdba9cb5440c73a45683d770e16716",
          "md5": "8c069418bf809cc83ab02a325518c213"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.7.1.jar",
          "url": "projektor-settings-plugin-4.7.1.jar",
          "size": 363425,
          "sha512": "7af25d4361c4232e2b488404e8fb2656222e2df5de67e1824c4268fc38c9c353776020a56bdf04a42951d2c99fa9bbd3088da11c01b08a5713021b93a646ae1a",
          "sha256": "fc428d46dab9dfac5c36be367f6b8a877117d1ae5c2e71c68222fe04ee7078ed",
          "sha1": "332ba71f1a0d1d6041876edb1a10f8eb87379470",
          "md5": "89c77b79f1cdd29d71633cd90b92027b"
        }
      ]
    }
  ]
}
