{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.18.jar",
          "url": "projektor-settings-plugin-3.5.18.jar",
          "size": 50228,
          "sha512": "f7d516ccbac7abec571634de03c21b1b7e06652fa2e1474950d5e54380cccd8ce2ef2d4a01021de6cab904ecce99e5912c71f12d4fdb696268f978d064c66c72",
          "sha256": "f9d1b284b7630caccd55c0e1d201f9985574221c617f8b393b00691ea9530e43",
          "sha1": "f2de1ff835b07ddcfed2f8f3aa25526c1731e411",
          "md5": "d0a1f59bbb0f7426209896e742a07ce7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.18.jar",
          "url": "projektor-settings-plugin-3.5.18.jar",
          "size": 50228,
          "sha512": "f7d516ccbac7abec571634de03c21b1b7e06652fa2e1474950d5e54380cccd8ce2ef2d4a01021de6cab904ecce99e5912c71f12d4fdb696268f978d064c66c72",
          "sha256": "f9d1b284b7630caccd55c0e1d201f9985574221c617f8b393b00691ea9530e43",
          "sha1": "f2de1ff835b07ddcfed2f8f3aa25526c1731e411",
          "md5": "d0a1f59bbb0f7426209896e742a07ce7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.18-sources.jar",
          "url": "projektor-settings-plugin-3.5.18-sources.jar",
          "size": 10790,
          "sha512": "48e95042e2b40a73f9b6afbf1d6144e93ea36fc5ab3c6be58bea6f8e4f8d499eeb8d4f5f46c4bafa8b4bb848ab061a3349c79643f5404b556a36d9afb8d19e12",
          "sha256": "b2974b266be34c5bf4ae1043cf37170aaf47963ffed9004151210992bbf5747b",
          "sha1": "0572d66e91b4060838013b79b779827445d916cf",
          "md5": "00877bb00f1085dcfc7be93353ce481f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.18-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.18-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
