{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.0.0.jar",
          "url": "projektor-project-plugin-4.0.0.jar",
          "size": 509313,
          "sha512": "be332b55b1f2078efc9149bd1bb6eba15d34385b0cd8b0bd93fa8571d046832686b3da7a84b23810ffbf9bacfd92fb7fbef24d554fa51ce34cc6302c12805eec",
          "sha256": "129c48bab2ac8991c03d3691214d4d60b40955efb66cd0245c2b4fa80b6ecb3b",
          "sha1": "603221e3c2159db9a29d52713f90ccf2ecddee12",
          "md5": "51f5a4b67e3248a519360c7b76715a89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.0.0.jar",
          "url": "projektor-project-plugin-4.0.0.jar",
          "size": 509313,
          "sha512": "be332b55b1f2078efc9149bd1bb6eba15d34385b0cd8b0bd93fa8571d046832686b3da7a84b23810ffbf9bacfd92fb7fbef24d554fa51ce34cc6302c12805eec",
          "sha256": "129c48bab2ac8991c03d3691214d4d60b40955efb66cd0245c2b4fa80b6ecb3b",
          "sha1": "603221e3c2159db9a29d52713f90ccf2ecddee12",
          "md5": "51f5a4b67e3248a519360c7b76715a89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.0.0-sources.jar",
          "url": "projektor-project-plugin-4.0.0-sources.jar",
          "size": 71998,
          "sha512": "d600f851377c71ee5d881399ab08d0bced4cb94ad3300024ab36a6b9b2405695eb6d40e5485bb8205334385315bfe1b4ea8181ca6bd68b1501e3a9699898ef73",
          "sha256": "a6ec5e4e2efb8ce1a9318455b850c5f09beaf3607012f990be01153851b63fc8",
          "sha1": "c9e8a223f7dbc4b010ee396857c31a9dabd5ea42",
          "md5": "1ed15cabec9aba59954f071ec64a725f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.0.0-javadoc.jar",
          "url": "projektor-project-plugin-4.0.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.0.0.jar",
          "url": "projektor-project-plugin-4.0.0.jar",
          "size": 509313,
          "sha512": "be332b55b1f2078efc9149bd1bb6eba15d34385b0cd8b0bd93fa8571d046832686b3da7a84b23810ffbf9bacfd92fb7fbef24d554fa51ce34cc6302c12805eec",
          "sha256": "129c48bab2ac8991c03d3691214d4d60b40955efb66cd0245c2b4fa80b6ecb3b",
          "sha1": "603221e3c2159db9a29d52713f90ccf2ecddee12",
          "md5": "51f5a4b67e3248a519360c7b76715a89"
        }
      ]
    }
  ]
}
