{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.9.jar",
          "url": "projektor-project-plugin-4.6.9.jar",
          "size": 1014522,
          "sha512": "0a6671e1fe56fa1334394f0f87ff687fdee9bad689781a4f6e5c0698cc4f37bc4322a27e95f43034a8efbe12e01811b5c081a12d407eca4f22131ff6034ec815",
          "sha256": "6f286647e5b66be345332bd60136c8e1945b647e2fa484c9cc3338c0ab3ffb24",
          "sha1": "a13e7d8c0014a28e2565ea47c670633f91294430",
          "md5": "594d67e44fec8b8cdc5edcba142015cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.90.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "com.modrinth.minotaur.gradle.plugin",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.parchmentmc.librarian.forgegradle",
          "module": "org.parchmentmc.librarian.forgegradle.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "fabric-loom",
          "module": "fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.46"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.6.9.jar",
          "url": "projektor-project-plugin-4.6.9.jar",
          "size": 1014522,
          "sha512": "0a6671e1fe56fa1334394f0f87ff687fdee9bad689781a4f6e5c0698cc4f37bc4322a27e95f43034a8efbe12e01811b5c081a12d407eca4f22131ff6034ec815",
          "sha256": "6f286647e5b66be345332bd60136c8e1945b647e2fa484c9cc3338c0ab3ffb24",
          "sha1": "a13e7d8c0014a28e2565ea47c670633f91294430",
          "md5": "594d67e44fec8b8cdc5edcba142015cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.9-sources.jar",
          "url": "projektor-project-plugin-4.6.9-sources.jar",
          "size": 92452,
          "sha512": "114e6ed664f98cedc130d3ef2b5d82d9104a83520ee00e2d9d297315a94c55adcb37e3f0b4c12f2cdca352763a1549654cd5081d74ea2431dd7e870270801897",
          "sha256": "a5c830153a11d645f3cf7f2d14d9661b414da69ff168c0d84ad7fe9b44043dcf",
          "sha1": "35bd35ef2e6c73552f82604cbf54dbe47db6710b",
          "md5": "09a0b619e558752d13a550e8ab652585"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.9-javadoc.jar",
          "url": "projektor-project-plugin-4.6.9-javadoc.jar",
          "size": 261,
          "sha512": "c7da62f90f0ee90db76c8125967f712311f62f37a665d214b271fff5f4ff17db133ea2ca275d311b8100ac945d045d018fc22ebaccf8f4ecd48f41247e3db622",
          "sha256": "00b4762da4a2d3801155bd9ef6a82c1f07b97c1a31e9501bb8ec2d7035f1dd3c",
          "sha1": "432bb2ed73a45808f41ab44b82fbc8d70e163b77",
          "md5": "738b322e0fc59da99b0859d551aa14db"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.9.jar",
          "url": "projektor-project-plugin-4.6.9.jar",
          "size": 1014522,
          "sha512": "0a6671e1fe56fa1334394f0f87ff687fdee9bad689781a4f6e5c0698cc4f37bc4322a27e95f43034a8efbe12e01811b5c081a12d407eca4f22131ff6034ec815",
          "sha256": "6f286647e5b66be345332bd60136c8e1945b647e2fa484c9cc3338c0ab3ffb24",
          "sha1": "a13e7d8c0014a28e2565ea47c670633f91294430",
          "md5": "594d67e44fec8b8cdc5edcba142015cb"
        }
      ]
    }
  ]
}
