{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.3.jar",
          "url": "projektor-settings-plugin-4.6.3.jar",
          "size": 310566,
          "sha512": "9881aa6ef7a7a17e6ac53c6947c5885b1107926613088deaff7ffbe0e9a34216becea457a096d2149327f14832aa32ee67da3d374a378f0eafd656200af51118",
          "sha256": "237cac81b162f07165404a94bcc3ef54ddfe131344f15149339118bffe8927e2",
          "sha1": "2abf65579aa799267697d29549aafbabe2f95f84",
          "md5": "5617d51f6696b49ac3dd6b8ecd3a39c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.16"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.6.14"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.3.jar",
          "url": "projektor-settings-plugin-4.6.3.jar",
          "size": 310566,
          "sha512": "9881aa6ef7a7a17e6ac53c6947c5885b1107926613088deaff7ffbe0e9a34216becea457a096d2149327f14832aa32ee67da3d374a378f0eafd656200af51118",
          "sha256": "237cac81b162f07165404a94bcc3ef54ddfe131344f15149339118bffe8927e2",
          "sha1": "2abf65579aa799267697d29549aafbabe2f95f84",
          "md5": "5617d51f6696b49ac3dd6b8ecd3a39c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.3-sources.jar",
          "url": "projektor-settings-plugin-4.6.3-sources.jar",
          "size": 11956,
          "sha512": "b16591cd90e5cdd4b6e11ce295301317767d11574837615a82ecdd9a51d395a7f90c076e8875ab05799643ff9d719845688d1c10fc1fb74e7bbf3d496b89d7f5",
          "sha256": "7b43946323f523ab29a023c4552e5e868ea8c396614222b1fa1f5e460a30bd11",
          "sha1": "5469fd8143f6333ce0a4b7e16e53d7b0037091b5",
          "md5": "10334503596c41a0595da9ae7d23722f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.3-javadoc.jar",
          "url": "projektor-settings-plugin-4.6.3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.3.jar",
          "url": "projektor-settings-plugin-4.6.3.jar",
          "size": 310566,
          "sha512": "9881aa6ef7a7a17e6ac53c6947c5885b1107926613088deaff7ffbe0e9a34216becea457a096d2149327f14832aa32ee67da3d374a378f0eafd656200af51118",
          "sha256": "237cac81b162f07165404a94bcc3ef54ddfe131344f15149339118bffe8927e2",
          "sha1": "2abf65579aa799267697d29549aafbabe2f95f84",
          "md5": "5617d51f6696b49ac3dd6b8ecd3a39c4"
        }
      ]
    }
  ]
}
