{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "settings-plugin",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "settings-plugin-5.0.1.jar",
          "url": "settings-plugin-5.0.1.jar",
          "size": 99944,
          "sha512": "237a1e8040dcebc5f6c7195ac13d884addcc980183023d4728b2bf7eda4988ae4e934b12d4ad78fb857f6248fb2d1a60c73d723da88da1c83f7c8c3b2c2c6b81",
          "sha256": "18bcfb4c26a6b460314c0607a7d3297825dc4028752c56218d8a47ac8f02079a",
          "sha1": "42fc0ad0f6b1049de8e412751ab8037d17346b3f",
          "md5": "922eba7f76e94a7e6992666b1e75ab06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "settings-plugin-5.0.1.jar",
          "url": "settings-plugin-5.0.1.jar",
          "size": 99944,
          "sha512": "237a1e8040dcebc5f6c7195ac13d884addcc980183023d4728b2bf7eda4988ae4e934b12d4ad78fb857f6248fb2d1a60c73d723da88da1c83f7c8c3b2c2c6b81",
          "sha256": "18bcfb4c26a6b460314c0607a7d3297825dc4028752c56218d8a47ac8f02079a",
          "sha1": "42fc0ad0f6b1049de8e412751ab8037d17346b3f",
          "md5": "922eba7f76e94a7e6992666b1e75ab06"
        }
      ]
    }
  ]
}
