{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.4.8.jar",
          "url": "projektor-common-3.4.8.jar",
          "size": 25808,
          "sha512": "91f1c9a67eaad628769b62e0b6f3c793aa17c1e2fb2822b747193c949a8ccf8c14da76b7dc306341893c3f50efc0b3efe99d4ddb31d529b7ce0411e6d0995453",
          "sha256": "4862e5ab6bf037b8f2354880a73bd0f6a1f10c08e12227a82138f7cf2d31b3dc",
          "sha1": "ec343f8c0220f8c541e61b753559c4a8ee307acf",
          "md5": "6f8dbb25fe753aebfe33a9582e5a9e9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.4.8.jar",
          "url": "projektor-common-3.4.8.jar",
          "size": 25808,
          "sha512": "91f1c9a67eaad628769b62e0b6f3c793aa17c1e2fb2822b747193c949a8ccf8c14da76b7dc306341893c3f50efc0b3efe99d4ddb31d529b7ce0411e6d0995453",
          "sha256": "4862e5ab6bf037b8f2354880a73bd0f6a1f10c08e12227a82138f7cf2d31b3dc",
          "sha1": "ec343f8c0220f8c541e61b753559c4a8ee307acf",
          "md5": "6f8dbb25fe753aebfe33a9582e5a9e9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.8-sources.jar",
          "url": "projektor-common-3.4.8-sources.jar",
          "size": 6939,
          "sha512": "f28de2c867ace37a52038e06d5543d0dd96be5047339e281bb3e1dd036510a087d7f8e6c97d9de433575e52eb85a348667963d223a80d0327fb5a702a4ce9016",
          "sha256": "323960181d2fb6fca5f3fe3f312daf207f828cef3750b8484998813a0e055b49",
          "sha1": "4dd6d4682b0ebc6c2e1aae08ce0f6b64e58fb5cf",
          "md5": "6299a3914fb0c2150bd13c4b60994c4c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.8-javadoc.jar",
          "url": "projektor-common-3.4.8-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
