{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.7.jar",
          "url": "projektor-settings-plugin-3.4.7.jar",
          "size": 43544,
          "sha512": "b156dff93ab785c1b1ed6515a0bf8e35810d11a9808decb66fb6b9aa98c68d71f0151c04c919392415844cdc4bcc819268a258d5c3c509a12d3002e2467499da",
          "sha256": "868939ba740e3fafc4130cc988dac550527ddf4de2db577f40815cb967cd7281",
          "sha1": "eeec22ec44e86d994409aa6c90d89ca4d5bf1f9d",
          "md5": "6b9c788cc3fb7c542747e1ae23cedd2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.7.jar",
          "url": "projektor-settings-plugin-3.4.7.jar",
          "size": 43544,
          "sha512": "b156dff93ab785c1b1ed6515a0bf8e35810d11a9808decb66fb6b9aa98c68d71f0151c04c919392415844cdc4bcc819268a258d5c3c509a12d3002e2467499da",
          "sha256": "868939ba740e3fafc4130cc988dac550527ddf4de2db577f40815cb967cd7281",
          "sha1": "eeec22ec44e86d994409aa6c90d89ca4d5bf1f9d",
          "md5": "6b9c788cc3fb7c542747e1ae23cedd2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.7-sources.jar",
          "url": "projektor-settings-plugin-3.4.7-sources.jar",
          "size": 8951,
          "sha512": "ef3c117eb6a9f799c942c406129ac5b1724a5d9ed027ec273dc9df46329ad5a63b34a0320e8f70fb8f96463c374efbaa68318399ba7314ab56dab640bc6b1602",
          "sha256": "6851389f47bfd4a7bbc1522ffd3a3c7dd905f6ceccae0bff4af97da188abdc99",
          "sha1": "da6ce3a19ed3b02ed61eb302ec384611876d619e",
          "md5": "8fdcc7bcd776e61e2cd44f7a0b3e27b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.7-javadoc.jar",
          "url": "projektor-settings-plugin-3.4.7-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
