{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gradle",
    "module": "github-pages",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "github-pages-0.1.0.jar",
          "url": "github-pages-0.1.0.jar",
          "size": 3410,
          "sha512": "8f4477173b61c06863d391777e5b1242b2090428b5115693eb1b98ac6ec6d876b46f7f83e24cbae6c72da4bd9282811b9b44e3ca39005a253229869ebc5157a7",
          "sha256": "ae5bb928978e327409e5c4b439f3045011717a8bcd62bb41f296ab019a549fe5",
          "sha1": "2c1b6354c81d0d71a88e53dc46d39671edc8663e",
          "md5": "6b76839e7792c1689b953b063f5c3086"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "github-pages-0.1.0.jar",
          "url": "github-pages-0.1.0.jar",
          "size": 3410,
          "sha512": "8f4477173b61c06863d391777e5b1242b2090428b5115693eb1b98ac6ec6d876b46f7f83e24cbae6c72da4bd9282811b9b44e3ca39005a253229869ebc5157a7",
          "sha256": "ae5bb928978e327409e5c4b439f3045011717a8bcd62bb41f296ab019a549fe5",
          "sha1": "2c1b6354c81d0d71a88e53dc46d39671edc8663e",
          "md5": "6b76839e7792c1689b953b063f5c3086"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "github-pages-0.1.0-sources.jar",
          "url": "github-pages-0.1.0-sources.jar",
          "size": 1814,
          "sha512": "dbc188a22b23ebfe2060228acfab32d076ce48d42dae987c4dfe899af4a6b8dab2dd0afbb30b2c46259266dcc65d8b992e8e476ed82f7fdce392fff76b8c7913",
          "sha256": "aa967420a6e7b312f6f4ac7fe39d5fd5991a869da7230b2d40eba2a47b4144de",
          "sha1": "576d48c5d6f25e309e0e6dc4bddd8a83572ba795",
          "md5": "684f94f5d68abe25b6f9748089298c16"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "github-pages-0.1.0-javadoc.jar",
          "url": "github-pages-0.1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
