{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.6.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.10.jar",
          "url": "projektor-settings-plugin-4.6.10.jar",
          "size": 358267,
          "sha512": "17c95a5aa0ee19180205ed76b53a6a241826c390cf7e1cfb21a6d75312903dc7dcbb1331001d23cd0a72a88890556b8c0795077d600712b2f8ca3b4018497ee1",
          "sha256": "d590486b0126f4b5eeb618dbd842cdc12b7d86b9dbf24d673d9baf1abd62cc7a",
          "sha1": "9a032135ee35f591c9ba19390f7f6a6926e7b6dc",
          "md5": "d6da5cd8fc07b20b29eeb14e29148660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.10.jar",
          "url": "projektor-settings-plugin-4.6.10.jar",
          "size": 358267,
          "sha512": "17c95a5aa0ee19180205ed76b53a6a241826c390cf7e1cfb21a6d75312903dc7dcbb1331001d23cd0a72a88890556b8c0795077d600712b2f8ca3b4018497ee1",
          "sha256": "d590486b0126f4b5eeb618dbd842cdc12b7d86b9dbf24d673d9baf1abd62cc7a",
          "sha1": "9a032135ee35f591c9ba19390f7f6a6926e7b6dc",
          "md5": "d6da5cd8fc07b20b29eeb14e29148660"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.10-sources.jar",
          "url": "projektor-settings-plugin-4.6.10-sources.jar",
          "size": 12861,
          "sha512": "0e1731237e6b0b564dbe933e9d4740248e031108cf378a32a4bcf5e47182fa0b0d6ac6856baf2416ff9ea1cff11c03cbe23d7c52112b8faa37e384afb08e8247",
          "sha256": "eb2ef908e8b91114e92efe2ecc7c80fbe280e0b15012afc019180f0c1e2079ed",
          "sha1": "fae1acfda61fc9794b882907414b9ea90a5128a1",
          "md5": "78ea79f347b0f633087193b482f7072e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.10-javadoc.jar",
          "url": "projektor-settings-plugin-4.6.10-javadoc.jar",
          "size": 261,
          "sha512": "b7c8e2047ddc5d09d197852cf674490c46611d0c2633659c8b611bceb9ce988be64cdfda204b4b98678dfce961e892615ea2da08d29a0c23da0fc61d01f68695",
          "sha256": "a4c6dc31912c2fe4c66dff6a7d8f03584e7a4574a45f990b4cf2705c6eb743ea",
          "sha1": "9b62c71f4c1cd42115e92b35f5328923af8d8183",
          "md5": "68e235159af1b83f0d321c54aed17699"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.10.jar",
          "url": "projektor-settings-plugin-4.6.10.jar",
          "size": 358267,
          "sha512": "17c95a5aa0ee19180205ed76b53a6a241826c390cf7e1cfb21a6d75312903dc7dcbb1331001d23cd0a72a88890556b8c0795077d600712b2f8ca3b4018497ee1",
          "sha256": "d590486b0126f4b5eeb618dbd842cdc12b7d86b9dbf24d673d9baf1abd62cc7a",
          "sha1": "9a032135ee35f591c9ba19390f7f6a6926e7b6dc",
          "md5": "d6da5cd8fc07b20b29eeb14e29148660"
        }
      ]
    }
  ]
}
