{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.21.jar",
          "url": "projektor-settings-plugin-3.5.21.jar",
          "size": 53227,
          "sha512": "410c8975e2aa991855abbddfb1e344c7f7e14980bc9e90d23be942d960fda3a2304ce162114b1fae37401114d146239f06320a5e67ac5fa8441787bc209e611b",
          "sha256": "c80bfd56eb16eea7d232e90f6efd7b1579ad849bb34219d852d536a066bc2680",
          "sha1": "a906b2491a7b5fe3a7b54ef533dd58fa647706cc",
          "md5": "5b01766668fa5d11abd0c11bd3cd7a0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.21.jar",
          "url": "projektor-settings-plugin-3.5.21.jar",
          "size": 53227,
          "sha512": "410c8975e2aa991855abbddfb1e344c7f7e14980bc9e90d23be942d960fda3a2304ce162114b1fae37401114d146239f06320a5e67ac5fa8441787bc209e611b",
          "sha256": "c80bfd56eb16eea7d232e90f6efd7b1579ad849bb34219d852d536a066bc2680",
          "sha1": "a906b2491a7b5fe3a7b54ef533dd58fa647706cc",
          "md5": "5b01766668fa5d11abd0c11bd3cd7a0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.21-sources.jar",
          "url": "projektor-settings-plugin-3.5.21-sources.jar",
          "size": 11297,
          "sha512": "2471262c3aed358e5f3bca5987650e6a919aa4c3a074a30f82113401a49bbb5310f2e80ca2eb6aa08ef51856e6cc11ab7d6f30727549082e9be40a8bf4ad0115",
          "sha256": "b517553199fc39b8c07c40d5ac3a15813deafb09c21b17890c517fa213d8515c",
          "sha1": "f6a1d55561293b969a410171a6023f6565fde0b8",
          "md5": "eca037a72f41ede7189c252db85fa672"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.21-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.21-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
