{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.3.jar",
          "url": "projektor-settings-plugin-4.2.3.jar",
          "size": 271610,
          "sha512": "3b4ddff130ebe3f4c4a32ca674e9e957338495bc64f99b0cd334f63d2edfb0ef534bc9010396e728fcda481cff21d723928c58febf2ddc5377a51410b08a7077",
          "sha256": "2d6c7ee46f8f87d5894ed9d9c2aa2e6efae4d17a73b49076c0e218f0354013eb",
          "sha1": "47761d367d40df208176d5c957cf8bc70ecadc15",
          "md5": "3e4ffdce0e7db3632a2be7dd611f36b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.3.jar",
          "url": "projektor-settings-plugin-4.2.3.jar",
          "size": 271610,
          "sha512": "3b4ddff130ebe3f4c4a32ca674e9e957338495bc64f99b0cd334f63d2edfb0ef534bc9010396e728fcda481cff21d723928c58febf2ddc5377a51410b08a7077",
          "sha256": "2d6c7ee46f8f87d5894ed9d9c2aa2e6efae4d17a73b49076c0e218f0354013eb",
          "sha1": "47761d367d40df208176d5c957cf8bc70ecadc15",
          "md5": "3e4ffdce0e7db3632a2be7dd611f36b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.3-sources.jar",
          "url": "projektor-settings-plugin-4.2.3-sources.jar",
          "size": 11104,
          "sha512": "7a306b93ecd362ac5658f16fde42e299b5a2a56e4ce8787f1284e0b367c1540047eec72bcc8a4bb5265df57a054b7580e4155c30b085c175bf1989b37b578f49",
          "sha256": "246238dca77f14d61f56cce3e0c3df71167e1a460473579aa9f76cf68fef420d",
          "sha1": "6d8f7ea57064c69314f82b8b79cd29baa7ba8a29",
          "md5": "072260a5ad3b0323da35604016af8563"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.3-javadoc.jar",
          "url": "projektor-settings-plugin-4.2.3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.2.3.jar",
          "url": "projektor-settings-plugin-4.2.3.jar",
          "size": 271610,
          "sha512": "3b4ddff130ebe3f4c4a32ca674e9e957338495bc64f99b0cd334f63d2edfb0ef534bc9010396e728fcda481cff21d723928c58febf2ddc5377a51410b08a7077",
          "sha256": "2d6c7ee46f8f87d5894ed9d9c2aa2e6efae4d17a73b49076c0e218f0354013eb",
          "sha1": "47761d367d40df208176d5c957cf8bc70ecadc15",
          "md5": "3e4ffdce0e7db3632a2be7dd611f36b4"
        }
      ]
    }
  ]
}
