{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.3.jar",
          "url": "projektor-project-plugin-4.2.3.jar",
          "size": 654622,
          "sha512": "f3941a1057a7a4a3053dddad5c6c4a01188868e512614d5b6c6466b0518ed0463ed05211a31d03d584d2a1c37d8416d91f8ba6b0a7eefae181296f4fbb52c150",
          "sha256": "b2b50fe33c470ffc257cf00abb800199e20a62786c187a50c592460d8e0877b0",
          "sha1": "67eb81aa1313d4c27159a0c308c2ae10121becc0",
          "md5": "1a545dd1cb4f3784c58a7aa6162d685a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.2.3.jar",
          "url": "projektor-project-plugin-4.2.3.jar",
          "size": 654622,
          "sha512": "f3941a1057a7a4a3053dddad5c6c4a01188868e512614d5b6c6466b0518ed0463ed05211a31d03d584d2a1c37d8416d91f8ba6b0a7eefae181296f4fbb52c150",
          "sha256": "b2b50fe33c470ffc257cf00abb800199e20a62786c187a50c592460d8e0877b0",
          "sha1": "67eb81aa1313d4c27159a0c308c2ae10121becc0",
          "md5": "1a545dd1cb4f3784c58a7aa6162d685a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.3-sources.jar",
          "url": "projektor-project-plugin-4.2.3-sources.jar",
          "size": 69740,
          "sha512": "fdd340fda03bdbe75f1db51269c85eb68b2c6157badd8926c65a953bc87635fef70b2c081375a6ea9555d1b4cea7f05ae1246cfebb3de2e9803fec29151645f5",
          "sha256": "fdfa2e5407225a6a8428534fc2958e2ee1df22a5426627dca316955837c362da",
          "sha1": "59357ab2a76c73f359f2ad82d14b8af5ebba9529",
          "md5": "316bc05d898c5b8c7c85bf4de946f860"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.3-javadoc.jar",
          "url": "projektor-project-plugin-4.2.3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.3.jar",
          "url": "projektor-project-plugin-4.2.3.jar",
          "size": 654622,
          "sha512": "f3941a1057a7a4a3053dddad5c6c4a01188868e512614d5b6c6466b0518ed0463ed05211a31d03d584d2a1c37d8416d91f8ba6b0a7eefae181296f4fbb52c150",
          "sha256": "b2b50fe33c470ffc257cf00abb800199e20a62786c187a50c592460d8e0877b0",
          "sha1": "67eb81aa1313d4c27159a0c308c2ae10121becc0",
          "md5": "1a545dd1cb4f3784c58a7aa6162d685a"
        }
      ]
    }
  ]
}
