{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.16.jar",
          "url": "projektor-settings-plugin-3.5.16.jar",
          "size": 49977,
          "sha512": "7929429f3e5c96b075baeb21bf31bdc3fb7dfde81b5c3cc7fdd7cc386ffa0d9b8d4bd50a9811aa272cc9c7df3aaee836a0644b6c0f758965e15b8bbf1bfe7a4d",
          "sha256": "1367af8136c4cde259b5b6b30a4d936c1d5ea235f08b3c7d1ae8f8d544ba93a7",
          "sha1": "29dc91ce111b1d24340c926a691f8d815bce8cf1",
          "md5": "53bb9ff32632c35afd0c67e26c57636c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.16.jar",
          "url": "projektor-settings-plugin-3.5.16.jar",
          "size": 49977,
          "sha512": "7929429f3e5c96b075baeb21bf31bdc3fb7dfde81b5c3cc7fdd7cc386ffa0d9b8d4bd50a9811aa272cc9c7df3aaee836a0644b6c0f758965e15b8bbf1bfe7a4d",
          "sha256": "1367af8136c4cde259b5b6b30a4d936c1d5ea235f08b3c7d1ae8f8d544ba93a7",
          "sha1": "29dc91ce111b1d24340c926a691f8d815bce8cf1",
          "md5": "53bb9ff32632c35afd0c67e26c57636c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.16-sources.jar",
          "url": "projektor-settings-plugin-3.5.16-sources.jar",
          "size": 10688,
          "sha512": "fcf7baf3df1968ddc4efc7d9e8e6b956174fa34d4f0de0b41416237e2a093dc9f5d78cd8703bcb5dd56c01b8c286cae54b7957ed79c641609ad944e5c89943f8",
          "sha256": "d7c398d4798e16f957774f34f6d2bfcc10e19362bbd09b81033a21a3cdfdcb90",
          "sha1": "f79969406589d714d1211a32b9564bd5f911d36f",
          "md5": "dd104fa879d1efa841b0b13095da9be8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.16-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.16-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
