{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "5.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-5.0.8.jar",
          "url": "project-plugin-5.0.8.jar",
          "size": 304243,
          "sha512": "29bce027e3468c3ba5a34c1513dfeba68d89dbb03c493280510cf2719c10a96f630e8279580622c166c03ffea25723119b407bfb1aae9383c006701b29e39bbd",
          "sha256": "ae23a78ddb7606e33c63da7cb849545abdcd0f344612b6717dea9970a562c01f",
          "sha1": "7996fe1aea8edea411cd8ae41792184cce224476",
          "md5": "b1007303326be44f1150df96c19ab31b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.9"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-5.0.8.jar",
          "url": "project-plugin-5.0.8.jar",
          "size": 304243,
          "sha512": "29bce027e3468c3ba5a34c1513dfeba68d89dbb03c493280510cf2719c10a96f630e8279580622c166c03ffea25723119b407bfb1aae9383c006701b29e39bbd",
          "sha256": "ae23a78ddb7606e33c63da7cb849545abdcd0f344612b6717dea9970a562c01f",
          "sha1": "7996fe1aea8edea411cd8ae41792184cce224476",
          "md5": "b1007303326be44f1150df96c19ab31b"
        }
      ]
    }
  ]
}
