{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.5.0.jar",
          "url": "projektor-project-plugin-4.5.0.jar",
          "size": 766991,
          "sha512": "63f69ccc22209f042220a0fce80cc7e0ada68bda79b966588b451c621e678269ae3975b1c9a4383d328357eedd74bc53b3ce781834adcdb720b16539e5589a61",
          "sha256": "dba03c043b19ee44b9da53da9ef7ee496e8d21c0e8d2863b48952b4569da4797",
          "sha1": "37547fbff3741f1a5ca069b5f7bca7266762ac79",
          "md5": "31cf94cef7738daadf45e913614be5eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.13"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta2"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta2"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.5.0.jar",
          "url": "projektor-project-plugin-4.5.0.jar",
          "size": 766991,
          "sha512": "63f69ccc22209f042220a0fce80cc7e0ada68bda79b966588b451c621e678269ae3975b1c9a4383d328357eedd74bc53b3ce781834adcdb720b16539e5589a61",
          "sha256": "dba03c043b19ee44b9da53da9ef7ee496e8d21c0e8d2863b48952b4569da4797",
          "sha1": "37547fbff3741f1a5ca069b5f7bca7266762ac79",
          "md5": "31cf94cef7738daadf45e913614be5eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.5.0-sources.jar",
          "url": "projektor-project-plugin-4.5.0-sources.jar",
          "size": 79299,
          "sha512": "3a6fb9a769af0f6a9d197c66704657bd672780d6812271528867c2d83fa710f6b16c01f9eb4fe6876db64054e5e22b9f82fa92164d17b3ef1430a00b88c20a2f",
          "sha256": "6e09eaa06e145fd3d1d6979e9e17713074b7c046fcaea94cacac747471b56af0",
          "sha1": "24b187caa13863e892e00ca134d69811a5e9f0b7",
          "md5": "1ff9843b4711ae61d7dd85dc9d3e4f95"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.5.0-javadoc.jar",
          "url": "projektor-project-plugin-4.5.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.5.0.jar",
          "url": "projektor-project-plugin-4.5.0.jar",
          "size": 766991,
          "sha512": "63f69ccc22209f042220a0fce80cc7e0ada68bda79b966588b451c621e678269ae3975b1c9a4383d328357eedd74bc53b3ce781834adcdb720b16539e5589a61",
          "sha256": "dba03c043b19ee44b9da53da9ef7ee496e8d21c0e8d2863b48952b4569da4797",
          "sha1": "37547fbff3741f1a5ca069b5f7bca7266762ac79",
          "md5": "31cf94cef7738daadf45e913614be5eb"
        }
      ]
    }
  ]
}
