{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "3.4.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.4.17.jar",
          "url": "projektor-project-plugin-3.4.17.jar",
          "size": 386349,
          "sha512": "946cf5753fd4c48674370345728e20562ce0c21fdff2ac8a12a3a73b6baef9338fcf7ae88cc55ad44623d85df0c51e65cbef50a12045b29b19191c43dd1954e9",
          "sha256": "575fccd11547baa91d39262ffdcd9133d020aa7f01a918a6b739a1b119dead8e",
          "sha1": "58411797d0dad799a4ba66ec89c475efe3bed401",
          "md5": "3fcbfcefc19196b9e985ca03d6c06e3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-3.4.17.jar",
          "url": "projektor-project-plugin-3.4.17.jar",
          "size": 386349,
          "sha512": "946cf5753fd4c48674370345728e20562ce0c21fdff2ac8a12a3a73b6baef9338fcf7ae88cc55ad44623d85df0c51e65cbef50a12045b29b19191c43dd1954e9",
          "sha256": "575fccd11547baa91d39262ffdcd9133d020aa7f01a918a6b739a1b119dead8e",
          "sha1": "58411797d0dad799a4ba66ec89c475efe3bed401",
          "md5": "3fcbfcefc19196b9e985ca03d6c06e3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.4.17-sources.jar",
          "url": "projektor-project-plugin-3.4.17-sources.jar",
          "size": 60318,
          "sha512": "57ea8fde5c8fac2aede208c74e8d6eb3c074a31b6b3e13eca6d246b26c4e1c37e5b896666460ea29fcf14692e8e0230722076c8ecab0b205a21a68427ee24413",
          "sha256": "3b083e158d20fbef8607c20c57e65f44058e9f630c58b9a35fb0f311a8075931",
          "sha1": "9dd17e83e472aa7d68b13dce1279f674b3c2d36e",
          "md5": "889be91fa58b673dfd6ef37b0525a442"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.4.17-javadoc.jar",
          "url": "projektor-project-plugin-3.4.17-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
