{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.5.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.5.21.jar",
          "url": "projektor-common-3.5.21.jar",
          "size": 44393,
          "sha512": "37aaf36687e3db7d56efbd8b5793f01014cdf2d3943b5410f2f1d0b0ab7c1a22ef6fdc50a5a171c8272f941ef48c8b958ceea4f8bacf20acabf306baeab42ef5",
          "sha256": "ec9191da9eb5bd8d837544c1027e8defba1864044d2f83f5761362aaee4d6be9",
          "sha1": "375b6713469bc52788f081c18ed5edcf00c91dbe",
          "md5": "e52aef4e67f956e99bc15d671c525f73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.5.21.jar",
          "url": "projektor-common-3.5.21.jar",
          "size": 44393,
          "sha512": "37aaf36687e3db7d56efbd8b5793f01014cdf2d3943b5410f2f1d0b0ab7c1a22ef6fdc50a5a171c8272f941ef48c8b958ceea4f8bacf20acabf306baeab42ef5",
          "sha256": "ec9191da9eb5bd8d837544c1027e8defba1864044d2f83f5761362aaee4d6be9",
          "sha1": "375b6713469bc52788f081c18ed5edcf00c91dbe",
          "md5": "e52aef4e67f956e99bc15d671c525f73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.5.21-sources.jar",
          "url": "projektor-common-3.5.21-sources.jar",
          "size": 11171,
          "sha512": "15c060ea9f7a8fb986dc0a48a5ad4375f39df6da96b497f1f43f4a80b36bd0cbc4e532f6b1a9d8810b79a3dc329aeccc4d767e5e66ece97824bfb65985ad6a3d",
          "sha256": "8c6f1669b994f816dd04e86764067dec1c4d821e145d22ee5e36835505bbe28a",
          "sha1": "7e384d1213affdf77461ec0addfe5af898c0b42b",
          "md5": "fae4d4fcc52eb56b935fa8eed77377b2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.5.21-javadoc.jar",
          "url": "projektor-common-3.5.21-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
