{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.15.jar",
          "url": "projektor-settings-plugin-3.5.15.jar",
          "size": 49977,
          "sha512": "4a2118851c6859ba54050a2c239a8118b2d0d61019f0003c068dd2db2079273fb1039b7de14b999e97549d5c3a0cc1dcb0c79367693d7bd9c79fbd4910f70f69",
          "sha256": "d2ffdce391eb1eeaf238c152d02c74c0c2c252cc7fef612736cee2a7047ca3f7",
          "sha1": "6b4804a07f00bb2f730083570ae1d57ffd5a5060",
          "md5": "a75956b508199c024d9c96eafa7c22a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.15.jar",
          "url": "projektor-settings-plugin-3.5.15.jar",
          "size": 49977,
          "sha512": "4a2118851c6859ba54050a2c239a8118b2d0d61019f0003c068dd2db2079273fb1039b7de14b999e97549d5c3a0cc1dcb0c79367693d7bd9c79fbd4910f70f69",
          "sha256": "d2ffdce391eb1eeaf238c152d02c74c0c2c252cc7fef612736cee2a7047ca3f7",
          "sha1": "6b4804a07f00bb2f730083570ae1d57ffd5a5060",
          "md5": "a75956b508199c024d9c96eafa7c22a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.15-sources.jar",
          "url": "projektor-settings-plugin-3.5.15-sources.jar",
          "size": 10688,
          "sha512": "f5985d29827146e538c833f10927316944147e7d6dcfae471ef423904771b0a1924537dae90cba8239036864d257a5d190b712ba2fc074ca3d451de9f8966d12",
          "sha256": "79fa0d8c7491d531dec8cb43b3e51007d44a93efee5ecafd12babdfd13704012",
          "sha1": "fbbf55d9da4bad19319ac26fc964684867a5cc59",
          "md5": "b10f1c54006e256e99ae50d162b0d625"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.15-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.15-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
