{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.5.1.jar",
          "url": "projektor-project-plugin-3.5.1.jar",
          "size": 415912,
          "sha512": "10d7844dfffecb27a307187a1c5b0b4abe2b26d04e742d0448ce26a19a79fad5677c78a368400a2c37cdc1627da8d3f7f67a4565503a260bc37ed012ddcf4c90",
          "sha256": "4552f8055fdaf0d9f5153cfa0f4332b7f17c5db2429a8972bd7ef839cc0d1d8a",
          "sha1": "83cf49473f67d2dc478dbd557f9c8e874417481b",
          "md5": "8dd896147c2bd459169d247da51c8d65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-3.5.1.jar",
          "url": "projektor-project-plugin-3.5.1.jar",
          "size": 415912,
          "sha512": "10d7844dfffecb27a307187a1c5b0b4abe2b26d04e742d0448ce26a19a79fad5677c78a368400a2c37cdc1627da8d3f7f67a4565503a260bc37ed012ddcf4c90",
          "sha256": "4552f8055fdaf0d9f5153cfa0f4332b7f17c5db2429a8972bd7ef839cc0d1d8a",
          "sha1": "83cf49473f67d2dc478dbd557f9c8e874417481b",
          "md5": "8dd896147c2bd459169d247da51c8d65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.5.1-sources.jar",
          "url": "projektor-project-plugin-3.5.1-sources.jar",
          "size": 63082,
          "sha512": "10ff82a49a0fa7b34de6562d9b6a6fb81f4e8f0d918d43d993b0282f163fcdee057f0f7f6fb2dc7ef55ae46a88db10bf91c50762fb14a238fc7727b4a16f29b9",
          "sha256": "4faacee99a0106430e3d4ddaf173abbd0d0a0f718deb5b26a9f540a325839e05",
          "sha1": "8e556d2eb279b98305cd9176510515dace93d637",
          "md5": "7c21413d71a84135ea889e523436aa83"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.5.1-javadoc.jar",
          "url": "projektor-project-plugin-3.5.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
