{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.6.1.jar",
          "url": "projektor-common-3.6.1.jar",
          "size": 34134,
          "sha512": "744ed10c20983a2a3cfa460719215ecadfff1b7395a8068971d914332f3cef1a0bf71c39b3fab2a5e779552da2823eb3427f990362430f4d45572839498af6c8",
          "sha256": "33a0d70306c07d3c3db059b77fbabb2d2b142ef8f3200eb1b580a9d5eb843de4",
          "sha1": "8d71a88125dcf1d792958234b22fee0d3da491e3",
          "md5": "8889d62485db848e3589a6f67f5884a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.6.1.jar",
          "url": "projektor-common-3.6.1.jar",
          "size": 34134,
          "sha512": "744ed10c20983a2a3cfa460719215ecadfff1b7395a8068971d914332f3cef1a0bf71c39b3fab2a5e779552da2823eb3427f990362430f4d45572839498af6c8",
          "sha256": "33a0d70306c07d3c3db059b77fbabb2d2b142ef8f3200eb1b580a9d5eb843de4",
          "sha1": "8d71a88125dcf1d792958234b22fee0d3da491e3",
          "md5": "8889d62485db848e3589a6f67f5884a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.1-sources.jar",
          "url": "projektor-common-3.6.1-sources.jar",
          "size": 9447,
          "sha512": "6e4943229c9225c294ff941b3b697c7e78f6acb818d84ed503ed3daf0c67c8255e7a914f0da28f88791733767b95bce487fd91aa7d3c5d82c1244ee0cad17196",
          "sha256": "552e5ca2a5b25520884d8de099a1135e10b79de43518dd13360d6d52bce9794d",
          "sha1": "d849b808b0ed1b40c0e5352533527ea1ea62fc7a",
          "md5": "a511322e1eecd58d49cbcdf6f2e24629"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.1-javadoc.jar",
          "url": "projektor-common-3.6.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
