{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.3.jar",
          "url": "projektor-settings-plugin-3.5.3.jar",
          "size": 49976,
          "sha512": "296d64bbe761caea741ff0fb43e5093bdefec0d109ab4e852bf341934534b34faed15f4942decc9b818f40b6c68a8b6bf246f9d36692ad7595ae68f92c94eb70",
          "sha256": "6631078d797770b65e04f358e3968ff976b5b4fc51c7975d477aa1151154886b",
          "sha1": "b7cbc04f4c06fe33c7d99f6dfd45790f1c131dac",
          "md5": "2477d421152ce2aaf5672558c23ef22d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.3.jar",
          "url": "projektor-settings-plugin-3.5.3.jar",
          "size": 49976,
          "sha512": "296d64bbe761caea741ff0fb43e5093bdefec0d109ab4e852bf341934534b34faed15f4942decc9b818f40b6c68a8b6bf246f9d36692ad7595ae68f92c94eb70",
          "sha256": "6631078d797770b65e04f358e3968ff976b5b4fc51c7975d477aa1151154886b",
          "sha1": "b7cbc04f4c06fe33c7d99f6dfd45790f1c131dac",
          "md5": "2477d421152ce2aaf5672558c23ef22d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.3-sources.jar",
          "url": "projektor-settings-plugin-3.5.3-sources.jar",
          "size": 10686,
          "sha512": "1a1d8111ab3df2dcae1a5f20c54d9c9cfd1ef9da45e2778b669d6f2072d0fc93ff7779442b23f9d432c85b2529bdf5b0b45ba03d2f7ada342fe31aeccfa2a10a",
          "sha256": "c2afcd3004146db6e50821aee6d07654314a287b13db887d9f829192d9ef277b",
          "sha1": "b397f812bbaeb8a612becfb211c4f1cdd96a0ea6",
          "md5": "35187f2c9b60cf8a536a552fc481dc0c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.3-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
