{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.3.0.jar",
          "url": "projektor-project-plugin-4.3.0.jar",
          "size": 712628,
          "sha512": "c1886f4b7712eed8e9c91b913b2150646815e6117ed7f8865bc6489ae260b955c3b15da027f1dbe5e281e1fff29ec04456b808105fdd1e05f32676a4c79586f7",
          "sha256": "938583748b511e9073bf2d846c36142fcca0ee1c3b32b5f09d943855e3e385eb",
          "sha1": "20e69ddff0d7f26520cbe207fdb0dc320f66b7e7",
          "md5": "2320f1a50709ff4b23b3645d9ce5d1be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.3.0.jar",
          "url": "projektor-project-plugin-4.3.0.jar",
          "size": 712628,
          "sha512": "c1886f4b7712eed8e9c91b913b2150646815e6117ed7f8865bc6489ae260b955c3b15da027f1dbe5e281e1fff29ec04456b808105fdd1e05f32676a4c79586f7",
          "sha256": "938583748b511e9073bf2d846c36142fcca0ee1c3b32b5f09d943855e3e385eb",
          "sha1": "20e69ddff0d7f26520cbe207fdb0dc320f66b7e7",
          "md5": "2320f1a50709ff4b23b3645d9ce5d1be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.3.0-sources.jar",
          "url": "projektor-project-plugin-4.3.0-sources.jar",
          "size": 74655,
          "sha512": "9c9a1d3acbb1db778256b8c44fedbb5e66e82dd4febce47439c163af1d1d97e3581446121c7ccadffaef8a448ebc285ba44385ea18c75084d58f3cceaffd57e1",
          "sha256": "1bbd7f0ea707647dbc5c94705f8d2b20387f9ac09da4e5e542de57eb1eaf58fa",
          "sha1": "64998c2834f0bb6d027892ce16a5c8998fc95b01",
          "md5": "151905f87a284c2ff0da70b62e43d3fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.3.0-javadoc.jar",
          "url": "projektor-project-plugin-4.3.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.3.0.jar",
          "url": "projektor-project-plugin-4.3.0.jar",
          "size": 712628,
          "sha512": "c1886f4b7712eed8e9c91b913b2150646815e6117ed7f8865bc6489ae260b955c3b15da027f1dbe5e281e1fff29ec04456b808105fdd1e05f32676a4c79586f7",
          "sha256": "938583748b511e9073bf2d846c36142fcca0ee1c3b32b5f09d943855e3e385eb",
          "sha1": "20e69ddff0d7f26520cbe207fdb0dc320f66b7e7",
          "md5": "2320f1a50709ff4b23b3645d9ce5d1be"
        }
      ]
    }
  ]
}
