{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.5.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.17.jar",
          "url": "projektor-settings-plugin-3.5.17.jar",
          "size": 49977,
          "sha512": "190155c833446d7668b5241116f2ff28e6b2c00720096616f28cfa1eccd7e966a31b7bce9c8ae0560f5073beb5e78d801a15d2fc0ee4dcee124687e280c80532",
          "sha256": "b467f400fc5aa72c4eedd8718932d7731d3f73e583e4b27e517828d6aa9ed634",
          "sha1": "5d4f550bb666ce118a761da1314857a2dc8f674e",
          "md5": "c074b30bce3def068f271e6716478e5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.17.jar",
          "url": "projektor-settings-plugin-3.5.17.jar",
          "size": 49977,
          "sha512": "190155c833446d7668b5241116f2ff28e6b2c00720096616f28cfa1eccd7e966a31b7bce9c8ae0560f5073beb5e78d801a15d2fc0ee4dcee124687e280c80532",
          "sha256": "b467f400fc5aa72c4eedd8718932d7731d3f73e583e4b27e517828d6aa9ed634",
          "sha1": "5d4f550bb666ce118a761da1314857a2dc8f674e",
          "md5": "c074b30bce3def068f271e6716478e5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.17-sources.jar",
          "url": "projektor-settings-plugin-3.5.17-sources.jar",
          "size": 10688,
          "sha512": "c4eb0816938656fc710622b279966dc9ddcb1057a5a2789221c2f397a28d8cb152ea86df8ca109dff2aeba367cccc98f403f69e666295c1a5bfaf485dbf0efd0",
          "sha256": "9342ed08b8ec175a7f72775dc4838566bbfa3a847f21c1255460856dd824bfe2",
          "sha1": "655dd26ebb8c16d941f2027c2487baa48b3c2c82",
          "md5": "4d0f3280ce30ddfb6f554f4488084541"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.5.17-javadoc.jar",
          "url": "projektor-settings-plugin-3.5.17-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
