{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.6.12.jar",
          "url": "projektor-common-3.6.12.jar",
          "size": 51071,
          "sha512": "8685709816cf34cd65f84234d18172614bff50885b36cdec653f6c5671c807eb2f5958bd658aee53c8a1a12d1e2ca2693585794f5fe26a5c903e6079bb82c3b9",
          "sha256": "0dfc4cee82586c5108e661c028e62e8825fb293dc1e663150b8859514ea2d492",
          "sha1": "413feb43202dba947b7c6e78a94191398762f4ff",
          "md5": "8a5960dbb01b32e113087c1f4b17df96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.6.12.jar",
          "url": "projektor-common-3.6.12.jar",
          "size": 51071,
          "sha512": "8685709816cf34cd65f84234d18172614bff50885b36cdec653f6c5671c807eb2f5958bd658aee53c8a1a12d1e2ca2693585794f5fe26a5c903e6079bb82c3b9",
          "sha256": "0dfc4cee82586c5108e661c028e62e8825fb293dc1e663150b8859514ea2d492",
          "sha1": "413feb43202dba947b7c6e78a94191398762f4ff",
          "md5": "8a5960dbb01b32e113087c1f4b17df96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.12-sources.jar",
          "url": "projektor-common-3.6.12-sources.jar",
          "size": 9664,
          "sha512": "ac74f48918ab0fc4b03356f731efe1c1d7708d0b8f46a3130fdefdf39c47db39f54bba673721198495ef31ba782a8c365a031b37e6b047ac8527273a47d00fe1",
          "sha256": "1aa7038df40aa76e9ff39fc2c6d82ab4e371bef60549b57370728f5ec997e4c6",
          "sha1": "d3e2d9b1799a1f3248f206705b7626ed6c6fb326",
          "md5": "35b1bf26135af7194936a5c0c3990da0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.6.12-javadoc.jar",
          "url": "projektor-common-3.6.12-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
