{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.1.0.jar",
          "url": "projektor-settings-plugin-4.1.0.jar",
          "size": 108130,
          "sha512": "29a6aca0c101746cda16bdc641083f0b709bf3f89cfc24c1a0cdb80250b4c469058b7a1231ee56cac357a0ab761656a90695da9d801875f449e13c5085861dc6",
          "sha256": "815780edf113a6297ddac3d5be2864d16b7e88f5d40de520d2d10afcceea8cb4",
          "sha1": "0d60b2eb3ad7cfdf383872fab17ee1bac530bcba",
          "md5": "47d59f72c19b9e3dddb93f858f8f784e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.7"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.1.0.jar",
          "url": "projektor-settings-plugin-4.1.0.jar",
          "size": 108130,
          "sha512": "29a6aca0c101746cda16bdc641083f0b709bf3f89cfc24c1a0cdb80250b4c469058b7a1231ee56cac357a0ab761656a90695da9d801875f449e13c5085861dc6",
          "sha256": "815780edf113a6297ddac3d5be2864d16b7e88f5d40de520d2d10afcceea8cb4",
          "sha1": "0d60b2eb3ad7cfdf383872fab17ee1bac530bcba",
          "md5": "47d59f72c19b9e3dddb93f858f8f784e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.1.0-sources.jar",
          "url": "projektor-settings-plugin-4.1.0-sources.jar",
          "size": 10924,
          "sha512": "8a12143a3d8589528700d7da9a4a57d390fb7cfaeac1cfb517c170df4fbace4cb661807e91cd288afc7e53efbc18f0b96fa66af2d6e70409511efc663d3b87dc",
          "sha256": "278c9b52dad558b423c91bcce6cecd2b618d332004450c95f386bffc0cc4aa60",
          "sha1": "3e54bfbe79a4f419a43bd6bfc8a0ef8be0f618a2",
          "md5": "a3a105cd394317c938918e457fd7c787"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.1.0-javadoc.jar",
          "url": "projektor-settings-plugin-4.1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.1.0.jar",
          "url": "projektor-settings-plugin-4.1.0.jar",
          "size": 108130,
          "sha512": "29a6aca0c101746cda16bdc641083f0b709bf3f89cfc24c1a0cdb80250b4c469058b7a1231ee56cac357a0ab761656a90695da9d801875f449e13c5085861dc6",
          "sha256": "815780edf113a6297ddac3d5be2864d16b7e88f5d40de520d2d10afcceea8cb4",
          "sha1": "0d60b2eb3ad7cfdf383872fab17ee1bac530bcba",
          "md5": "47d59f72c19b9e3dddb93f858f8f784e"
        }
      ]
    }
  ]
}
