{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.6.jar",
          "url": "projektor-project-plugin-4.6.6.jar",
          "size": 899402,
          "sha512": "5daaeb605ef86d0b7a93e2e28da98665630bc9c29799725966ce7cd1c11fcc0ee6c7685a9741ae98c020d16363a4f6875a6a83aceebb11fa7ed43c294559f41c",
          "sha256": "f71a1d0fb93bba123550f341161faead273594b60616b63a6455c5b8a02bd1cc",
          "sha1": "744294b38b3619806f199c42ad1c7608a9676c45",
          "md5": "2cc6c9712b3ea368404220f760c12680"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "com.modrinth.minotaur.gradle.plugin",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "fabric-loom",
          "module": "fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.44"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.6.6.jar",
          "url": "projektor-project-plugin-4.6.6.jar",
          "size": 899402,
          "sha512": "5daaeb605ef86d0b7a93e2e28da98665630bc9c29799725966ce7cd1c11fcc0ee6c7685a9741ae98c020d16363a4f6875a6a83aceebb11fa7ed43c294559f41c",
          "sha256": "f71a1d0fb93bba123550f341161faead273594b60616b63a6455c5b8a02bd1cc",
          "sha1": "744294b38b3619806f199c42ad1c7608a9676c45",
          "md5": "2cc6c9712b3ea368404220f760c12680"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.6-sources.jar",
          "url": "projektor-project-plugin-4.6.6-sources.jar",
          "size": 83263,
          "sha512": "b60ab0a91c7ab377f084e1c2bed41c8c534eb7ae27a65301deda62e97c24a84f4ed4041bae7a9096b09eb25db4168a969d05dcc630e91fc003810de3c0aae1df",
          "sha256": "b4415a5aea53ca980cf1b49bd15317bdb8dc2c470f1ea91143890447343ab69c",
          "sha1": "2c9cd02555ace6e3ebc75c42651167441629c18f",
          "md5": "fe536bad72767ba88b350410e9d40179"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.6-javadoc.jar",
          "url": "projektor-project-plugin-4.6.6-javadoc.jar",
          "size": 261,
          "sha512": "607b356e727e13d4d7a923e3b5ee463a61bef0acbcc08d95101b1cc3308629da502bfe58e3dfc4a4233f9ee82118b0abd99ff41e93a8ffc2cc2c374ea940d292",
          "sha256": "7176fa82c36e34627e37e21470d627240ae5ecda4c6fe8490d448b29529ee01b",
          "sha1": "240138956e1778f5c64e61b4b06d6a3cc5f8d1dd",
          "md5": "f8962de69867708de7f3a2598761468e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.6.jar",
          "url": "projektor-project-plugin-4.6.6.jar",
          "size": 899402,
          "sha512": "5daaeb605ef86d0b7a93e2e28da98665630bc9c29799725966ce7cd1c11fcc0ee6c7685a9741ae98c020d16363a4f6875a6a83aceebb11fa7ed43c294559f41c",
          "sha256": "f71a1d0fb93bba123550f341161faead273594b60616b63a6455c5b8a02bd1cc",
          "sha1": "744294b38b3619806f199c42ad1c7608a9676c45",
          "md5": "2cc6c9712b3ea368404220f760c12680"
        }
      ]
    }
  ]
}
