{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.1.0.jar",
          "url": "projektor-project-plugin-4.1.0.jar",
          "size": 522150,
          "sha512": "19cb62738b52496cf5f8f5db1e721ad6d239a626180aab84619c641cdb337e72b79b66a42c2fddeea1b46adf15453e35a63fe8dff22b35a5832c234146fabffd",
          "sha256": "68fb5f0d0f63cd10ea373505b76c54583471762c266ce3ebedaf533403b84b74",
          "sha1": "88fd0b4e7b0e39f75b58563982948d7f1c1cdef1",
          "md5": "d01b6e270bb3f5f7a8cbb435ec402fbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.7"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta1"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.1.0.jar",
          "url": "projektor-project-plugin-4.1.0.jar",
          "size": 522150,
          "sha512": "19cb62738b52496cf5f8f5db1e721ad6d239a626180aab84619c641cdb337e72b79b66a42c2fddeea1b46adf15453e35a63fe8dff22b35a5832c234146fabffd",
          "sha256": "68fb5f0d0f63cd10ea373505b76c54583471762c266ce3ebedaf533403b84b74",
          "sha1": "88fd0b4e7b0e39f75b58563982948d7f1c1cdef1",
          "md5": "d01b6e270bb3f5f7a8cbb435ec402fbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.1.0-sources.jar",
          "url": "projektor-project-plugin-4.1.0-sources.jar",
          "size": 75035,
          "sha512": "5d3c889c3b15ab182552b05212dcf68eadb0d50aad5fb0b8e001721462682f48db7f6cf13df5d39fffef7ebfd55e30b81e7dc2e370df4ae70c5659d4ff1e368a",
          "sha256": "f1ab930e3aa0b94d4f253cbd526177d1ccbae277e9efb1754cfe2323c6c12ccf",
          "sha1": "8d7c244928ad66e98e44c4175d0223c451f716ac",
          "md5": "7524d328bebb96a7d9e0053429907a18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.1.0-javadoc.jar",
          "url": "projektor-project-plugin-4.1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.1.0.jar",
          "url": "projektor-project-plugin-4.1.0.jar",
          "size": 522150,
          "sha512": "19cb62738b52496cf5f8f5db1e721ad6d239a626180aab84619c641cdb337e72b79b66a42c2fddeea1b46adf15453e35a63fe8dff22b35a5832c234146fabffd",
          "sha256": "68fb5f0d0f63cd10ea373505b76c54583471762c266ce3ebedaf533403b84b74",
          "sha1": "88fd0b4e7b0e39f75b58563982948d7f1c1cdef1",
          "md5": "d01b6e270bb3f5f7a8cbb435ec402fbf"
        }
      ]
    }
  ]
}
