{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.6.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.11.jar",
          "url": "projektor-settings-plugin-3.6.11.jar",
          "size": 53882,
          "sha512": "6d1f920227d17c0c3ab47fa8ef6a48f2073c180e107feed0fe61fab4f3f79dea900988497fb62d1e4d1b5cde420ee65a1ace05ae240758846726d7ab7924c18d",
          "sha256": "aa1844aee4e0d297332252708c4567d837dd891ecbdc774040764dc00d18fc90",
          "sha1": "8ad65790c3e0956bcca7bb56078693b46aaed8a0",
          "md5": "1ddf508299d8c2eedf1663a71f8fca79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.6.11"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.11.jar",
          "url": "projektor-settings-plugin-3.6.11.jar",
          "size": 53882,
          "sha512": "6d1f920227d17c0c3ab47fa8ef6a48f2073c180e107feed0fe61fab4f3f79dea900988497fb62d1e4d1b5cde420ee65a1ace05ae240758846726d7ab7924c18d",
          "sha256": "aa1844aee4e0d297332252708c4567d837dd891ecbdc774040764dc00d18fc90",
          "sha1": "8ad65790c3e0956bcca7bb56078693b46aaed8a0",
          "md5": "1ddf508299d8c2eedf1663a71f8fca79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.11-sources.jar",
          "url": "projektor-settings-plugin-3.6.11-sources.jar",
          "size": 10898,
          "sha512": "a50a01ae115856c59c63ac0818c700e3e187c036d8e79c53fa309ba9117f448f2a918d82169f6d623a643e2352329fab1ed9c3468859493c529b50b2242fb52c",
          "sha256": "9f030dc0c17aa2c8b31466e14ecc02ec78e7d88c5c061baef06f7c4f4b40b98b",
          "sha1": "a0386759c231958fe1d99a86488110aaed2b7a4a",
          "md5": "2f5a1c78ea50d2b6bc9c0686fd15dc9d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.11-javadoc.jar",
          "url": "projektor-settings-plugin-3.6.11-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
