{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.6.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.14.jar",
          "url": "projektor-settings-plugin-4.6.14.jar",
          "size": 362867,
          "sha512": "adffb4ee8d77d1f63e7f61bc9eb3b92ab1e3098d5f24d742087a093aabbf87c0c16e513a7d97a2fb0af9f9b9b393745dfd03d570511b89c3daae9deb478a329c",
          "sha256": "4bb7fd7cbc1f4c70aa4be8d04a63ae475ccea39a9ffc79c783abf79e456a3e59",
          "sha1": "eadc7c0dc5acf7260f084c890b715d7d09d7a111",
          "md5": "9b5dec4f7d99b9d5be4108adb2728589"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.14.jar",
          "url": "projektor-settings-plugin-4.6.14.jar",
          "size": 362867,
          "sha512": "adffb4ee8d77d1f63e7f61bc9eb3b92ab1e3098d5f24d742087a093aabbf87c0c16e513a7d97a2fb0af9f9b9b393745dfd03d570511b89c3daae9deb478a329c",
          "sha256": "4bb7fd7cbc1f4c70aa4be8d04a63ae475ccea39a9ffc79c783abf79e456a3e59",
          "sha1": "eadc7c0dc5acf7260f084c890b715d7d09d7a111",
          "md5": "9b5dec4f7d99b9d5be4108adb2728589"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.14-sources.jar",
          "url": "projektor-settings-plugin-4.6.14-sources.jar",
          "size": 12839,
          "sha512": "33224facf2efcd4ef79a5447bb2ee8200f4bfd17f396940dc1e89ab2ee47a295c0e22342699496d3b6e0ea9d941735be1fbcb169db5bfa9e311eb7ef170c88fb",
          "sha256": "4fc16b2e27572872d8b59ad80c70745520e1e20ccd3a3994de69cab349041853",
          "sha1": "21bdc496ce72305945ce6eba0c7d411b050cf3cf",
          "md5": "29b55a48d8e61061b35463f9730eef12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.14-javadoc.jar",
          "url": "projektor-settings-plugin-4.6.14-javadoc.jar",
          "size": 261,
          "sha512": "c5cd3ca566d74c7da1918b793d5e087a7f0a20882570d2ad43609754a8684e58ca0083b2ba7afe357bd8dac579cdc62357ee9eab18972495d1f9005ec6cab11d",
          "sha256": "d08b4406c320ec2053349fbcd43c1d906c7cbbae182015ab2ea064af8bfa1c9e",
          "sha1": "05cd12721f26653c80e73d7733e949c9e191fc08",
          "md5": "19ce057bdaed1d84478136be732860fc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.14.jar",
          "url": "projektor-settings-plugin-4.6.14.jar",
          "size": 362867,
          "sha512": "adffb4ee8d77d1f63e7f61bc9eb3b92ab1e3098d5f24d742087a093aabbf87c0c16e513a7d97a2fb0af9f9b9b393745dfd03d570511b89c3daae9deb478a329c",
          "sha256": "4bb7fd7cbc1f4c70aa4be8d04a63ae475ccea39a9ffc79c783abf79e456a3e59",
          "sha1": "eadc7c0dc5acf7260f084c890b715d7d09d7a111",
          "md5": "9b5dec4f7d99b9d5be4108adb2728589"
        }
      ]
    }
  ]
}
