{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.9.jar",
          "url": "projektor-settings-plugin-3.6.9.jar",
          "size": 54541,
          "sha512": "d07552be926a5bfe4db7d4367285af3c2d2bcc3f5ca8f6127a567b1569d2769e9eb66827948061910e09db3d345b73f770a72d811b5bca9e93df5ad3bdc34c25",
          "sha256": "af036bbe113d7ad0c973d3a34f6a12926e476438d6dde3c969ef02c1842f9955",
          "sha1": "98403223d4452a702001b60d055437af22935d77",
          "md5": "92b596884e254ad1cdef95c65f472ed6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.9.jar",
          "url": "projektor-settings-plugin-3.6.9.jar",
          "size": 54541,
          "sha512": "d07552be926a5bfe4db7d4367285af3c2d2bcc3f5ca8f6127a567b1569d2769e9eb66827948061910e09db3d345b73f770a72d811b5bca9e93df5ad3bdc34c25",
          "sha256": "af036bbe113d7ad0c973d3a34f6a12926e476438d6dde3c969ef02c1842f9955",
          "sha1": "98403223d4452a702001b60d055437af22935d77",
          "md5": "92b596884e254ad1cdef95c65f472ed6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.9-sources.jar",
          "url": "projektor-settings-plugin-3.6.9-sources.jar",
          "size": 11050,
          "sha512": "47b26a58b18655ebb04928886a2a898417525d67a6ea573ec3ebb4c1b4d78276f529d8acc59e365536a6470560e8e441c86832aae9cd32312291a534f50c8d0b",
          "sha256": "93db641bdd92a87ff4a134f4af6accb2c74c66bfd22ac3288daa3cc72a8cf2c2",
          "sha1": "d1ef8db69753f618e04dd01fc609fe7d0c289356",
          "md5": "29e5db8df82ae7ad456e5d36d5a30ccb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.9-javadoc.jar",
          "url": "projektor-settings-plugin-3.6.9-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
