{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.0.jar",
          "url": "projektor-settings-plugin-3.6.0.jar",
          "size": 52919,
          "sha512": "a1c4cfdfa5ae5cc8cac5e6d2da1d491d02cf8ca587b445d2ec4641d6ac53aa2e223f974bac74be9192ac0100e7ec40e01aa5ff58540154a948a1687e662cd9ef",
          "sha256": "95dfb236b1308ab0b881c6951b6c4390bb7ea9139dd9bb894f969cbb5479b8ce",
          "sha1": "7e7e24f4735054b4eebf680ad632484a908e5714",
          "md5": "f1c1ee24d2e696dc06157faf780f7498"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.0.jar",
          "url": "projektor-settings-plugin-3.6.0.jar",
          "size": 52919,
          "sha512": "a1c4cfdfa5ae5cc8cac5e6d2da1d491d02cf8ca587b445d2ec4641d6ac53aa2e223f974bac74be9192ac0100e7ec40e01aa5ff58540154a948a1687e662cd9ef",
          "sha256": "95dfb236b1308ab0b881c6951b6c4390bb7ea9139dd9bb894f969cbb5479b8ce",
          "sha1": "7e7e24f4735054b4eebf680ad632484a908e5714",
          "md5": "f1c1ee24d2e696dc06157faf780f7498"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.0-sources.jar",
          "url": "projektor-settings-plugin-3.6.0-sources.jar",
          "size": 11207,
          "sha512": "b7ae7db73851e1e0d9a2b4b815169a6be8cbb97ae5d93e5f2f63097b9f38d2924c0e1d04861cc6767fcdeae4adf1a8226371fc61cb1b1fd6b86f2848a92256dc",
          "sha256": "cedf1a61d3969a576b75202cda558c6eaddae6d5681b8c16412992502a954f4e",
          "sha1": "a06f18ec20ca6941bf94db44a1a0ec0d65ab73be",
          "md5": "0c2260fb13365ff4971ff0b5c649e914"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.0-javadoc.jar",
          "url": "projektor-settings-plugin-3.6.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
