{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "5.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-5.0.7.jar",
          "url": "project-plugin-5.0.7.jar",
          "size": 301847,
          "sha512": "98aae3c666d44bd79814d06ed699d92a87b000745b72bb053818ea0dccbe44b491e5dd0efdb152f1d6e5dbdac0450ace85dd53144b988167e9a9c8d53115c627",
          "sha256": "f7b940febca2db66f1dbed268198d7d0fb01ca83fbc46d93b9e06585ac82be09",
          "sha1": "56abf7985ff60fde59c44b4a8e6b1daf14f8fbbf",
          "md5": "445402af4df9aebf234e335c106fa43c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.9"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-5.0.7.jar",
          "url": "project-plugin-5.0.7.jar",
          "size": 301847,
          "sha512": "98aae3c666d44bd79814d06ed699d92a87b000745b72bb053818ea0dccbe44b491e5dd0efdb152f1d6e5dbdac0450ace85dd53144b988167e9a9c8d53115c627",
          "sha256": "f7b940febca2db66f1dbed268198d7d0fb01ca83fbc46d93b9e06585ac82be09",
          "sha1": "56abf7985ff60fde59c44b4a8e6b1daf14f8fbbf",
          "md5": "445402af4df9aebf234e335c106fa43c"
        }
      ]
    }
  ]
}
