{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.6.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.11.jar",
          "url": "projektor-settings-plugin-4.6.11.jar",
          "size": 362867,
          "sha512": "0834a362f7d4535dad3275e3e3289d860ce6299d75b5b105b7e7ce859f14c4619560e02ccf30676404e8a3f20a0774ff118de5a4acb039298e7786e50eb41161",
          "sha256": "31d8c9fd46de61e2b7c80b71b560869e0354582f125438b575eb8d0304614d24",
          "sha1": "4ce6c4f38254d7572cb49ae9b9a6ccd632f532ff",
          "md5": "727239ddecd7b9f7e1bf5d468f769969"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.11.jar",
          "url": "projektor-settings-plugin-4.6.11.jar",
          "size": 362867,
          "sha512": "0834a362f7d4535dad3275e3e3289d860ce6299d75b5b105b7e7ce859f14c4619560e02ccf30676404e8a3f20a0774ff118de5a4acb039298e7786e50eb41161",
          "sha256": "31d8c9fd46de61e2b7c80b71b560869e0354582f125438b575eb8d0304614d24",
          "sha1": "4ce6c4f38254d7572cb49ae9b9a6ccd632f532ff",
          "md5": "727239ddecd7b9f7e1bf5d468f769969"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.11-sources.jar",
          "url": "projektor-settings-plugin-4.6.11-sources.jar",
          "size": 12839,
          "sha512": "4968b2f4287fea07659d0f06b3b7768088d6bd52f4cf08cdf2a99704c95487a16a0b7234d9d1b5c9ab3bc971473592ec98312fcc284cbf9c1d40b39ec893e26d",
          "sha256": "e0df6b53bdf2d4b3178000b13a07ed5ad0871f0a939aa7345896be648985f7c1",
          "sha1": "ca39707c8b9391cf40681057638b81806b73c77f",
          "md5": "3d7c1262d919eb9873f79edaaa6b37db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.11-javadoc.jar",
          "url": "projektor-settings-plugin-4.6.11-javadoc.jar",
          "size": 261,
          "sha512": "390a5c53a2a8ba2e16aab7e3a2ae15655b1d29780b5c9b01f47cb1874b0f2b1fcfe585ad3658230394b7d5db05c0eb577696c0765503d6da08023a362a0a89dd",
          "sha256": "d3baa03580097689f3a974b0d7baa6a4496af9065a21d0443a4f550a515e61d2",
          "sha1": "95d6065e5f40b0a5d34d2c1719cf5fce8e841257",
          "md5": "5912fd752bb1d51c97d1377fe54c21e6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.11.jar",
          "url": "projektor-settings-plugin-4.6.11.jar",
          "size": 362867,
          "sha512": "0834a362f7d4535dad3275e3e3289d860ce6299d75b5b105b7e7ce859f14c4619560e02ccf30676404e8a3f20a0774ff118de5a4acb039298e7786e50eb41161",
          "sha256": "31d8c9fd46de61e2b7c80b71b560869e0354582f125438b575eb8d0304614d24",
          "sha1": "4ce6c4f38254d7572cb49ae9b9a6ccd632f532ff",
          "md5": "727239ddecd7b9f7e1bf5d468f769969"
        }
      ]
    }
  ]
}
