{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "3.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.6.9.jar",
          "url": "projektor-project-plugin-3.6.9.jar",
          "size": 437527,
          "sha512": "1771db94409e0ed2675778fea2f4de105b4d30bfefc24ed3c7d1529c1d114ce8a341db9ab05861cd719a0b4aea6e0cf82daad73ed18bdce017116e3efd6056a3",
          "sha256": "709288f0ad42d391e195535b0cb6281b84df6c44936b0db27397d9de3e1abd88",
          "sha1": "14bec1756efa73aa9ed3a245c9b66687cf6b0d4f",
          "md5": "a2ad61467211834f5a9a9f0649315d8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-3.6.9.jar",
          "url": "projektor-project-plugin-3.6.9.jar",
          "size": 437527,
          "sha512": "1771db94409e0ed2675778fea2f4de105b4d30bfefc24ed3c7d1529c1d114ce8a341db9ab05861cd719a0b4aea6e0cf82daad73ed18bdce017116e3efd6056a3",
          "sha256": "709288f0ad42d391e195535b0cb6281b84df6c44936b0db27397d9de3e1abd88",
          "sha1": "14bec1756efa73aa9ed3a245c9b66687cf6b0d4f",
          "md5": "a2ad61467211834f5a9a9f0649315d8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.6.9-sources.jar",
          "url": "projektor-project-plugin-3.6.9-sources.jar",
          "size": 67312,
          "sha512": "46339b76dad4c326afa56cb2ae6a5991b9a631f01ea569b897c3d877292e3145f7ceb081300e476b6dcb5f07b38a7283ef3ae240a682818f049d5817c7b07f34",
          "sha256": "13d63fbaa066159c6109db8edc591c454d0bb675113f142a4ab1c1e8166e7d56",
          "sha1": "bceac27a5b5cd7fd88b0b1d1d4b7644bc977db48",
          "md5": "bf7575fc2e18a86adc907d8302360506"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-3.6.9-javadoc.jar",
          "url": "projektor-project-plugin-3.6.9-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
