{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.5.1.jar",
          "url": "projektor-project-plugin-4.5.1.jar",
          "size": 784317,
          "sha512": "403cf1964d6a8d4d2798910b7e748129231ffadd28753532b792b5b22f9b508c03a653393739f32f5aced1ddde2d72d8a5a93da845982bec9eadaddaeed4cca4",
          "sha256": "a32bc1d78789b19012e6b48c432ae8a715e148c5ec62bd62728663e612e4da9a",
          "sha1": "d541af52cc994a8aaaad11de3ded7414640f32b2",
          "md5": "623437d69836bf4a698b3c4e2de4fc45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.13"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta2"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0-Beta2"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.5.1.jar",
          "url": "projektor-project-plugin-4.5.1.jar",
          "size": 784317,
          "sha512": "403cf1964d6a8d4d2798910b7e748129231ffadd28753532b792b5b22f9b508c03a653393739f32f5aced1ddde2d72d8a5a93da845982bec9eadaddaeed4cca4",
          "sha256": "a32bc1d78789b19012e6b48c432ae8a715e148c5ec62bd62728663e612e4da9a",
          "sha1": "d541af52cc994a8aaaad11de3ded7414640f32b2",
          "md5": "623437d69836bf4a698b3c4e2de4fc45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.5.1-sources.jar",
          "url": "projektor-project-plugin-4.5.1-sources.jar",
          "size": 80933,
          "sha512": "a7d4ef5723ccc110da7e76e665a6f426b840b24ef1c4d7d685bee420a436c2497806e3ef1efa5bce8de6a546777e3f93944da43da187a2370b2c4b1e1e134f18",
          "sha256": "aab32aa80e5bc10343d004db4500630eeb4639a5a344eb9f37ca2d3f6781489f",
          "sha1": "4d26e4c95e4b62c3303761f3a48b6cf54695860c",
          "md5": "c1fb17e8c9c3d23703f9e23d6252756f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.5.1-javadoc.jar",
          "url": "projektor-project-plugin-4.5.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.5.1.jar",
          "url": "projektor-project-plugin-4.5.1.jar",
          "size": 784317,
          "sha512": "403cf1964d6a8d4d2798910b7e748129231ffadd28753532b792b5b22f9b508c03a653393739f32f5aced1ddde2d72d8a5a93da845982bec9eadaddaeed4cca4",
          "sha256": "a32bc1d78789b19012e6b48c432ae8a715e148c5ec62bd62728663e612e4da9a",
          "sha1": "d541af52cc994a8aaaad11de3ded7414640f32b2",
          "md5": "623437d69836bf4a698b3c4e2de4fc45"
        }
      ]
    }
  ]
}
