{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "5.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-5.0.4.jar",
          "url": "project-plugin-5.0.4.jar",
          "size": 295822,
          "sha512": "385840471bc81e79df8611ac19ff43c5498cc54d7dcefd49b31a695852a59f48c29012cf9bbabe42fbfebc250554156310ef2c67814618a6710efa7c8e292ea9",
          "sha256": "3862442d8d807c0f731354a5b87e146bd66c08c7cbf59c1205d9cce3ba0f7ef1",
          "sha1": "bd28db5e8cab06bd5b053017c07c6789b8e01bb7",
          "md5": "4b7e6a3c3c0a26d31473c622c7091d92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.7"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-5.0.4.jar",
          "url": "project-plugin-5.0.4.jar",
          "size": 295822,
          "sha512": "385840471bc81e79df8611ac19ff43c5498cc54d7dcefd49b31a695852a59f48c29012cf9bbabe42fbfebc250554156310ef2c67814618a6710efa7c8e292ea9",
          "sha256": "3862442d8d807c0f731354a5b87e146bd66c08c7cbf59c1205d9cce3ba0f7ef1",
          "sha1": "bd28db5e8cab06bd5b053017c07c6789b8e01bb7",
          "md5": "4b7e6a3c3c0a26d31473c622c7091d92"
        }
      ]
    }
  ]
}
