{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.1.jar",
          "url": "projektor-settings-plugin-4.6.1.jar",
          "size": 310605,
          "sha512": "cbc5b785b69d103d27fde3c49af2416a4ef06e67434bbe966a51a5026859445147195e38cfe542c90d66f711181b84f28c1bcbb54156641a39fbfff0905c8804",
          "sha256": "f220ca04505672d9a40298efea6c9e636749984ea0bc98d242dc83e7a75d1cc9",
          "sha1": "8303414f4ca84c52a91edaf7d005b52a04d55c6b",
          "md5": "082e5923713a515dae51e79b9b9732af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.15"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.6.13"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.1.jar",
          "url": "projektor-settings-plugin-4.6.1.jar",
          "size": 310605,
          "sha512": "cbc5b785b69d103d27fde3c49af2416a4ef06e67434bbe966a51a5026859445147195e38cfe542c90d66f711181b84f28c1bcbb54156641a39fbfff0905c8804",
          "sha256": "f220ca04505672d9a40298efea6c9e636749984ea0bc98d242dc83e7a75d1cc9",
          "sha1": "8303414f4ca84c52a91edaf7d005b52a04d55c6b",
          "md5": "082e5923713a515dae51e79b9b9732af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.1-sources.jar",
          "url": "projektor-settings-plugin-4.6.1-sources.jar",
          "size": 11956,
          "sha512": "d510ab2e37713d765439db4fe4b484e46a2e92ca6b313e094c11f36574e57c1f5159d4ee8ee5c3eb8233a75238fe5a31391f987e87d86be91eb3bb3bea276918",
          "sha256": "d92ed04d53fca6bb4ebd2c50ed009a9b3e03b544274300062693324acb4e4547",
          "sha1": "cc0cff6b9badce2d77c8ce76c0e6b1c1e389b217",
          "md5": "4716fc3a721d610678c18908494dd088"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.1-javadoc.jar",
          "url": "projektor-settings-plugin-4.6.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.1.jar",
          "url": "projektor-settings-plugin-4.6.1.jar",
          "size": 310605,
          "sha512": "cbc5b785b69d103d27fde3c49af2416a4ef06e67434bbe966a51a5026859445147195e38cfe542c90d66f711181b84f28c1bcbb54156641a39fbfff0905c8804",
          "sha256": "f220ca04505672d9a40298efea6c9e636749984ea0bc98d242dc83e7a75d1cc9",
          "sha1": "8303414f4ca84c52a91edaf7d005b52a04d55c6b",
          "md5": "082e5923713a515dae51e79b9b9732af"
        }
      ]
    }
  ]
}
