{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.4.jar",
          "url": "projektor-project-plugin-4.2.4.jar",
          "size": 655944,
          "sha512": "67ea4d19bfa44ed0d2046f2f1615de8aa1699baccc649c19f88f59d41e6b801d71e50367cb870963b72d1394c8e2ff55bd3e022e5b1c1dbe39db50e062bb977f",
          "sha256": "7d59b75ecc77cde8e370a6eb0e33ad26022a0f7a68dae755bac50823de79724b",
          "sha1": "4896ecf08556a9af0bb218ce485b4cd40820d23a",
          "md5": "2af3b740aa3916e54055e75ec44ffd1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "plugin",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "net.neoforged.moddev.repositories",
          "module": "net.neoforged.moddev.repositories.gradle.plugin",
          "version": {
            "requires": "2.0.115"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "Minotaur",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.2.4.jar",
          "url": "projektor-project-plugin-4.2.4.jar",
          "size": 655944,
          "sha512": "67ea4d19bfa44ed0d2046f2f1615de8aa1699baccc649c19f88f59d41e6b801d71e50367cb870963b72d1394c8e2ff55bd3e022e5b1c1dbe39db50e062bb977f",
          "sha256": "7d59b75ecc77cde8e370a6eb0e33ad26022a0f7a68dae755bac50823de79724b",
          "sha1": "4896ecf08556a9af0bb218ce485b4cd40820d23a",
          "md5": "2af3b740aa3916e54055e75ec44ffd1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.4-sources.jar",
          "url": "projektor-project-plugin-4.2.4-sources.jar",
          "size": 70236,
          "sha512": "8e85480c716fa74b5c3507bccdcf2d12aa6af08306c149641f5bd5dd8175e3a0efb85ec86ee3f59e524a584fb9c7a3c68f9a5156233c74c493f5ac20e63f74eb",
          "sha256": "b438c8b29fec13f395848a980dc07a058d9b195d15ad4aca9a296b9969e2dc9a",
          "sha1": "987de9ac419e9c429ccfc0a97fbadda9cdba92a9",
          "md5": "0bd89044a1f2238c07eab6a527941323"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.4-javadoc.jar",
          "url": "projektor-project-plugin-4.2.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.2.4.jar",
          "url": "projektor-project-plugin-4.2.4.jar",
          "size": 655944,
          "sha512": "67ea4d19bfa44ed0d2046f2f1615de8aa1699baccc649c19f88f59d41e6b801d71e50367cb870963b72d1394c8e2ff55bd3e022e5b1c1dbe39db50e062bb977f",
          "sha256": "7d59b75ecc77cde8e370a6eb0e33ad26022a0f7a68dae755bac50823de79724b",
          "sha1": "4896ecf08556a9af0bb218ce485b4cd40820d23a",
          "md5": "2af3b740aa3916e54055e75ec44ffd1b"
        }
      ]
    }
  ]
}
