{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.8.jar",
          "url": "projektor-settings-plugin-3.4.8.jar",
          "size": 43562,
          "sha512": "24f7e42a6613241fc40cda8c70dccc15ff7611e25cdc0c651651ccc2b881afd5d3791f1c55f6690bfc62848a2553119b968076eb6dfe4052df812a976c5bb5a0",
          "sha256": "f57ef2f857acd883f7241b8be75c5af9e9ff373f3f1ed5914bf6d3a10bb0e371",
          "sha1": "ebd166ce67daf0ddc22a6986d32d91bfb3dd4670",
          "md5": "4f7a46e738a3da53489c02edc0d6e289"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.8.jar",
          "url": "projektor-settings-plugin-3.4.8.jar",
          "size": 43562,
          "sha512": "24f7e42a6613241fc40cda8c70dccc15ff7611e25cdc0c651651ccc2b881afd5d3791f1c55f6690bfc62848a2553119b968076eb6dfe4052df812a976c5bb5a0",
          "sha256": "f57ef2f857acd883f7241b8be75c5af9e9ff373f3f1ed5914bf6d3a10bb0e371",
          "sha1": "ebd166ce67daf0ddc22a6986d32d91bfb3dd4670",
          "md5": "4f7a46e738a3da53489c02edc0d6e289"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.8-sources.jar",
          "url": "projektor-settings-plugin-3.4.8-sources.jar",
          "size": 8958,
          "sha512": "a7677071051f45a459da7399fbdfd85800918d880773eceaad2a002b0e6d7a4281f2cfa78f2a9de691214b8050518c9e14f4af441de1e61b41e4508eaa5301c5",
          "sha256": "b2bf5b197be40cfad41f0d9055183e6ae695f03b94d70e45a4b9d105f8011c54",
          "sha1": "1de47bea32c29e9c821aab46e84b6e55d92a44f8",
          "md5": "2911507877e63dc3de23a78ad0bcfd84"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.8-javadoc.jar",
          "url": "projektor-settings-plugin-3.4.8-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
