{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.8.jar",
          "url": "projektor-settings-plugin-3.4.8.jar",
          "size": 43519,
          "sha512": "e0973513dcf63406e1c8894d8927fd12394ce2f123f52b0979c39cd6186c02977f61de11ed33becae94e99f4ae36e1981150b26bcd0456887c30f1d19929ec53",
          "sha256": "d0fcf3e83018813d67d01ab683e537a4e6630601482a4efd69c4495fbbb9aa1c",
          "sha1": "9180a2137abf57dea2a3891da25626b6b4d3c7bb",
          "md5": "85d2496e3ceb2cf786a6bca0ff07686c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.8.jar",
          "url": "projektor-settings-plugin-3.4.8.jar",
          "size": 43519,
          "sha512": "e0973513dcf63406e1c8894d8927fd12394ce2f123f52b0979c39cd6186c02977f61de11ed33becae94e99f4ae36e1981150b26bcd0456887c30f1d19929ec53",
          "sha256": "d0fcf3e83018813d67d01ab683e537a4e6630601482a4efd69c4495fbbb9aa1c",
          "sha1": "9180a2137abf57dea2a3891da25626b6b4d3c7bb",
          "md5": "85d2496e3ceb2cf786a6bca0ff07686c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.8-sources.jar",
          "url": "projektor-settings-plugin-3.4.8-sources.jar",
          "size": 8948,
          "sha512": "c08bb04e33d016e69b2024b35a9316370c25ca0ed274c5bca24665f74af2236b4c17dc16182fe20e205a2dd6617c56db658b76a3aa86e946a171071ae785fb87",
          "sha256": "d0e3ced8d6d6f9908ba5c3a5f637fe78e5365100689647faad56e04e26fa7780",
          "sha1": "e2da12c3c84c97ff6b99d0be4c3221e4a6de98f7",
          "md5": "fb4aba0c4ad7d68afa2bdc96a8becfdf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.4.8-javadoc.jar",
          "url": "projektor-settings-plugin-3.4.8-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
