{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-project-plugin",
    "version": "4.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.5.jar",
          "url": "projektor-project-plugin-4.6.5.jar",
          "size": 899402,
          "sha512": "5ff9d146e5f1d456fd62d9436dd7e8c940a75838a3cb1cbee000a5f724d06855c1c9771e17bcc5780fd9063a42c2d6a20ee0ac8f8156f93b296ab5e8173b03b6",
          "sha256": "925594c8b57912efe97b988b2fe71e9510b5cdc3feca22b58ec45e7dcba5e32f",
          "sha1": "78515aaf8f5492cab4074aa178d853c603dbe8da",
          "md5": "f10e0386119c46a25055b8a98fbaee7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "com.palantir.javapoet",
          "module": "javapoet",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "com.modrinth.minotaur",
          "module": "com.modrinth.minotaur.gradle.plugin",
          "version": {
            "requires": "2.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "com.gradleup.shadow.gradle.plugin",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "fabric-loom",
          "module": "fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "legacy-looming",
          "module": "legacy-looming.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "ploceus",
          "module": "ploceus.gradle.plugin",
          "version": {
            "requires": "1.11-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.116"
          }
        },
        {
          "group": "net.minecraftforge.gradle",
          "module": "net.minecraftforge.gradle.gradle.plugin",
          "version": {
            "requires": "6.0.44"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.squareup.okio",
          "module": "okio-jvm",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-project-plugin-4.6.5.jar",
          "url": "projektor-project-plugin-4.6.5.jar",
          "size": 899402,
          "sha512": "5ff9d146e5f1d456fd62d9436dd7e8c940a75838a3cb1cbee000a5f724d06855c1c9771e17bcc5780fd9063a42c2d6a20ee0ac8f8156f93b296ab5e8173b03b6",
          "sha256": "925594c8b57912efe97b988b2fe71e9510b5cdc3feca22b58ec45e7dcba5e32f",
          "sha1": "78515aaf8f5492cab4074aa178d853c603dbe8da",
          "md5": "f10e0386119c46a25055b8a98fbaee7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.5-sources.jar",
          "url": "projektor-project-plugin-4.6.5-sources.jar",
          "size": 83263,
          "sha512": "37acec50105b613f63687b4384b6884b154fb751d311f15af65cd52eb3114dee6899f4a4308cb644b8189676f7845fe0d9716f8deee86786418a7d62c1e2faef",
          "sha256": "c34ed72764e50a407d8bfd5abaa9854271d2c4db36bcd83aeb694dae27f13d86",
          "sha1": "462b19a064004bb78cec1422ae86b94eeaaebcd0",
          "md5": "4e53eb0b60ee3ac6d4f84f0b0428fd59"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.5-javadoc.jar",
          "url": "projektor-project-plugin-4.6.5-javadoc.jar",
          "size": 261,
          "sha512": "3acc84b36cc8cbac56920b239e3b7070e42eac97b19505502d416b31c0cef3d9a7aa8155db15286a41d9dd4ad263a4e641159b3e1c9e8171e6b65f7bca151fb6",
          "sha256": "30e9880db21f54fa91575379500d6d7db36527921fffe67f4c15d20f37ffac88",
          "sha1": "0552ac61d9527cb7e6ff7e7ea3c491a89fddfa61",
          "md5": "90fd4a06e169c33d073ed3a9f33e212b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-project-plugin-4.6.5.jar",
          "url": "projektor-project-plugin-4.6.5.jar",
          "size": 899402,
          "sha512": "5ff9d146e5f1d456fd62d9436dd7e8c940a75838a3cb1cbee000a5f724d06855c1c9771e17bcc5780fd9063a42c2d6a20ee0ac8f8156f93b296ab5e8173b03b6",
          "sha256": "925594c8b57912efe97b988b2fe71e9510b5cdc3feca22b58ec45e7dcba5e32f",
          "sha1": "78515aaf8f5492cab4074aa178d853c603dbe8da",
          "md5": "f10e0386119c46a25055b8a98fbaee7c"
        }
      ]
    }
  ]
}
