{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.5.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.5.13.jar",
          "url": "projektor-common-3.5.13.jar",
          "size": 36438,
          "sha512": "7760ec45d35fe2db969fc6f6f88164e655bd1b0ad7b9f1e10774f854d752b6a85b40fba19d3b898b68f052750c143934f2674d0edbaf7fe7753040817ba92f48",
          "sha256": "851d3dfdd48e4de2dd1f536771dfe8abedabd3b68a822281369eea9e42efcff3",
          "sha1": "ab239d3fe5169c14bdadaaf80c4eb929d094afae",
          "md5": "80649c57016111c6ca3b4c5b21296765"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.5.13.jar",
          "url": "projektor-common-3.5.13.jar",
          "size": 36438,
          "sha512": "7760ec45d35fe2db969fc6f6f88164e655bd1b0ad7b9f1e10774f854d752b6a85b40fba19d3b898b68f052750c143934f2674d0edbaf7fe7753040817ba92f48",
          "sha256": "851d3dfdd48e4de2dd1f536771dfe8abedabd3b68a822281369eea9e42efcff3",
          "sha1": "ab239d3fe5169c14bdadaaf80c4eb929d094afae",
          "md5": "80649c57016111c6ca3b4c5b21296765"
        }
      ]
    }
  ]
}
