{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor",
    "version": "8.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-8.0.1.jar",
          "url": "projektor-8.0.1.jar",
          "size": 295764,
          "sha512": "bc683ac2e996aa50da3b8d01879e0df2101fce6b3f0f97a23bcfb096d3ce589421bf37c00ff2b97d519b1b71086078a357b23643a932f7e55fe74c38de9d7012",
          "sha256": "a92ef84d6ab48c3cb178d1384e3b68b4db88964ead1749f8e5bb1cb970b0cd7c",
          "sha1": "166c2b1efbed612a71a3c974c17e50fcf87fe3ad",
          "md5": "9195a4d19a60efbd0ee5494af07abcfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-8.0.1.jar",
          "url": "projektor-8.0.1.jar",
          "size": 295764,
          "sha512": "bc683ac2e996aa50da3b8d01879e0df2101fce6b3f0f97a23bcfb096d3ce589421bf37c00ff2b97d519b1b71086078a357b23643a932f7e55fe74c38de9d7012",
          "sha256": "a92ef84d6ab48c3cb178d1384e3b68b4db88964ead1749f8e5bb1cb970b0cd7c",
          "sha1": "166c2b1efbed612a71a3c974c17e50fcf87fe3ad",
          "md5": "9195a4d19a60efbd0ee5494af07abcfc"
        }
      ]
    }
  ]
}
