{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "project-plugin",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "project-plugin-6.0.0.jar",
          "url": "project-plugin-6.0.0.jar",
          "size": 304262,
          "sha512": "ae6c58e6a37959442822bcf0d6b55405ec5ce8ec75cbf4fda855ac491fcf2af45edae38d72004555126a4a6f4dde8b275451b045ef4b014b7c8ed98bc18c0762",
          "sha256": "6d205c3d1ce9af99ac4ae36319a7fad07ad86f8cac3103b8f460e67070c4c77b",
          "sha1": "d2522b729a50ada8d9e56170dc032dd35d457cdf",
          "md5": "cee0be8997a1dd9e30947e1ae756bf8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.github.gmazzo.buildconfig",
          "module": "com.github.gmazzo.buildconfig.gradle.plugin",
          "version": {
            "requires": "6.0.9"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "project-plugin-6.0.0.jar",
          "url": "project-plugin-6.0.0.jar",
          "size": 304262,
          "sha512": "ae6c58e6a37959442822bcf0d6b55405ec5ce8ec75cbf4fda855ac491fcf2af45edae38d72004555126a4a6f4dde8b275451b045ef4b014b7c8ed98bc18c0762",
          "sha256": "6d205c3d1ce9af99ac4ae36319a7fad07ad86f8cac3103b8f460e67070c4c77b",
          "sha1": "d2522b729a50ada8d9e56170dc032dd35d457cdf",
          "md5": "cee0be8997a1dd9e30947e1ae756bf8e"
        }
      ]
    }
  ]
}
