{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "settings-plugin",
    "version": "3.5.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "settings-plugin-3.5.14.jar",
          "url": "settings-plugin-3.5.14.jar",
          "size": 49271,
          "sha512": "3542b7186ecf4bbef54fb478a4bf13c095730ffedf59679aa00f6861af602ad78a53208ff2c1a60fae727597e681965c01d3f83f3f89dcb17a1467e5cd4c3455",
          "sha256": "c54ffbcb68e8d31015fa9b10e6934044034fcc04c5762b959473e431fd2b651b",
          "sha1": "36c7e2b1647476ee4cf78bfd957ae3d1dd7d6d2a",
          "md5": "3a7cc9c8d00956c5f4930eca313251d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "settings-plugin-3.5.14.jar",
          "url": "settings-plugin-3.5.14.jar",
          "size": 49271,
          "sha512": "3542b7186ecf4bbef54fb478a4bf13c095730ffedf59679aa00f6861af602ad78a53208ff2c1a60fae727597e681965c01d3f83f3f89dcb17a1467e5cd4c3455",
          "sha256": "c54ffbcb68e8d31015fa9b10e6934044034fcc04c5762b959473e431fd2b651b",
          "sha1": "36c7e2b1647476ee4cf78bfd957ae3d1dd7d6d2a",
          "md5": "3a7cc9c8d00956c5f4930eca313251d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "settings-plugin-3.5.14-sources.jar",
          "url": "settings-plugin-3.5.14-sources.jar",
          "size": 10334,
          "sha512": "42ceee523bb4faa9b2cf5c235a8b93c2386162d73eb79b4d77fd51003d536572bdb96dc3c239414277a047767d0eafcf864dccfb384f1d9e5314f775769aacb3",
          "sha256": "3861e1c908f867025b1f8c94491f3a24d70b9a423d0aca07c24e32ef9bd4861f",
          "sha1": "9404c913057a62f7b694e8e7daf02629cbf98afd",
          "md5": "796aab68e37eb21d09972ac5ab88bd75"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "settings-plugin-3.5.14-javadoc.jar",
          "url": "settings-plugin-3.5.14-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
