{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor",
    "version": "8.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-8.0.4.jar",
          "url": "projektor-8.0.4.jar",
          "size": 304030,
          "sha512": "0e69168ffab2085a7e97c3b98f5e236c0a19f3ec5f0a83e0dd12830549214a21ed7eddeb30fdee9ed62b8bf488620e1e8e3bdff8c16312e33ca3c3b5312daa2e",
          "sha256": "9d2d13518d2d142b86adf3274d64e1dea307d98d37ae0c9e5db133a6fa70eec8",
          "sha1": "d0a68d79b82382cf601987a981912725ef231893",
          "md5": "b0238e831a08124c65d0a60c27ab0174"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-jvm",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-8.0.4.jar",
          "url": "projektor-8.0.4.jar",
          "size": 304030,
          "sha512": "0e69168ffab2085a7e97c3b98f5e236c0a19f3ec5f0a83e0dd12830549214a21ed7eddeb30fdee9ed62b8bf488620e1e8e3bdff8c16312e33ca3c3b5312daa2e",
          "sha256": "9d2d13518d2d142b86adf3274d64e1dea307d98d37ae0c9e5db133a6fa70eec8",
          "sha1": "d0a68d79b82382cf601987a981912725ef231893",
          "md5": "b0238e831a08124c65d0a60c27ab0174"
        }
      ]
    }
  ]
}
