{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-common",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-common-3.4.0.jar",
          "url": "projektor-common-3.4.0.jar",
          "size": 13123,
          "sha512": "3ec411c353693acec5093c979d5fce67ade2399bacae9c58cde20db95bc746ca59f0a7d955bd08a3be35d27b8f178f57bbeca7c8ca037ead17d42d929d6290ee",
          "sha256": "fc0a2bb5581770bbad8cd2fdae399ca098abafc8ef761edc116a41d0023294c3",
          "sha1": "e05189f2222b8c9fa18d0a5dfcc3f5eca0a72461",
          "md5": "5b1bfe5017679b6ebcbaf6cf2fa5592c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-common-3.4.0.jar",
          "url": "projektor-common-3.4.0.jar",
          "size": 13123,
          "sha512": "3ec411c353693acec5093c979d5fce67ade2399bacae9c58cde20db95bc746ca59f0a7d955bd08a3be35d27b8f178f57bbeca7c8ca037ead17d42d929d6290ee",
          "sha256": "fc0a2bb5581770bbad8cd2fdae399ca098abafc8ef761edc116a41d0023294c3",
          "sha1": "e05189f2222b8c9fa18d0a5dfcc3f5eca0a72461",
          "md5": "5b1bfe5017679b6ebcbaf6cf2fa5592c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.0-sources.jar",
          "url": "projektor-common-3.4.0-sources.jar",
          "size": 3782,
          "sha512": "6b3660cd3004e5c4c83c43438a261b6b2222601c8cfffe10ebfc2b309afb349ed45bd4bedd7629f67229a8fe96ad35e6c8ba4e1b127477ae71f55365cd71df43",
          "sha256": "1126a553dfba7f315beb9714e93be87e087f5a9b5ac82b334b670685b16a31fe",
          "sha1": "c8fdb28f437e4fcf16d7a1bdbbf9ed2a0e1df6fa",
          "md5": "f4f0e5c305dd3bf6eb653f64843107af"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-common-3.4.0-javadoc.jar",
          "url": "projektor-common-3.4.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
