{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "3.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.8.jar",
          "url": "projektor-settings-plugin-3.6.8.jar",
          "size": 50909,
          "sha512": "7bf1fa121d296e9d657245a03214c749236d1ad17c93c2e09952ba0aead1604105ab919f5dea0912ddf5d7930e362a8ab52a60c0bd94a62ce63ad9ffb7453360",
          "sha256": "196e31337b6a395d5734fa3ffe1a363f6ad2392293c191130fd3276695e63c4c",
          "sha1": "5ce862e4e64344626613257082c8af478ada2a23",
          "md5": "a37289f18fe6f775f349c4879c685bf5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "projektor-common",
          "version": {
            "requires": "3.+"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.8.jar",
          "url": "projektor-settings-plugin-3.6.8.jar",
          "size": 50909,
          "sha512": "7bf1fa121d296e9d657245a03214c749236d1ad17c93c2e09952ba0aead1604105ab919f5dea0912ddf5d7930e362a8ab52a60c0bd94a62ce63ad9ffb7453360",
          "sha256": "196e31337b6a395d5734fa3ffe1a363f6ad2392293c191130fd3276695e63c4c",
          "sha1": "5ce862e4e64344626613257082c8af478ada2a23",
          "md5": "a37289f18fe6f775f349c4879c685bf5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.8-sources.jar",
          "url": "projektor-settings-plugin-3.6.8-sources.jar",
          "size": 10846,
          "sha512": "25e4d937e6a19c65cca4fef710ea464b1939d64fb3519105a1174c84126042982375f1495eac3b65784f6113fe142e3cf92fb9683454f868cafd458882c53dcd",
          "sha256": "35fa6236e4a35b144b8a8c9b2574b5f76e229bf3b47c8f6ecc7bbe87dc3fec80",
          "sha1": "b9021dd8c41a85f736f20440277cb7b7f9a6a936",
          "md5": "1429ecbdf425300f151076bd45da5318"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-3.6.8-javadoc.jar",
          "url": "projektor-settings-plugin-3.6.8-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
