{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.4.jar",
          "url": "projektor-settings-plugin-4.6.4.jar",
          "size": 310778,
          "sha512": "612f6fcc34ce21edaa420e782fd30fe1d5baa62b99d1c4dd792cd471a4380fd7f56afc376bd848b62a2699ce76df69dbc9543f99276971f47becd464db0218c7",
          "sha256": "30f86736165be55b7fda033a6ad0697e7afa3c3941febe2178252181b2ea53c5",
          "sha1": "cb475ccdf8d7ac5ba9d44e5649903beebbd63dd7",
          "md5": "d5206e2833d812fc93e908709d50022a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.17"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.6.14"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.4.jar",
          "url": "projektor-settings-plugin-4.6.4.jar",
          "size": 310778,
          "sha512": "612f6fcc34ce21edaa420e782fd30fe1d5baa62b99d1c4dd792cd471a4380fd7f56afc376bd848b62a2699ce76df69dbc9543f99276971f47becd464db0218c7",
          "sha256": "30f86736165be55b7fda033a6ad0697e7afa3c3941febe2178252181b2ea53c5",
          "sha1": "cb475ccdf8d7ac5ba9d44e5649903beebbd63dd7",
          "md5": "d5206e2833d812fc93e908709d50022a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.4-sources.jar",
          "url": "projektor-settings-plugin-4.6.4-sources.jar",
          "size": 11956,
          "sha512": "5f85296af77e0661aa2698fd70059d85a620d3998fd2d0b53ee0c9f335f48868bcdae7b279215608a43a44bf6409597dbb0cf19325ef9386bac96b061bb2194c",
          "sha256": "4bb877819b1ae0442de44fbe3abd8419d8de097ff481b5dba1a15b054aadcffc",
          "sha1": "bc5c502a06ef2fe66b4f297b3495be67506c0813",
          "md5": "4d52846bcb4c0ee998db5b129a205d68"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.4-javadoc.jar",
          "url": "projektor-settings-plugin-4.6.4-javadoc.jar",
          "size": 261,
          "sha512": "379d6eea224d0d74abc801dce18700c962788aba6453cd42d0f645294ba68ce59dc49c4f000cbf52eedfe88443db6e84c2a633b0cf0ebdfbf599417e68ad18ce",
          "sha256": "432b8b382ab135c974da13cd0afc320bcb293c5568c1a0f5fb478e3c9927bd48",
          "sha1": "09847c63e74a19af61a2a7d0acd81c64e2c715a4",
          "md5": "80443c88daafe187bb734d92b869f848"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.6.4.jar",
          "url": "projektor-settings-plugin-4.6.4.jar",
          "size": 310778,
          "sha512": "612f6fcc34ce21edaa420e782fd30fe1d5baa62b99d1c4dd792cd471a4380fd7f56afc376bd848b62a2699ce76df69dbc9543f99276971f47becd464db0218c7",
          "sha256": "30f86736165be55b7fda033a6ad0697e7afa3c3941febe2178252181b2ea53c5",
          "sha1": "cb475ccdf8d7ac5ba9d44e5649903beebbd63dd7",
          "md5": "d5206e2833d812fc93e908709d50022a"
        }
      ]
    }
  ]
}
