{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gradle",
    "module": "github-pages-moduleB",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "github-pages-moduleB-0.1.0.jar",
          "url": "github-pages-moduleB-0.1.0.jar",
          "size": 2369,
          "sha512": "fc60b6f9bccc2f94e9eab76d772521b962b2f770c7f74223beaca2aaded126642c94661576411f73ccc4ad40f75b02bf3ef9dc1c8911c3d1dfd5bdeefe159077",
          "sha256": "7933a5bade0e30618bfe6e2abe891344c9d3a8078114753a2b8f66b5034e3c78",
          "sha1": "b050939d91ae4d0e8248e153509af3a7bc44feb3",
          "md5": "242ddf5cd3fb5c2f3d2af49a73619f79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "github-pages-moduleB-0.1.0.jar",
          "url": "github-pages-moduleB-0.1.0.jar",
          "size": 2369,
          "sha512": "fc60b6f9bccc2f94e9eab76d772521b962b2f770c7f74223beaca2aaded126642c94661576411f73ccc4ad40f75b02bf3ef9dc1c8911c3d1dfd5bdeefe159077",
          "sha256": "7933a5bade0e30618bfe6e2abe891344c9d3a8078114753a2b8f66b5034e3c78",
          "sha1": "b050939d91ae4d0e8248e153509af3a7bc44feb3",
          "md5": "242ddf5cd3fb5c2f3d2af49a73619f79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "github-pages-moduleB-0.1.0-sources.jar",
          "url": "github-pages-moduleB-0.1.0-sources.jar",
          "size": 1319,
          "sha512": "84192f23e3d17809c45a64a42a44957f595be57c4e8623188d5ab14ac231824da3a8495e86e6210f81b85d8c1c27cbc053ece3992d597c094315f5735e97e313",
          "sha256": "946386c7d8ca73e8732139ea2b91d8770b1262f0c9ba73b68ae951ec0e1415ca",
          "sha1": "d9bc34a8280f3f7b7d1e13c1f4a86b6b7b50bb98",
          "md5": "5ae73bfef8490d7fdc16dd3f4faa7f92"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "github-pages-moduleB-0.1.0-javadoc.jar",
          "url": "github-pages-moduleB-0.1.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
