{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "settings-plugin",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "settings-plugin-6.0.2.jar",
          "url": "settings-plugin-6.0.2.jar",
          "size": 99862,
          "sha512": "cecf58fb4a0896e51fdf095c4511d1dc32374787b4473b589959e9eeaa50dd39e6f82589f03c088357077652933585af490e3112c52f73e3939b705972c0b7b2",
          "sha256": "483779c97e3d58d2c6e1a1d2a7465bce916315022e4a74c6b229fac404c12224",
          "sha1": "a9230a814854a22dda29d75f7ab063529befbe38",
          "md5": "64b5351d8d3d2d4494b69a5456df675b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "settings-plugin-6.0.2.jar",
          "url": "settings-plugin-6.0.2.jar",
          "size": 99862,
          "sha512": "cecf58fb4a0896e51fdf095c4511d1dc32374787b4473b589959e9eeaa50dd39e6f82589f03c088357077652933585af490e3112c52f73e3939b705972c0b7b2",
          "sha256": "483779c97e3d58d2c6e1a1d2a7465bce916315022e4a74c6b229fac404c12224",
          "sha1": "a9230a814854a22dda29d75f7ab063529befbe38",
          "md5": "64b5351d8d3d2d4494b69a5456df675b"
        }
      ]
    }
  ]
}
