{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.diskria",
    "module": "projektor-settings-plugin",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.5.0.jar",
          "url": "projektor-settings-plugin-4.5.0.jar",
          "size": 299735,
          "sha512": "2668898947fd866566847e7b2165e8508e0b14f30ecedda68c97cc78c31bcb924e8a78e6bd8316cc87742d4dd77d4d584f8394f347da3e91be90fd0d60b51fd0",
          "sha256": "8cac14b6303759a8dc8aa9b5de6d4bce3e2a9bb3fff0fcceb0f47458470728a8",
          "sha1": "398b373690f6b699596dc51193f4ed8739aa1d5c",
          "md5": "cf89570f72b742eab9b9f89778383a84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.diskria",
          "module": "kotlin-utils",
          "version": {
            "requires": "0.7.13"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "gradle-utils",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "io.github.diskria",
          "module": "kotlin-shell-dsl",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "projektor-settings-plugin-4.5.0.jar",
          "url": "projektor-settings-plugin-4.5.0.jar",
          "size": 299735,
          "sha512": "2668898947fd866566847e7b2165e8508e0b14f30ecedda68c97cc78c31bcb924e8a78e6bd8316cc87742d4dd77d4d584f8394f347da3e91be90fd0d60b51fd0",
          "sha256": "8cac14b6303759a8dc8aa9b5de6d4bce3e2a9bb3fff0fcceb0f47458470728a8",
          "sha1": "398b373690f6b699596dc51193f4ed8739aa1d5c",
          "md5": "cf89570f72b742eab9b9f89778383a84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.5.0-sources.jar",
          "url": "projektor-settings-plugin-4.5.0-sources.jar",
          "size": 11089,
          "sha512": "993f9d5027da5368a9ce3dd1d948ea4050763affdacbec6d7dbbc592242ba5ee03dc53902547bbc4e74fda926d5bb8159fb695659cf6bab6bd52bc940372531f",
          "sha256": "8cd6811f986ab4aed758a96e52f3d75bc5c917f354687f23a2c320d17b529c05",
          "sha1": "9745d27ae69798acde1b3863ea19330885025edd",
          "md5": "93c22419020f59205e798281b63c6821"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.5.0-javadoc.jar",
          "url": "projektor-settings-plugin-4.5.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "projektor-settings-plugin-4.5.0.jar",
          "url": "projektor-settings-plugin-4.5.0.jar",
          "size": 299735,
          "sha512": "2668898947fd866566847e7b2165e8508e0b14f30ecedda68c97cc78c31bcb924e8a78e6bd8316cc87742d4dd77d4d584f8394f347da3e91be90fd0d60b51fd0",
          "sha256": "8cac14b6303759a8dc8aa9b5de6d4bce3e2a9bb3fff0fcceb0f47458470728a8",
          "sha1": "398b373690f6b699596dc51193f4ed8739aa1d5c",
          "md5": "cf89570f72b742eab9b9f89778383a84"
        }
      ]
    }
  ]
}
